// utility.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/utility.h"

void cIconToTypeName(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setMainWindow(void)

{
  GLXwinset(display,*(undefined4 *)curcontextwindows);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMMonitorFile2(void)

{
  fam_monitor_request();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void compare_dirs(undefined4 *param_1,undefined4 *param_2)

{
  strcmp(*(char **)*param_1,*(char **)*param_2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void savecontext(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMMonitorDirectory2(void)

{
  fam_monitor_request();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void shrinkDueToZoom(void)

{
  init_gl_state(FUN_00410858,0);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void hsv_to_rgb(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void myContext(undefined4 param_1,undefined4 param_2)

{
  set_gl_context(param_2,0);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cFindIconByName(undefined4 param_1)

{
  FUN_00434a88(&context_data_block,param_1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void getValue__8RuleInfoFi(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirToPath(undefined1 *param_1,int param_2)

{
  if (param_1 == (undefined1 *)0x0) {
    param_1 = &DAT_10016710;
  }
  *param_1 = 0;
  if (param_2 != 0) {
    FUN_00411a78();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void rgb_to_hsv(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void rgb_to_hls(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void restorecontext(void)

{
  FUN_0042a4d4(DAT_10016e00,1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void index_to_dir(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setOverlayWindow(void)

{
  GLXwinset(display,*(undefined4 *)(curcontextwindows + 4));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void swapcontext(undefined1 param_1)

{
  FUN_0042a4d4(1 - curcontextid,param_1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void hls_to_rgb(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cIconDraw(int param_1)

{
  (**(code **)(*(int *)(param_1 + 0x60) + 0xc))(*(short *)(*(int *)(param_1 + 0x60) + 8) + param_1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void build_path_string(undefined1 *param_1,int param_2)

{
  int unaff_gp;
  
  if (param_1 == (undefined1 *)0x0) {
    param_1 = (undefined1 *)(*(int *)(unaff_gp + -0x7f94) + 0x6710);
  }
  *param_1 = 0;
  if (param_2 != 0) {
    (*(code *)(*(int *)(unaff_gp + -0x7fe8) + 0x1a78))();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void age(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void quit_application(void)

{
  cleanup_before_exit();
                    // WARNING: Subroutine does not return
  exit(0);
}

void setOverviewOverlayWindow(void)

{
  GLXwinset(display,DAT_10016c04);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void getnum__FiT1PvT1(int param_1,__off_t param_2,void *param_3,size_t param_4)

{
  lseek(param_1,param_2,0);
  read(param_1,param_3,param_4);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void copycontext(void)

{
  pointer_____offset_0x10017720___ puVar1;
  pointer_____offset_0x10018374___ puVar2;
  pointer_____offset_0x10017720___ puVar3;
  pointer_____offset_0x10017720___ puVar4;
  
  puVar1 = curcontext + 0xc54;
  puVar2 = altcontext;
  puVar3 = curcontext;
  do {
    puVar4 = puVar3 + 0xc;
    *(undefined4 *)puVar2 = *(undefined4 *)puVar3;
    *(undefined4 *)(puVar2 + 4) = *(undefined4 *)(puVar3 + 4);
    *(undefined4 *)(puVar2 + 8) = *(undefined4 *)(puVar3 + 8);
    puVar2 = puVar2 + 0xc;
    puVar3 = puVar4;
  } while (puVar4 != puVar1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void getTypeName__8RuleInfoFv(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void getlong__FPc(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void getcolorsys(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void typeName__13ByteCodedIconFv(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void do_perspective(void)

{
  perspective((int)*(short *)(curcontext + 0x10),0x3f800000,0x3d4ccccd,0x43fa0000);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cFindIconByType(undefined4 param_1)

{
  FUN_004349f8(&context_data_block,param_1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMClose(int param_1)

{
  __dl__FPv(*(undefined4 *)(param_1 + 4));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cIconGetValue(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void equalPositions(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cSetColors(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  setColors__13ByteCodedIconFiN21(param_1,param_2,param_3,param_4);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cIconInit(undefined4 param_1)

{
  FUN_00434324(&context_data_block,param_1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void compare_files(undefined4 *param_1,undefined4 *param_2)

{
  strcmp(*(char **)*param_1,*(char **)*param_2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void bitpat__Ff(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setOverviewWindow(void)

{
  GLXwinset(display,DAT_10016c00);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void getshort__FPc(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void doneFam(void)

{
  FUN_00417b88();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMOpen(undefined4 param_1)

{
  FUN_00439a98(param_1,0);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
