/**
 * __sti__1251b_3102d580
 *
 * Extracted from fsn.c lines 73665-73671
 * Category: Other
 */

void __sti__1251b_3102d580(void)

{
  FUN_00435748(&TheFileIconInterpreter);
                    // WARNING: Bad instruction - Truncating control flow here
      /*
     * BADDATA ANALYSIS (from binary @ 0x004356d0):
     * Function: __sti__1251b_3102d580
     *
     * ## Analysis
     * **1. What it does:**
     * Static initializer function (C++ constructor notation `__sti__`). Sets up GP, loads a function pointer from GOT offset -30572 and a data pointer from GOT offset -30228, then calls the function with that data as argument.
     * **2. C pseudocode:**
     * ```c
     * // Static initializer at 0x004356d0
     * // Called automatically at program startup
     * void __sti__1251b_3102d580(void) {
     * void (*init_func)(void*) = *(void**)((char*)_gp - 30572);  // GOT[-30572]
     * void *data = *(void**)((char*)_gp - 30228);                 // GOT[-30228]
     * init_func(data);
     * }
     * ```
     * **Note:** The `__sti__` prefix indicates this is a static initializer generated by the SGI MIPSpro C++ compiler. The hex suffix `1251b_3102d580` encodes the source file and line info. This function is placed in `.init` or called via `.ctors` to initialize a global object before `main()` runs. The actual initialization work is done by whatever function is at GOT offset -30572 (likely a constructor or registration function).
     */
halt_baddata();
}
