/**
 * get_panel_value
 *
 * Extracted from fsn.c lines 37952-38115
 * Category: UI
 */

void get_panel_value(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 local_78;
  undefined4 local_74;
  undefined4 local_70;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_c;
  undefined4 local_8;
  undefined4 local_4;
  
  local_78 = 0;
  local_4 = XmCreateMenuBar(param_1,"menuBar",&local_74,0);
  XtManageChild(local_4);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_c = XmCreatePulldownMenu(local_4,"session_pane",&local_74,local_78);
  XtAddCallback(local_c,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(local_c,0xe3f4c38,overlayMenuUnmappedCB,0);
  install_help_callback(local_c,&sessionHelp);
  local_78 = 0;
  autoscan_split_toggle = XmCreateToggleButton(local_c,"menuSplit",&local_74,0);
  XtManageChild(autoscan_split_toggle);
  XtAddCallback(autoscan_split_toggle,0xe3f4ca5,autoscan_toggle_callback,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_c,"menuRescan",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,rescanDatabase,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_c,"menuSave",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,dumpDatabaseCB,0);
  configure_context_widget(local_c);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_c,"menuQuit",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,quit_application,0);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_c;
  local_8 = XmCreateCascadeButton(local_4,"menuSession",&local_74,1);
  XtManageChild(local_8);
  install_help_callback(local_8,&sessionHelp);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_14 = XmCreatePulldownMenu(local_4,"show_pane",&local_74,local_78);
  XtAddCallback(local_14,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(local_14,0xe3f4c38,overlayMenuUnmappedCB,0);
  XtManageChild(local_14);
  install_help_callback(local_14,&showHelp);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuOverview",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,showOverview,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuControls",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,show_controls,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuLegend",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,toggle_legend,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuPreferences",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,showPreferencePanel,0);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_18 = XmCreatePulldownMenu(local_14,"hide_pane",&local_74,local_78);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuOverview",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,hideOverview,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuControls",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,init_panel_layout,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuLegend",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,controls_button_callback,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuPreferences",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,hidePreferencePanel,0);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_18;
  uVar1 = XmCreateCascadeButton(local_14,"menuHide",&local_74,1);
  XtManageChild(uVar1);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_14;
  local_8 = XmCreateCascadeButton(local_4,"menuShow",&local_74,1);
  XtManageChild(local_8);
  install_help_callback(local_8,&showHelp);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_10 = XmCreatePulldownMenu(local_4,"display_pane",&local_74,local_78);
  XtAddCallback(local_10,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(local_10,0xe3f4c38,overlayMenuUnmappedCB,0);
  XtManageChild(local_10);
  install_help_callback(local_10,&displayHelp);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_10;
  local_8 = XmCreateCascadeButton(local_4,"menuDisplay",&local_74,1);
  XtManageChild(local_8);
  install_help_callback(local_8,&displayHelp);
  local_70 = 1;
  local_74 = 0xe3f464e;
  local_78 = 1;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_70 = XmCreatePulldownMenu(local_10,"dheight_pane",&local_74,local_78);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_1c = local_70;
  uVar1 = XmCreateCascadeButton(local_10,"menuHeight",&local_74,1);
  XtManageChild(uVar1);
  local_78 = 0;
  file_height_none_toggle = XmCreateToggleButton(local_1c,"menuHeightNone",&local_74,0);
  XtManageChild(file_height_none_toggle);
  XtAddCallback(file_height_none_toggle,0xe3f4ca5,file_height_mode_callback,0);
  local_78 = 0;
  file_height_linear_toggle = XmCreateToggleButton(local_1c,"menuHeightLinear",&local_74,0);
  XtManageChild(file_height_linear_toggle);
  XtAddCallback(file_height_linear_toggle,0xe3f4ca5,file_height_mode_callback,1);
  local_78 = 0;
  file_height_exag_toggle = XmCreateToggleButton(local_1c,"menuHeightExaggerated",&local_74,0);
  XtManageChild(file_height_exag_toggle);
  XtAddCallback(file_height_exag_toggle,0xe3f4ca5,file_height_mode_callback,2);
  local_74 = 0xe3f464e;
  local_78 = 1;
  local_70 = 1;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_70 = XmCreatePulldownMenu(local_10,"ddir_pane",&local_74,local_78);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_20 = local_70;
  dir_height_menu_button = XmCreateCascadeButton(local_10,"menuDirectoryHeight",&local_74,1);
  XtManageChild(dir_height_menu_button);
  local_78 = 0;
  dir_flat_toggle = XmCreateToggleButton(local_20,"menuDirectoryFlat",&local_74,0);
  XtManageChild(dir_flat_toggle);
  XtAddCallback(dir_flat_toggle,0xe3f4ca5,dir_height_mode_callback,0);
  local_78 = 0;
  dir_files_only_toggle = XmCreateToggleButton(local_20,"menuDirectoryFilesOnly",&local_74,0);
  XtManageChild(dir_files_only_toggle);
  XtAddCallback(dir_files_only_toggle,0xe3f4ca5,dir_height_mode_callback,1);
  local_78 = 0;
  dir_children_toggle = XmCreateToggleButton(local_20,"menuDirectoryChildren",&local_74,0);
  XtManageChild(dir_children_toggle);
  XtAddCallback(dir_children_toggle,0xe3f4ca5,dir_height_mode_callback,2);
  init_context_menus(local_4,param_1);
  finalize_menu_setup(local_4);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
