// filesystem.h - Header for filesystem module
// Generated by extract_module.py

#ifndef FSN_FILESYSTEM_H
#define FSN_FILESYSTEM_H

#include "fsn_types.h"
#include "fsn_std.h"

void dirfamUnmonitor(void);
void fileStoppedExecuting(undefined4 param_1);
void dumpDatabaseCB(void);
void dirfamInit(void);
void warpZoomToFile(int param_1,int param_2);
void buildingDatabaseMessage(void);
void check_unmonitor_dp(int param_1);
void load_db(void);
void dirfamUnmonitorDir(int param_1);
void FAMResumeMonitor(undefined4 *param_1,undefined4 *param_2);
void finddir(int param_1,undefined4 param_2);
void FAMPending(uint *param_1);
void readingDatabaseMessage(void);
void fileerror(char *param_1,char *param_2);
void FAMCancelMonitor(undefined4 *param_1,undefined4 *param_2);
void updateDir(int param_1);
void filemessage(char *param_1,char *param_2,undefined4 param_3);
void dirfamDone(void);
void FAMSuspendMonitor(undefined4 *param_1,undefined4 *param_2);
void findfile(int param_1,undefined4 param_2);
void savePositions(void);
void dirfamMonitorDir(int param_1);
void gotoFileName(undefined4 param_1);
void scheduleDatabaseDumpTimeout(void);
void fileExecuting(int param_1);
void databaseDumpTimeout(void);
void FAMNextEvent(uint *param_1,undefined4 param_2);
void FAMMonitorDirectory(undefined4 param_1,char *param_2,int *param_3,undefined4 param_4);
void dirfamMonitor(void);
void FAMMonitorFile(undefined4 param_1,char *param_2,int *param_3,undefined4 param_4);

#endif // FSN_FILESYSTEM_H
