/**
 * fsn_forward.h - Forward declarations for all FSN functions
 *
 * Auto-generated by generate_forward_decls.py using tree-sitter
 */

#ifndef FSN_FORWARD_H
#define FSN_FORWARD_H

/* Note: This file should be included after fsn_types.h */
/* Types used: undefined, undefined1, undefined2, undefined4, uint, etc. */

/* DoClientIn_* functions */
void DoClientIn__6ClientFP11ServerEntry(undefined4 param_1,int *param_2);

/* FindIconByName_* functions */
void FindIconByName__14ByteCodeLoaderFPc(int *param_1);

/* FindIconByType_* functions */
void FindIconByType__14ByteCodeLoaderFPc(int *param_1,char *param_2);

/* FindInfoByName_* functions */
void FindInfoByName__14ByteCodeLoaderFPc(int *param_1);

/* FindInfoByType_* functions */
void FindInfoByType__14ByteCodeLoaderFPc(int *param_1,char *param_2);

/* LoadFileTypingRules_* functions */
void LoadFileTypingRules__14ByteCodeLoaderFPc(int *param_1,char *param_2);

/* ReadFromServer_* functions */
void ReadFromServer__6ClientFiPcT1(int *param_1,int param_2,undefined1 *param_3,int param_4);

/* SG_* functions */
void SG_defaultDepthAndTypeResources (int param_1,int param_2,uint *param_3,byte *param_4,uint *param_5,uint *param_6, int *param_7,int *param_8,int *param_9);
void SG_getDefaultColormap(int param_1,int param_2,int param_3);
void SG_getDefaultDepth(int param_1,undefined4 param_2,int *param_3,int param_4);
void SG_getMatchingVisual(int param_1,int param_2,int param_3,int *param_4,int param_5,int param_6);
void SG_getMaxDepth(int param_1,int param_2,int *param_3,int param_4);
void SG_getNormalArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void SG_getOverlay2Args(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void SG_getOverlay4Args(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void SG_getOverlayArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void SG_getPopupArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void SG_getUnderlayArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void SG_getVisualArgs(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,int param_6,int *param_7);

/* SetFile_* functions */
void SetFile__19FileIconInterpreterFPc(int param_1,char *param_2);

/* UnSetFile_* functions */
void UnSetFile__19FileIconInterpreterFv(int param_1);

/* WriteToServer_* functions */
void WriteToServer__6ClientFiPcT1(undefined4 param_1,int param_2,void *param_3,size_t param_4);

/* add_* functions */
void add_directory_monitor(int param_1);

/* allocate_* functions */
void allocate_directory_entry(void);

/* apply_* functions */
void apply_context_changes(undefined8 param_1,undefined8 param_2,undefined4 *param_3,char param_4);
void apply_label_color(uint param_1,undefined4 *param_2,int param_3,undefined4 param_4);
void apply_pending_updates(void);

/* begin_* functions */
void begin_overview_render(void);
void begin_rendering(void);

/* build_* functions */
void build_path_string(char *param_1,undefined4 *param_2);

/* calc_* functions */
void calc_h_angle(void);
void calc_v_angle(void);

/* calculate_* functions */
void calculate_file_view(int param_1);
void calculate_item_params(float *param_1,float *param_2,float *param_3,undefined2 *param_4, undefined2 *param_5,int *param_6,undefined1 *param_7,undefined1 *param_8);
void calculate_layout_position(int param_1);
void calculate_tree_layout(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void calculate_view_params(float *param_1,float *param_2,float *param_3,undefined2 *param_4, undefined2 *param_5,undefined4 *param_6,undefined1 *param_7,undefined1 *param_8);

/* check_* functions */
void check_directory_flags(undefined4 *param_1,char *param_2,char *param_3,char param_4);
void check_gl_ready(void);
void check_unmonitor_dp(int param_1);
void check_visibility(void);

/* cleanup_* functions */
void cleanup_directory(int param_1);

/* clear_* functions */
void clear_current_selection(void);
void clear_marked_state(void);
void clear_selection(void);
void clear_selection_state(void);

/* close_* functions */
void close_connections(int *param_1,int param_2);
void close_file_handle(int param_1);

/* cmy_* functions */
void cmy_to_rgb(double param_1,double param_2);

/* compare_* functions */
void compare_dirs(undefined4 *param_1,undefined4 *param_2);
void compare_files(undefined4 *param_1,undefined4 *param_2);

/* configure_* functions */
void configure_context_widget(undefined4 param_1);
void configure_viewport(int param_1,undefined4 *param_2,int param_3);

/* connect_* functions */
void connect_network(int *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);

/* copy_* functions */
void copy_buffer_data(int param_1,undefined4 *param_2);
void copy_file_item(undefined4 param_1,undefined4 *param_2);
void copy_selection_data(undefined2 *param_1,undefined4 param_2);

/* count_* functions */
void count_directory_items(void);

/* create_* functions */
void create_color_legend_box(uint param_1,int param_2);
void create_context_widget(undefined4 param_1,int *param_2,undefined4 param_3);
void create_directory_entry(void);
void create_gl_window(int param_1);
void create_panel_component(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void create_root_directory(char *param_1);
void create_socket(undefined4 *param_1);

/* destroy_* functions */
void destroy_gl_resources(int param_1);

/* display_* functions */
void display_scan_status(undefined4 param_1,char *param_2,undefined4 param_3);
void display_status_message(char *param_1);

/* do_* functions */
void do_warp(int param_1);

/* draw_* functions */
void draw__13ByteCodedIconFv(undefined1 *param_1);
void draw_alt(void);
void draw_box(undefined4 *param_1,int param_2,uint param_3);
void draw_dir(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, char param_5);
void draw_directories(char param_1);
void draw_directory(ulonglong param_1,int param_2,char param_3);
void draw_directory_recursive(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void draw_directory_tree(int param_1);
void draw_entry(int param_1,undefined4 param_2);
void draw_file(int param_1,undefined4 *param_2,char param_3,char param_4,undefined4 param_5, undefined4 param_6);
void draw_file_icon(byte *param_1);
void draw_file_item(int param_1,char param_2,uint param_3);
void draw_file_pointers(int param_1,int param_2,int param_3);
void draw_files(int param_1,char param_2,uint param_3);
void draw_item_recursive(undefined8 param_1,undefined8 param_2,int param_3);
void draw_legend_color_box(undefined4 *param_1,int param_2,uint param_3);
void draw_mark_overlay(void);
void draw_overview_content(void);
void draw_positioned_item(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void draw_scaled_element(double param_1,double param_2);
void draw_scene(void);
void draw_second_pick(undefined8 param_1,undefined8 param_2,int param_3);
void draw_special(undefined4 *param_1,char *param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void draw_visibility(void);
void draw_visible_directory(int param_1);
void draw_warp(void);
void draw_warp_directory(undefined8 param_1,undefined8 param_2,undefined4 *param_3,char param_4);

/* dump_* functions */
void dump_database_file(int *param_1);
void dump_directory_tree(FILE *param_1,undefined4 *param_2,int param_3);

/* end_* functions */
void end_rendering(void);

/* eval_* functions */
void eval_bytecode_instruction(int param_1,int param_2,int param_3);
void eval_icon_script(undefined4 param_1);

/* expand_* functions */
void expand_path(undefined4 param_1);

/* extract_* functions */
void extract_position_data(undefined2 *param_1,undefined2 *param_2,undefined2 *param_3,float *param_4, float *param_5,float *param_6,int *param_7,int *param_8,int *param_9, undefined1 *param_10);

/* fam_* functions */
void fam_cancel_monitor_wrapper(undefined4 *param_1,undefined4 *param_2);
void fam_monitor_request(undefined4 *param_1,undefined4 param_2,undefined4 *param_3,undefined4 param_4, undefined4 param_5);
void fam_open_wrapper(undefined4 param_1);

/* finalize_* functions */
void finalize_draw_frame(void);
void finalize_interpreter(int param_1);
void finalize_menu_setup(undefined4 param_1);
void finalize_update(void);

/* find_* functions */
void find_directory_by_path(int param_1,undefined4 param_2);
void find_string_index(int param_1);

/* findzoom_* functions */
void findzoom_landscape(float *param_1,float *param_2,float *param_3,undefined2 *param_4, undefined2 *param_5,undefined4 *param_6,undefined1 *param_7, undefined1 *param_8);
void findzoom_warp(float *param_1,float *param_2,float *param_3,undefined2 *param_4, undefined2 *param_5,int *param_6,undefined1 *param_7,undefined1 *param_8);

/* flush_* functions */
void flush_rendering(int param_1);

/* format_* functions */
void format_data_output(int param_1,int param_2,int param_3,int param_4,int *param_5);
void format_log_message(undefined4 param_1,char *param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);

/* free_* functions */
void free_child_nodes(int param_1);

/* fsn_* functions */
int fsn_fam_init(void);
int fsn_fam_monitor_directory(const char *path, void *userdata);
int fsn_fam_process_events(void);
void fsn_fam_shutdown(void);
int fsn_fam_unmonitor(int reqnum);

/* get_* functions */
void get_bytecode_context(int param_1,int param_2);
void get_cursor_state(int *param_1,undefined4 *param_2,undefined4 *param_3);
void get_directory_info(uint param_1,undefined4 param_2);
void get_file_status(void);
void get_icon_attribute(void);
void get_icon_bounds(int param_1,undefined4 *param_2,undefined4 *param_3,undefined4 *param_4, undefined4 *param_5);
void get_icon_result(undefined4 *param_1);
void get_icon_string(void);
void get_item_by_index(void);
void get_item_screen_coords(undefined4 *param_1);
void get_panel_value(undefined4 param_1);
void get_path_entry(int param_1);
void get_position_coords(int param_1,int *param_2,undefined4 *param_3);
void get_selection_params(int *param_1,undefined4 *param_2,undefined4 *param_3);
void get_selection_string(void);
void get_view_extents(int param_1,float *param_2,float *param_3);
void get_view_position(undefined2 *param_1);
void get_warp_entry(int param_1,float *param_2,float *param_3);
void get_window_entry(undefined4 param_1);
void get_window_properties(undefined4 param_1,int *param_2,undefined4 param_3);

/* getTypeName_* functions */
void getTypeName__8RuleInfoFv(void);

/* getValue_* functions */
void getValue__8RuleInfoFi(void);

/* gl_* functions */
void gl_get_dimensions_wrapper(void);
void gl_picking_setup_wrapper(void);
void gl_pop_state(void);
void gl_push_state(void);
void gl_swap_buffers(undefined1 param_1);

/* glx_* functions */
void glx_reset_context_wrapper(void);
void glx_swap_buffers_wrapper(void);
void glx_switch_context_wrapper(void);

/* handle_* functions */
void handle_item_action(int param_1,undefined4 param_2);

/* hash_* functions */
void hash_filename(char *param_1);

/* hls_* functions */
void hls_to_rgb(void);

/* hsb_* functions */
void hsb_to_rgb(undefined4 param_1,undefined4 param_2);

/* hsv_* functions */
void hsv_to_rgb(double param_1, double param_2);

/* icon_* functions */
void icon_bytecode_eval_wrapper(undefined4 *param_1);

/* index_* functions */
void index_to_dir(void);

/* init_* functions */
void init_app_state(void);
void init_camera_state(void);
void init_color_menus(void);
void init_context_menus(undefined4 param_1,undefined4 param_2);
void init_context_windows(void);
void init_database_display(void);
void init_database_node(int param_1);
void init_database_state(void);
void init_directory_layout(int param_1);
void init_directory_state(void);
void init_display_lists(void);
void init_display_mode(void);
void init_display_state(void);
void init_gl_lists(void);
void init_gl_state(int param_1,undefined4 param_2);
void init_icon_context(void);
void init_icon_resources(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void init_mark_panel(undefined4 param_1);
void init_network_state(void);
void init_panel_layout(void);
void init_render_state(void);
void init_rendering(void);
void init_search_panel(undefined4 param_1);
void init_toplevel_resources(undefined4 param_1);
void init_view_transform(void);

/* install_* functions */
void install_help_callback(undefined4 param_1,undefined4 param_2);

/* isSuperByInfo_* functions */
void isSuperByInfo__14ByteCodeLoaderFPcP8RuleInfo(undefined4 param_1,char *param_2,int param_3);

/* isSuperByName_* functions */
void isSuperByName__14ByteCodeLoaderFPcT1(undefined4 param_1,char *param_2,undefined4 param_3);

/* isSuperByType_* functions */
void isSuperByType__14ByteCodeLoaderFPcT1(undefined4 param_1,char *param_2,undefined4 param_3);

/* layout_* functions */
void layout_db(undefined4 param_1,undefined4 param_2);
void layout_tree_recursive(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);

/* load_* functions */
void load_filetype_rules_wrapper(undefined4 param_1);

/* lookup_* functions */
void lookup_buffer_index(int param_1);
void lookup_context_item(uint param_1);

/* mark_* functions */
void mark_directory_item(int param_1);
void mark_items_recursive(int param_1);

/* misc_* functions */
void CreateSelectionEntries(undefined4 param_1);
void CreateSelectionMenus(undefined4 param_1,undefined4 param_2);
void FAMCancelMonitor(undefined4 *param_1,undefined4 *param_2);
void FAMClose(int param_1);
void FAMDebugLevel(undefined4 *param_1,int param_2);
void FAMMonitorCollection (undefined4 *param_1,char *param_2,int *param_3,int param_4,undefined4 param_5, undefined4 param_6);
void FAMMonitorDirectory(undefined4 param_1,char *param_2,int *param_3,undefined4 param_4);
void FAMMonitorDirectory2(void);
void FAMMonitorFile(undefined4 param_1,char *param_2,int *param_3,undefined4 param_4);
void FAMMonitorFile2(void);
void FAMNextEvent(uint *param_1,undefined4 param_2);
void FAMOpen(undefined4 param_1);
void FAMOpen2(int *param_1,int param_2);
void FAMPending(uint *param_1);
void FAMResumeMonitor(undefined4 *param_1,undefined4 *param_2);
void FAMSuspendMonitor(undefined4 *param_1,undefined4 *param_2);
void LoadIntlResources(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void RGBcolor(short r, short g, short b);
void __ct__11ConvertInfoFv(undefined4 *param_1);
void __ct__13ByteCodedIconFP8RuleInfo(undefined1 *param_1,int param_2);
void __ct__14ByteCodeLoaderFv(undefined4 *param_1);
void __ct__19FileIconInterpreterFv(int param_1);
void __ct__6ClientFv(undefined4 *param_1);
void __ct__8RuleInfoFv(undefined4 *param_1);
void __dt__13ByteCodedIconFv(int param_1,uint param_2);
void __dt__14ByteCodeLoaderFv(int *param_1,uint param_2);
void __dt__19FileIconInterpreterFv(int param_1,uint param_2);
void activeWorkProc(void);
void addMark(char *param_1,undefined4 *param_2);
void allocOverlayColor(undefined4 param_1,undefined4 param_2);
void baseLocateHighlight(int param_1,undefined4 *param_2,int param_3);
void bgnclosedline(void);
void bgnline(void);
void bgnpoint(void);
void bgnpolygon(void);
void bgnqstrip(void);
void bgntmesh(void);
void bsearch2(undefined4 param_1,uint param_2,int param_3,int param_4,undefined4 param_5, uint *param_6);
void buildingDatabaseMessage(void);
void c3f(float c[3]);
void c4f(float c[4]);
void cFindIconByName(undefined4 param_1);
void cFindIconByType(undefined4 param_1);
void cGetBounds(int param_1,undefined4 *param_2,undefined4 *param_3,undefined4 *param_4, undefined4 *param_5);
void cIconDraw(int param_1);
void cIconGetValue(void);
void cIconInit(undefined4 param_1);
void cIconToTypeName(void);
void cSetState(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void charstr(String str);
void checkPointerFile(int param_1,undefined4 param_2);
void checkRedrawScene(void);
void checkValidSelections(void);
void clear(void);
void cmov2s(Scoord x, Scoord y);
void copycontext(void);
void cpack(uint32_t color);
void createCopyright(undefined4 param_1,int param_2,int param_3);
void createHelpMenu(undefined4 param_1);
void createMarkControls(undefined4 param_1);
void createOverview(void);
void createSearch(undefined4 param_1);
void createSelectedInfo(undefined4 param_1,undefined4 *param_2,undefined4 param_3);
void czclear(uint32_t cval, int32_t zval);
void databaseDumpTimeout(void);
void defpattern(short index, short size, unsigned short *pattern);
void deleteCmapWindow(int param_1);
void deleteMessage(undefined4 *param_1);
void deleteTopWindow(int param_1);
void destroyCopyright(void);
void dirToPath(undefined1 *param_1,int param_2);
void dirfamDone(void);
void dirfamInit(void);
void dirfamMonitor(void);
void dirfamMonitorDir(int param_1);
void dirfamUnmonitor(void);
void dirfamUnmonitorDir(int param_1);
void displayHourglass(undefined4 param_1);
void doneFam(void);
void drawOverview(void);
void drawOverviewDirectory(int param_1,char param_2);
void drawOverviewOverlay(void);
void drawOverviewOverlayCursor(void);
void dumpDatabaseCB(void);
void dumpMarks(FILE *param_1);
void editCB(void);
void endclosedline(void);
void endline(void);
int32_t endpick(short *buffer);
void endpoint(void);
void endpolygon(void);
void endqstrip(void);
int32_t endselect(short *buffer);
void endtmesh(void);
void equalPositions(void);
void fileChanged(int param_1,char *param_2);
void fileCreated(int param_1,char *param_2);
void fileDeleted(int param_1,char *param_2);
void fileExecuting(int param_1);
void fileStoppedExecuting(undefined4 param_1);
void fileerror(char *param_1,char *param_2);
void filemessage(char *param_1,char *param_2,undefined4 param_3);
void findDirByFullName(char *param_1);
void findbestfile(char *param_1,int *param_2,undefined4 *param_3);
void finddir(int param_1,undefined4 param_2);
void findfile(int param_1,undefined4 param_2);
void findzoom(void);
void fromrgb(undefined4 param_1,undefined4 param_2);
void getPosition(undefined2 *param_1,undefined2 *param_2,undefined2 *param_3,float *param_4, float *param_5,float *param_6,int *param_7,int *param_8,int *param_9, undefined1 *param_10);
void getcolorsys(void);
int32_t getgdesc(int32_t inquiry);
void gflush(void);
void glcompat(int32_t mode, int32_t value);
void gotoFileName(undefined4 param_1);
int32_t gselect(short *buffer, int32_t bufsize);
void handleEvents(void);
void hideOverview(void);
void hidePreferencePanel(void);
void highlightByName(undefined4 param_1);
void highlightDir(void);
void highlightDirLandscape(int param_1);
void highlightDirWarp(undefined8 param_1,undefined8 param_2,int param_3);
void highlightFile(void);
void highlightFileLandscape(int param_1,int param_2);
void highlightFileWarp(int param_1,int param_2);
void highlightOverviewDir(int param_1);
void highlightSpecialDir(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4 );
void initResources(undefined4 param_1);
void initnames(void);
void landscapeZoomToFile(int param_1,int param_2);
void linesmooth(uint32_t mode);
void linewidth(short width);
void loadname(short name);
void locateClear(void);
void locateClearAction(undefined4 param_1,int param_2);
void locateHighlight(void);
void locateHighlightAction(undefined4 param_1,int param_2);
void main(int param_1,undefined4 *param_2);
void markAllVisible(int param_1);
void message(undefined4 param_1,int param_2);
void movehoriz(undefined8 param_1,undefined4 param_2);
void myContext(undefined4 param_1,undefined4 param_2);
void newCmapWindow(undefined4 param_1);
void newOverlayColormap(undefined4 param_1);
void newTopWindow(undefined4 param_1);
void newcontext(uint param_1,char param_2);
void overlayMenuMappedCB(void);
void overlayMenuUnmappedCB(void);
void overviewLocateHighlight(void);
void overviewPickPointer(void);
void pick(short *buffer, int32_t bufsize);
void pickLandscape(int *param_1,undefined4 *param_2,undefined4 *param_3);
void pickPointer(void);
void pickWarp(int *param_1,undefined4 *param_2,undefined4 *param_3);
void picksize(short deltax, short deltay);
void popmatrix(void);
void popname(void);
void popzoom(void);
void postMenu(undefined4 param_1,undefined4 param_2,int param_3);
void pruneSubTree(int param_1);
void pruneTree(int param_1);
void pushmatrix(void);
void pushname(short name);
void pushzoom(void);
void readMark(FILE *param_1);
void readPosition(undefined2 *param_1,FILE *param_2);
void readingDatabaseMessage(void);
void redrawSelectionNames(void);
void rescaleOverview(void);
void rescanDatabase(void);
void restorePosition(undefined4 param_1);
void restorePositions(void);
void restorecontext(void);
void rgbcomplement(undefined4 param_1,undefined4 param_2);
void savePosition(undefined2 *param_1);
void savePositions(void);
void savecontext(void);
void scanDatabase(int param_1);
void scheduleDatabaseDumpTimeout(void);
void setMainWindow(void);
void setMoveAndCopyButtons(void);
void setOverlayWindow(void);
void setOverviewOverlayWindow(void);
void setOverviewWindow(void);
void setcolorsys(int param_1);
void setcontext(int param_1,undefined1 param_2);
void setpattern(short index);
void shademodel(int32_t mode);
void showOverview(void);
void showPreferencePanel(void);
void shrinkDueToZoom(void);
void subpixel(Boolean enable);
void swapbuffers(void);
void swapcontext(undefined1 param_1);
void torgb(undefined4 param_1,undefined4 param_2);
void undisplayHourglass(void);
void unpruneTree(int param_1);
void updateDir(int param_1);
void v2f(float v[2]);
void v2i(int32_t v[2]);
void v2s(short v[2]);
void v3f(float v[3]);
void v3i(int32_t v[3]);
void v3s(short v[3]);
void v4f(float v[4]);
void viewFile(undefined4 param_1,undefined4 *param_2);
void viewport(void);
void warpZoomToFile(int param_1,int param_2);
void widgetHelp(undefined4 param_1,undefined4 param_2);
void writePosition(undefined2 *param_1,FILE *param_2);
void zbuffer(Boolean enable);
void zclear(void);
void zoomPosition(undefined4 param_1);
void zoomToSelection(void);
void zoomto(double param_1,double param_2);
void zwritemask(uint32_t mask);

/* parse_* functions */
void parse_command_args(int param_1,undefined4 *param_2);
void parse_data_buffer(int param_1,undefined4 param_2,int *param_3,int param_4);

/* pick_* functions */
void pick_file_item(int param_1,undefined4 *param_2,undefined4 param_3,char param_4,undefined4 param_5 ,undefined4 param_6);

/* post_* functions */
void post_realize_setup(undefined4 param_1);

/* prepare_* functions */
void prepare_draw_frame(void);

/* process_* functions */
void process_child_directory(int param_1);
void process_child_recursive(undefined4 *param_1);
void process_data_recursive(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void process_data_section(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void process_directory_data(int param_1);
void process_file_data(int param_1,undefined4 param_2);
void process_path_buffer(undefined4 param_1,char *param_2,int param_3);
void process_pending_events(void);
void process_pick_item(int param_1);
void process_search_results(void);
void process_tree_node(ulonglong param_1,int param_2,char param_3);

/* quit_* functions */
void quit_application(void);

/* read_* functions */
void read_bytecode_value(int param_1,int param_2,int param_3,int *param_4,int param_5);
void read_context_value(int *param_1,undefined4 param_2);
void read_data_section(int param_1,int param_2,int *param_3,int param_4);
void read_file_buffer(int *param_1,int param_2,undefined1 *param_3,int param_4);

/* recalc_* functions */
void recalc_layout(void);

/* redraw_* functions */
void redraw_gl_scene(void);

/* refresh_* functions */
void refresh_after_change(void);
void refresh_context_view(int param_1,int param_2);
void refresh_directory(void *param);
void refresh_directory_view(int param_1);
void refresh_display(void);
void refresh_fam_state(void);
void refresh_legend_colors(void);
void refresh_list_display(void);
void refresh_toplevel(void);
void refresh_view(void);
void refresh_view_recursive(void);

/* render_* functions */
void render_directory(int param_1);
void render_file_icon(int param_1,undefined4 *param_2,char param_3,char param_4,undefined4 param_5, undefined4 param_6);
void render_item_recursive(undefined4 *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, char param_5);
void render_overview_frame(void);
void render_tree_level(undefined8 param_1,undefined8 param_2,int param_3);

/* reset_* functions */
void reset_display_state(void);
void reset_eye(void);
void reset_icon_interpreter(int param_1,int param_2);
void reset_list_state(void);
void reset_view_state(void);

/* restore_* functions */
void restore_state(void);

/* rgb_* functions */
void rgb_to_cmy(double param_1,double param_2);
void rgb_to_hls(void);
void rgb_to_hsb(undefined4 param_1,undefined4 param_2);
void rgb_to_hsv(double param_1, double param_2);
void rgb_to_irgb(double param_1,double param_2);
void rgb_to_rgb(double param_1,double param_2);
void rgb_to_yiq(double param_1,double param_2);

/* run_* functions */
void run__19FileIconInterpreterFPcPvT1(float *param_1,char *param_2,int param_3,int param_4);
void run_icon_interpreter(float *param_1,char *param_2,int param_3,int param_4);

/* save_* functions */
void save_matrix_state(void);
void save_state(void);

/* scale_* functions */
void scale__13ByteCodedIconFf(int param_1,float param_2);

/* search_* functions */
void search_file_entry(undefined4 param_1,undefined4 *param_2);

/* select_* functions */
void select_directory(int param_1);
void select_file(undefined4 *param_1);

/* set_* functions */
void set_camera_lookat(double param_1,double param_2);
void set_context_state(uint param_1,char param_2);
void set_draw_mode(char param_1);
void set_gl_color(uint param_1);
void set_gl_context(int param_1,undefined1 param_2);
void set_icon_flags(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5,undefined4 param_6);
void set_interpreter_mode(int param_1,uint param_2);
void set_items_flag(int param_1,char param_2);
void set_main_gl_window(void);
void set_render_flag(char param_1);
void set_status_message(undefined4 param_1,int param_2);
void set_status_text(void);
void set_window_property(undefined4 param_1,int param_2,int param_3);

/* setColors_* functions */
void setColors__13ByteCodedIconFiN21(int param_1,undefined4 param_2,undefined4 param_3);
void setColors__19FileIconInterpreterFiN21(int param_1,int param_2,int param_3);

/* setState_* functions */
void setState__13ByteCodedIconFiN41 (undefined1 *param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4, undefined1 param_5);
void setState__19FileIconInterpreterFiN41 (float *param_1,int param_2,int param_3,int param_4,int param_5);

/* setup_* functions */
void setup_context_widgets(void);
void setup_directory_handler(void);
void setup_event_handlers(void);
void setup_fam_monitoring(void);
void setup_icon_entry(undefined1 *param_1,int param_2);
void setup_item_render(int param_1,char param_2);
void setup_menu_resources(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void setup_rendering(void);
void setup_toplevel_window(undefined4 param_1);
void setup_window_state(undefined4 param_1);

/* show_* functions */
void show_controls(void);
void show_error_dialog(undefined4 param_1,undefined4 param_2);
void show_error_message(undefined4 param_1);

/* sort_* functions */
void sort_entries(undefined4 param_1,uint param_2,int param_3,int param_4,undefined4 param_5, uint *param_6);

/* sync_* functions */
void sync_fam_state(undefined4 param_1);

/* toggle_* functions */
void toggle_legend(void);

/* traverse_* functions */
void traverse_directories(int param_1);

/* typeName_* functions */
void typeName__13ByteCodedIconFv(void);

/* ui_* functions */
void ui_layout_setup_wrapper(void);

/* unmark_* functions */
void unmark_items_recursive(int param_1);

/* unselect_* functions */
void unselect_directory(void);
void unselect_file(void);

/* update_* functions */
void update_child_nodes(int param_1);
void update_colormap_windows(void);
void update_context_bounds(int param_1,int param_2);
void update_context_display(int param_1,int param_2);
void update_database_entry(undefined4 param_1,undefined4 param_2,int *param_3,undefined4 param_4);
void update_database_view(void);
void update_directory_bounds(int param_1);
void update_directory_layout(int param_1);
void update_directory_state(void *param);
void update_display(undefined4 param_1,undefined4 param_2);
void update_fam_display(void);
void update_gl_context(void);
void update_item_state(int param_1);
void update_items_recursive(int param_1,undefined4 param_2);
void update_legend_display(void);
void update_list_state(void);
void update_marked_item(int param_1);
void update_selection(void);
void update_status_display(undefined4 param_1);
void update_tree_bounds(int param_1);
void update_view_recursive(int param_1,int param_2);
void update_widget_state(void);

/* validate_* functions */
void validate_directory(int param_1);
void validate_directory_access(int param_1,undefined4 param_2);

/* write_* functions */
void write_data_buffer(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void write_database_entry(undefined4 param_1);
void write_file_entry(FILE *param_1);
void write_selection_file(undefined2 *param_1,FILE *param_2);

/* yiq_* functions */
void yiq_to_rgb(double param_1,double param_2);

#endif /* FSN_FORWARD_H */
