/**
 * fsn_stubs_generated.h - Auto-generated stub functions
 * Generated by extract_call_signatures.py using tree-sitter
 */

#ifndef FSN_STUBS_GENERATED_H
#define FSN_STUBS_GENERATED_H

#include <X11/Intrinsic.h>  /* Widget */

static inline void apply_context_changes(void * p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline int build_path_string(int p0, void * p1) { (void)p0; (void)p1; return 0; /* TODO */ }
static inline int check_directory_flags(int p0, int p1, int p2, int p3) { (void)p0; (void)p1; (void)p2; (void)p3; return 0; /* TODO */ }
static inline void cleanup_directory(int p0) { (void)p0; /* TODO */ }
static inline void configure_viewport(int p0, int p1, int p2) { (void)p0; (void)p1; (void)p2; /* TODO */ }
static inline void copy_selection_data(int p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline int create_panel_component(Widget p0, void * p1, int p2) { (void)p0; (void)p1; (void)p2; return 0; /* TODO */ }
static inline void display_status_message(int p0) { (void)p0; /* TODO */ }
static inline void do_warp(int p0) { (void)p0; /* TODO */ }
static inline void draw_entry(int p0) { (void)p0; /* TODO */ }
static inline void draw_file_icon(void * p0) { (void)p0; /* TODO */ }
static inline void draw_legend_color_box(int p0, int p1, float p2) { (void)p0; (void)p1; (void)p2; /* TODO */ }
static inline void draw_positioned_item(int p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline void draw_scaled_element(int p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline int equalPositions(int p0, int p1) { (void)p0; (void)p1; return 0; /* TODO */ }
static inline void extract_position_data(int p0, void * p1, void * p2, void * p3, void * p4, void * p5, void * p6, void * p7, void * p8, void * p9) { (void)p0; (void)p1; (void)p2; (void)p3; (void)p4; (void)p5; (void)p6; (void)p7; (void)p8; (void)p9; /* TODO */ }
static inline void flush_rendering(int p0) { (void)p0; /* TODO */ }
static inline int get_bytecode_context(int p0, int p1) { (void)p0; (void)p1; return 0; /* TODO */ }
static inline int get_cursor_state(void * p0, void * p1, void * p2) { (void)p0; (void)p1; (void)p2; return 0; /* TODO */ }
static inline int get_item_by_index(int p0) { (void)p0; return 0; /* TODO */ }
static inline int get_item_screen_coords(int p0) { (void)p0; return 0; /* TODO */ }
static inline int get_panel_value(int p0) { (void)p0; return 0; /* TODO */ }
static inline int get_position_coords(int p0, void * p1, void * p2) { (void)p0; (void)p1; (void)p2; return 0; /* TODO */ }
static inline int get_selection_params(void * p0, void * p1, int p2) { (void)p0; (void)p1; (void)p2; return 0; /* TODO */ }
static inline int get_view_extents(void * p0, void * p1, void * p2, int p3) { (void)p0; (void)p1; (void)p2; (void)p3; return 0; /* TODO */ }
static inline int get_view_position(void * p0) { (void)p0; return 0; /* TODO */ }
static inline int get_window_entry(int p0) { (void)p0; return 0; /* TODO */ }
static inline void gl_get_dimensions_wrapper(void * p0, void * p1, void * p2) { (void)p0; (void)p1; (void)p2; /* TODO */ }
static inline void gl_swap_buffers(int p0) { (void)p0; /* TODO */ }
static inline int init_toplevel_resources(int p0) { (void)p0; return 0; /* TODO */ }
static inline void install_help_callback(void * p0, void * p1) { (void)p0; (void)p1; /* TODO */ }
static inline void load_filetype_rules_wrapper(const char * p0) { (void)p0; /* TODO */ }
static inline int parse_data_buffer(int p0, int p1, void * p2, int p3) { (void)p0; (void)p1; (void)p2; (void)p3; return 0; /* TODO */ }
static inline void post_realize_setup(int p0) { (void)p0; /* TODO */ }
static inline void process_child_directory(void * p0) { (void)p0; /* TODO */ }
static inline void process_data_recursive(int p0, int p1, int p2, int p3) { (void)p0; (void)p1; (void)p2; (void)p3; /* TODO */ }
static inline void process_data_section(int p0, int p1, int p2, int p3) { (void)p0; (void)p1; (void)p2; (void)p3; /* TODO */ }
static inline void process_pick_item(int p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline int read_bytecode_value(int p0, int p1, int p2, void * p3, int p4) { (void)p0; (void)p1; (void)p2; (void)p3; (void)p4; return 0; /* TODO */ }
static inline void recalc_layout(int p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline void refresh_toplevel(int p0) { (void)p0; /* TODO */ }
static inline void refresh_view_recursive(int p0) { (void)p0; /* TODO */ }
static inline void render_file_icon(int p0, int p1, int p2, int p3, int p4, float p5) { (void)p0; (void)p1; (void)p2; (void)p3; (void)p4; (void)p5; /* TODO */ }
static inline void render_tree_level(int p0) { (void)p0; /* TODO */ }
static inline void set_context_state(int p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline void set_gl_context(int p0, int p1) { (void)p0; (void)p1; /* TODO */ }
static inline void set_render_flag(int p0) { (void)p0; /* TODO */ }
static inline int set_status_message(const char * p0, int p1) { (void)p0; (void)p1; return 0; /* TODO */ }
static inline void set_status_text(int p0) { (void)p0; /* TODO */ }
static inline void set_window_property(void * p0, void * p1, int p2) { (void)p0; (void)p1; (void)p2; /* TODO */ }
static inline void setup_menu_resources(Display * p0, int p1, void * p2, void * p3) { (void)p0; (void)p1; (void)p2; (void)p3; /* TODO */ }
static inline void sync_fam_state(void * p0) { (void)p0; /* TODO */ }
static inline void traverse_directories(void * p0) { (void)p0; /* TODO */ }
static inline void update_context_bounds(void * p0, void * p1) { (void)p0; (void)p1; /* TODO */ }
static inline void update_context_display(void * p0, void * p1) { (void)p0; (void)p1; /* TODO */ }
static inline void update_marked_item(int p0) { (void)p0; /* TODO */ }

#endif /* FSN_STUBS_GENERATED_H */
