// graphics_gl.h - Header for graphics_gl module
// Generated by extract_module.py

#ifndef FSN_GRAPHICS_GL_H
#define FSN_GRAPHICS_GL_H

#include "fsn_types.h"
#include "fsn_std.h"
#include <X11/Xlib.h>

void draw_file_pointers(int param_1,int param_2,int param_3);
void rect(void);
void irgb_to_rgb(int param_1,int param_2,undefined4 param_3,float *param_4,float *param_5);
void pushmatrix(void);
void hsb_to_rgb(undefined4 param_1,undefined4 param_2);
void draw_files(int param_1,char param_2,uint param_3);
void rgbStdColor__Fi(uint param_1);
void multmatrix(void);
void allocOverlayColor(undefined4 param_1,undefined4 param_2);
void check_visibility(void);
void getmcolor(void);
void endpoint(void);
void set_gl_color(uint param_1);
void gl_pop_state(void);
void highlightDir(void);
void rgb_to_hsb(undefined4 param_1,undefined4 param_2);
void draw_directories(char param_1);
void draw__13ByteCodedIconFv(undefined1 *param_1);
void bgnline(void);
void drawOverviewOverlay(void);
void rgb_to_rgb(double param_1,double param_2);
void clear(void);
void rgb_to_yiq(double param_1,double param_2);
void locateHighlightAction(undefined4 param_1,int param_2);
void move2(void);
void SG_getOverlay2Args(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void initRGBColors(void);
void setMatrix__13ByteCodedIconFRA4_A4_Cf(int param_1,void *param_2);
void baseLocateHighlight(int param_1,undefined4 *param_2,int param_3);
void overviewPickPointer(void);
void setColors__19FileIconInterpreterFiN21(int param_1,int param_2,int param_3);
void endqstrip(void);
void highlightDirWarp(undefined8 param_1,undefined8 param_2,int param_3);
void drawOverview(void);
void SG_getDefaultColormap(int param_1,int param_2,int param_3);
void redraw_gl_scene(void);
void draw_alt(void);
void makeColorBoxes(void);
void bgntmesh(void);
void drawOverviewOverlayCursor(void);
void highlightByName(undefined4 param_1);
void czclear(void);
void arcf(void);
void GlobMatch__FPcT1(byte *param_1,byte *param_2);
void endclosedline(void);
void draw_warp_directory(undefined8 param_1,undefined8 param_2,undefined4 *param_3,char param_4);
void SG_getOverlay4Args(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void cmov2(void);
void fromrgb(undefined4 param_1,undefined4 param_2);
void beamup(void);
void setColors__13ByteCodedIconFiN21(int param_1,undefined4 param_2,undefined4 param_3);
void highlightFileLandscape(int param_1,int param_2);
void locateClearAction(undefined4 param_1,int param_2);
void draw_visibility(void);
void save_matrix_state(void);
void endline(void);
void circf(void);
void cpack(void);
void linesmooth(void);
void endpolygon(void);
void endtmesh(void);
void makeDColorBox(uint param_1,int param_2);
void rectf(void);
void newOverlayColormap(undefined4 param_1);
void glcompat(void);
void highlightFile(void);
void gl_swap_buffers(undefined1 param_1);
void highlightDirLandscape(int param_1);
/* highlightOverviewDir - declared in overview.h */
void bgnqstrip(void);
void set_gl_context(int param_1,undefined1 param_2);
void GLXwinset(Display *dpy, Window win);
void SG_getOverlayArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void draw_visible_directory(int param_1);
void draw_directory(ulonglong param_1,int param_2,char param_3);
void locateClear(void);
void beamdown(void);
void overviewLocateHighlight(void);
void rgb_to_cmy(double param_1,double param_2);
void highlightFileWarp(int param_1,int param_2);
void checkPointerFile(int param_1,undefined4 param_2);
void arc(void);
void draw2(void);
void movehoriz(undefined8 param_1,undefined4 param_2);
void checkRedrawScene(void);
void rgb_to_irgb(double param_1,double param_2);
void drawOverviewDirectory(int param_1,char param_2);
void cmy_to_rgb(double param_1,double param_2);
void gl_push_state(void);
void rgbcomplement(undefined4 param_1,undefined4 param_2);
void yiq_to_rgb(double param_1,double param_2);
void bgnclosedline(void);
void setcolorsys(int param_1);
void ortho2(void);
void FAMDebugLevel(undefined4 *param_1,int param_2);
void bgnpoint(void);
void popmatrix(void);
void draw_box(undefined4 *param_1,int param_2,uint param_3);
void linewidth(void);
void makeColorBox(uint param_1,int *param_2);
void zbuffer(void);
void getbeam(void);
void bgnpolygon(void);
void perspective(void);
void calc_h_angle(void);
void calc_v_angle(void);
void draw_scene(void);
void torgb(undefined4 param_1,undefined4 param_2);
void color(void);
void locateHighlight(void);
void draw_warp(void);

#endif // FSN_GRAPHICS_GL_H
