// icons.h - Header for icons module
// Generated by extract_module.py

#ifndef FSN_ICONS_H
#define FSN_ICONS_H

#include "fsn_types.h"
#include "fsn_std.h"

void isSuperByInfo__14ByteCodeLoaderFPcP8RuleInfo(undefined4 param_1,char *param_2,int param_3);
void isSuperByType__14ByteCodeLoaderFPcT1(undefined4 param_1,char *param_2,undefined4 param_3);
void FindInfoByType__14ByteCodeLoaderFPc(int *param_1,char *param_2);
void scale__13ByteCodedIconFf(int param_1,float param_2);
void LoadFileTypingRules__14ByteCodeLoaderFPc(int *param_1,char *param_2);
void FindIconByName__14ByteCodeLoaderFPc(int *param_1);
void SetFile__19FileIconInterpreterFPc(int param_1,char *param_2);
void run__19FileIconInterpreterFPcPvT1(float *param_1,char *param_2,int param_3,int param_4);
void FindInfoByName__14ByteCodeLoaderFPc(int *param_1);
void isSuperByName__14ByteCodeLoaderFPcT1(undefined4 param_1,char *param_2,undefined4 param_3);
void UnSetFile__19FileIconInterpreterFv(int param_1);
void FindIconByType__14ByteCodeLoaderFPc(int *param_1,char *param_2);

#endif // FSN_ICONS_H
