// init.h - Header for init module
// Generated by extract_module.py

#ifndef FSN_INIT_H
#define FSN_INIT_H

#include "fsn_types.h"
#include "fsn_std.h"

void init_color_menus(void);
void get_panel_value(undefined4 param_1);
void init_context_windows(void);
void add_directory_monitor(int param_1);
void flush_rendering(int param_1);
void init_camera_state(void);
void initResources(undefined4 param_1);
void createHelpMenu(undefined4 param_1);
void init_panel_layout(void);
void dirfamMonitor(void);
void setup_fam_monitoring(void);
void setup_context_widgets(void);
void newOverlayColormap(undefined4 param_1);
void dirfamUnmonitorDir(int param_1);
void init_gl_state(int param_1,undefined4 param_2);
void init_database_state(void);
void activeWorkProc(void);
void init_view_transform(void);
void dirfamMonitorDir(int param_1);
void init_gl_lists(void);
void setup_event_handlers(void);
void init_toplevel_resources(undefined4 param_1);
void calc_v_angle(void);
void quit_application(void);
void install_help_callback(undefined4 param_1,undefined4 param_2);
void init_display_state(void);
void check_gl_ready(void);
void allocOverlayColor(undefined4 param_1,undefined4 param_2);
void finalize_menu_setup(undefined4 param_1);
void init_rendering(void);
void widgetHelp(undefined4 param_1,undefined4 param_2);
void dirfamDone(void);
void setup_directory_handler(void);
void init_display_mode(void);

#endif // FSN_INIT_H
