// navigation.h - Header for navigation module
// Generated by extract_module.py

#ifndef FSN_NAVIGATION_H
#define FSN_NAVIGATION_H

#include "fsn_types.h"
#include "fsn_std.h"

void landscapeZoomToFile(int param_1,int param_2);
void zoomPosition(undefined4 param_1);
void zoomToSelection(void);
void findbestfile(char *param_1,int *param_2,undefined4 *param_3);
void findzoom(void);
void do_warp(int param_1);
void pushzoom(void);
void popzoom(void);
void get_warp_entry(int param_1,float *param_2,float *param_3);
void zoomto(double param_1, double param_2, double param_3,
            short param_4, short param_5, int param_6,
            undefined4 param_7, undefined4 param_8);

#endif // FSN_NAVIGATION_H
