// picking.h - Header for picking module
// Generated by extract_module.py

#ifndef FSN_PICKING_H
#define FSN_PICKING_H

#include "fsn_types.h"
#include "fsn_std.h"

void addMark(char *param_1,undefined4 *param_2);
void unselect_directory(void);
void pick(void);
void draw_second_pick(undefined8 param_1,undefined8 param_2,int param_3);
void pickLandscape(int *param_1,undefined4 *param_2,undefined4 *param_3);
void endselect(void);
void pickWarp(int *param_1,undefined4 *param_2,undefined4 *param_3);
void unselect_file(void);
void markAllVisible(int param_1);
void select_file(undefined4 *param_1);
void picksize(void);
void pickPointer(void);
void endpick(void);
void gselect(void);
void select_directory(int param_1);

#endif // FSN_PICKING_H
