// rendering.h - Header for rendering module
// Generated by extract_module.py

#ifndef FSN_RENDERING_H
#define FSN_RENDERING_H

#include "fsn_types.h"
#include "fsn_std.h"

void draw_scene(void);
void draw_positioned_item(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void draw_warp(void);
void display_scan_status(undefined4 param_1,char *param_2,undefined4 param_3);
void draw_mark_overlay(void);
void render_overview_frame(void);
void draw_legend_color_box(undefined4 *param_1,int param_2,uint param_3);
void draw_item_recursive(undefined8 param_1,undefined8 param_2,int param_3);
void draw_warp_directory(undefined8 param_1,undefined8 param_2,undefined4 *param_3,char param_4);
void redraw_gl_scene(void);
void draw_overview_content(void);
void draw_file_icon(byte *param_1);
void display_status_message(char *param_1);
void draw_box(undefined4 *param_1,int param_2,uint param_3);

#endif // FSN_RENDERING_H
