// ui_motif.h - Header for ui_motif module
// Generated by extract_module.py

#ifndef FSN_UI_MOTIF_H
#define FSN_UI_MOTIF_H

#include "fsn_types.h"
#include "fsn_std.h"

void hideOverview(void);
void setScales(void);
void show_error_dialog(undefined4 param_1,undefined4 param_2);
void showPreferencePanel(void);
void createCopyright(undefined4 param_1,int param_2,int param_3);
void createMarkControls(undefined4 param_1);
void createSelectedInfo(undefined4 param_1,undefined4 *param_2,undefined4 param_3);
void createSearch(undefined4 param_1);
void CreateSelectionEntries(undefined4 param_1);
void setMoveAndCopyButtons(void);
void dumpDatabaseCB(void);
void showOverview(void);
void undisplayHourglass(void);
void redrawSelectionNames(void);
void createHelpMenu(undefined4 param_1);
void hidePreferencePanel(void);
void fileCreated(int param_1,char *param_2);
void newTopWindow(undefined4 param_1);
void deleteTopWindow(int param_1);
void deleteCmapWindow(int param_1);
void newCmapWindow(undefined4 param_1);
void set_status_message(undefined4 param_1,int param_2);
void setLabelColors(void);
void createViewer(undefined4 param_1,undefined4 *param_2,undefined4 param_3);
void widgetHelp(undefined4 param_1,undefined4 param_2);
void install_help_callback(undefined4 param_1,undefined4 param_2);
void editCB(void);
void GlxCreateMDraw(void);
void set_main_gl_window(void);
void displayHourglass(undefined4 param_1);
void overlayMenuUnmappedCB(void);
void createOverview(void);
void postMenu(undefined4 param_1,undefined4 param_2,int param_3);
void overlayMenuMappedCB(void);
void CreateSelectionMenus(undefined4 param_1,undefined4 param_2);
void SG_getPopupArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4);
void destroyCopyright(void);

#endif // FSN_UI_MOTIF_H
