// utility.h - Header for utility module
// Generated by extract_module.py

#ifndef FSN_UTILITY_H
#define FSN_UTILITY_H

#include "fsn_types.h"
#include "fsn_std.h"

void cIconToTypeName(void);
void setMainWindow(void);
void FAMMonitorFile2(void);
void compare_dirs(undefined4 *param_1,undefined4 *param_2);
void savecontext(void);
void FAMMonitorDirectory2(void);
void shrinkDueToZoom(void);
void hsv_to_rgb(double param_1, double param_2);
void myContext(undefined4 param_1,undefined4 param_2);
void cFindIconByName(undefined4 param_1);
void getValue__8RuleInfoFi(void);
void dirToPath(undefined1 *param_1,int param_2);
void rgb_to_hsv(double param_1, double param_2);
void rgb_to_hls(void);
void restorecontext(void);
void index_to_dir(void);
void setOverlayWindow(void);
void swapcontext(undefined1 param_1);
void hls_to_rgb(void);
void cIconDraw(int param_1);
void build_path_string(undefined1 *param_1,int param_2);
void age(void);
void quit_application(void);
void setOverviewOverlayWindow(void);
void getnum__FiT1PvT1(int param_1,__off_t param_2,void *param_3,size_t param_4);
void copycontext(void);
void getTypeName__8RuleInfoFv(void);
void getlong__FPc(void);
void getcolorsys(void);
void typeName__13ByteCodedIconFv(void);
void do_perspective(void);
void cFindIconByType(undefined4 param_1);
void FAMClose(int param_1);
void cIconGetValue(void);
void equalPositions(void);
void cSetColors(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void cIconInit(undefined4 param_1);
void compare_files(undefined4 *param_1,undefined4 *param_2);
void bitpat__Ff(void);
void setOverviewWindow(void);
void getshort__FPc(void);
void doneFam(void);
void FAMOpen(undefined4 param_1);

#endif // FSN_UTILITY_H
