/**
 * XtStringConversionWarning
 *
 * Extracted from fsn.c lines 19385-19624
 * Category: Other
 */

void XtStringConversionWarning(void)

{
  undefined4 in_a3;
  int iStackX_0;
  undefined1 auStackX_4 [4];
  undefined1 auStackX_8 [8];
  undefined1 *puVar1;
  undefined4 uVar2;
  
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  (*(code *)&__DT_MIPS_RLD_TEXT_RESOLVE_ADDR)();
  __Argv = auStackX_4;
  _DAT_0fb52740 = auStackX_8 + iStackX_0 * 4;
  __Argc = iStackX_0;
  puVar1 = &_mips_gp0_value;
  uVar2 = 0;
  __istart();
  (**(code **)(puVar1 + -0x7c5c))();
  uVar2 = (**(code **)(puVar1 + -0x7ae8))
                    (**(undefined4 **)(puVar1 + -0x760c),**(undefined4 **)(puVar1 + -0x7608),
                     **(undefined4 **)(puVar1 + -0x7f48),in_a3,puVar1,uVar2);
  (**(code **)(puVar1 + -0x7c60))(uVar2);
  return;
}
