// filesystem.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/filesystem.h"

void dirfamUnmonitor(void)

{
  if ((fsn_resources == '\0') && (database_loaded_flag != 0)) {
    XtRemoveInput();
    database_loaded_flag = 0;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void fileStoppedExecuting(undefined4 param_1)

{
  int iVar1;
  
  iVar1 = validate_directory_access();
  if ((iVar1 != 0) && (*(int *)(iVar1 + 0x20) != 0)) {
    FUN_00433e24(*(undefined4 *)(iVar1 + 0x20),0,0,0,0,0);
    *(byte *)(iVar1 + 0x29) = *(byte *)(iVar1 + 0x29) & 0xf7;
  }
  FUN_004184c8(param_1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dumpDatabaseCB(void)

{
  refresh_after_change();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamInit(void)

{
  int iVar1;
  
  if ((fsn_resources == '\0') && (iVar1 = fam_open_wrapper(&database_root_node), iVar1 < 0)) {
    fprintf((FILE *)0xfb52904,
            "Could not run FAM.  This program requires FAM to be installed.\nYou may need to install eoe2.sw.envm to obtain FAM\n"
           );
                    // WARNING: Subroutine does not return
    exit(1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void warpZoomToFile(int param_1,int param_2)

{
  uint uVar1;
  undefined8 in_f18;
  
  uVar1 = (uint)((ulonglong)in_f18 >> 0x20);
  if (param_1 != 0) {
    if (param_1 != *(int *)(curcontext + 0x3c)) {
      do_warp();
    }
    if (param_2 != 0) {
      set_camera_lookat((double)*(float *)(param_2 + 0x14) -
                   (double)*(float *)(curcontext + 0x14) * (double)database_version,
                   ((double)*(float *)(param_2 + 0x18) +
                   (double)*(float *)(param_1 + 0x3c) / (double)((ulonglong)uVar1 << 0x20)) -
                   (double)*(float *)(curcontext + 0x18) * (double)database_version);
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void buildingDatabaseMessage(void)

{
  undefined4 uVar1;
  
  uVar1 = XmTextGetLastPosition(active_file_list);
  XmTextInsert(active_file_list,uVar1,PTR_s_Please_be_patient_while_the_file_10007b64);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void check_unmonitor_dp(int param_1)

{
  int iVar1;
  int iVar2;
  
  iVar1 = *(int *)(param_1 + 0x74);
  *(undefined4 *)(param_1 + 100) = 0;
  if ((((iVar1 << 3 < 0) && (iVar1 << 10 < 0)) && (-1 < iVar1 << 0xb)) &&
     (param_1 != *(int *)(curcontext + 0x44))) {
    iVar2 = 0;
    if (altcontext[0xc51] != '\0') {
      iVar2 = *(int *)(altcontext + 0x44);
    }
    if ((iVar2 != param_1) && (-1 < iVar1 << 0xe)) {
      FUN_00427ec8(param_1);
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void load_db(void)

{
  int iVar1;
  
  FUN_00415b48();
  iVar1 = (*(code *)*vinfop)();
  if (iVar1 == -1) {
                    // WARNING: Bad instruction - Truncating control flow here
    halt_baddata();
  }
  if (iVar1 - 1U < 8) {
                    // WARNING: Bad instruction - Truncating control flow here
    halt_baddata();
  }
  fprintf((FILE *)0xfb52904,"garbage in database, quitting\n");
                    // WARNING: Subroutine does not return
  exit(1);
}

void dirfamUnmonitorDir(int param_1)

{
  if ((fsn_resources == '\0') && (*(int *)(param_1 + 0x74) << 10 < 0)) {
    build_path_string(0,param_1);
    fam_cancel_monitor_wrapper(&database_root_node,param_1 + 0x60);
    *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) & 0xdf;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMResumeMonitor(undefined4 *param_1,undefined4 *param_2)

{
  __uid_t _Var1;
  __gid_t _Var2;
  size_t sVar3;
  char acStack_bb8 [3000];
  
  _Var1 = getuid();
  _Var2 = getgid();
  sprintf(acStack_bb8,s_U_d__d__d_10009f08,*param_2,_Var1,_Var2);
  sVar3 = strlen(acStack_bb8);
  write_data_buffer(param_1[1],*param_1,acStack_bb8,sVar3 + 1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void finddir(int param_1,undefined4 param_2)

{
  undefined4 auStack_80 [30];
  undefined4 *apuStack_8 [2];
  
  if (*(int *)(param_1 + 0x14) != 0) {
    apuStack_8[0] = auStack_80;
    auStack_80[0] = param_2;
    bsearch(apuStack_8,*(void **)(param_1 + 0x18),*(size_t *)(param_1 + 0x14),4,compare_dirs);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMPending(uint *param_1)

{
  __fd_mask *p_Var1;
  fd_set fStack_80;
  
  bzero(&fStack_80,0x80);
  p_Var1 = fStack_80.fds_bits + (*param_1 >> 5);
  *p_Var1 = *p_Var1 | 1 << (*param_1 & 0x1f);
  select(0x400,&fStack_80,(fd_set *)0x0,(fd_set *)0x0,(timeval *)&database_dirty_flag);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void readingDatabaseMessage(void)

{
  undefined4 uVar1;
  
  uVar1 = XmTextGetLastPosition(active_file_list);
  XmTextInsert(active_file_list,uVar1,PTR_s_Please_be_patient_while_the_file_10007b60);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void fileerror(char *param_1,char *param_2)

{
  char acStack_434 [1076];
  
  strcpy(acStack_434,param_1);
  strcat(acStack_434," ");
  strcat(acStack_434,param_2);
  show_error_message(acStack_434);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMCancelMonitor(undefined4 *param_1,undefined4 *param_2)

{
  __uid_t _Var1;
  __gid_t _Var2;
  size_t sVar3;
  char acStack_bb8 [3000];
  
  _Var1 = getuid();
  _Var2 = getgid();
  sprintf(acStack_bb8,s_C_d__d__d_10009f14,*param_2,_Var1,_Var2);
  sVar3 = strlen(acStack_bb8);
  write_data_buffer(param_1[1],*param_1,acStack_bb8,sVar3 + 1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void updateDir(int param_1)

{
  size_t sVar1;
  int iVar2;
  char acStack_400 [1024];
  
  build_path_string(acStack_400,*(undefined4 *)(param_1 + 0x28));
  sVar1 = strlen(acStack_400);
  iVar2 = check_directory_flags(param_1,acStack_400,acStack_400 + sVar1,0);
  if (iVar2 != 0) {
    process_child_directory(param_1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void filemessage(char *param_1,char *param_2,undefined4 param_3)

{
  char *pcVar1;
  char cVar2;
  char acStack_434 [1076];
  
  if (*param_2 == '/') {
    cVar2 = param_2[1];
    while (cVar2 == '/') {
      pcVar1 = param_2 + 2;
      param_2 = param_2 + 1;
      cVar2 = *pcVar1;
    }
  }
  strcpy(acStack_434,param_1);
  strcat(acStack_434," ");
  strcat(acStack_434,param_2);
  set_status_message(acStack_434,param_3);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamDone(void)

{
  if (fsn_resources == '\0') {
    FUN_00439c0c(&database_root_node);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMSuspendMonitor(undefined4 *param_1,undefined4 *param_2)

{
  __uid_t _Var1;
  __gid_t _Var2;
  size_t sVar3;
  char acStack_bb8 [3000];
  
  _Var1 = getuid();
  _Var2 = getgid();
  sprintf(acStack_bb8,s_S_d__d__d_10009efc,*param_2,_Var1,_Var2);
  sVar3 = strlen(acStack_bb8);
  write_data_buffer(param_1[1],*param_1,acStack_bb8,sVar3 + 1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void findfile(int param_1,undefined4 param_2)

{
  undefined4 auStack_34 [11];
  undefined4 *apuStack_8 [2];
  
  if (*(int *)(param_1 + 0xc) != 0) {
    apuStack_8[0] = auStack_34;
    auStack_34[0] = param_2;
    bsearch(apuStack_8,*(void **)(param_1 + 0x10),*(size_t *)(param_1 + 0xc),4,compare_files);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void savePositions(void)

{
  get_view_position(&fam_connection);
  if (altcontext[0xc51] != '\0') {
    gl_swap_buffers(1);
    get_view_position(&fam_request_id);
    gl_swap_buffers(1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamMonitorDir(int param_1)

{
  undefined4 uVar1;
  
  if ((fsn_resources == '\0') && (-1 < *(int *)(param_1 + 0x74) << 10)) {
    uVar1 = build_path_string(0,param_1);
    FUN_00439eec(&database_root_node,uVar1,param_1 + 0x60);
    *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) | 0x20;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void gotoFileName(undefined4 param_1)

{
  int iStack_8;
  int iStack_4;
  
  FUN_0042ab1c(param_1,&iStack_4,&iStack_8);
  if (iStack_4 != 0) {
    update_marked_item();
    if (iStack_8 != 0) {
      get_item_screen_coords();
    }
    FUN_0041fbb4();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void scheduleDatabaseDumpTimeout(void)

{
  XtAppAddTimeOut(app_context,900000,databaseDumpTimeout,0);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void fileExecuting(int param_1)

{
  int iVar1;
  
  iVar1 = validate_directory_access();
  if ((iVar1 != 0) && (*(int *)(iVar1 + 0x20) != 0)) {
    FUN_00433e24(*(undefined4 *)(iVar1 + 0x20),1,0,0,0,0);
    *(byte *)(iVar1 + 0x29) = *(byte *)(iVar1 + 0x29) & 0xf7 | 8;
    *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) | 2;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void databaseDumpTimeout(void)

{
  refresh_after_change();
  FUN_00415550();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMNextEvent(uint *param_1,undefined4 param_2)

{
  int iVar1;
  int *piVar2;
  undefined1 auStack_c38 [3000];
  uint auStack_80 [32];
  
  bzero(auStack_80,0x80);
  auStack_80[*param_1 >> 5] = auStack_80[*param_1 >> 5] | 1 << (*param_1 & 0x1f);
  piVar2 = (int *)param_1[1];
  if (((*(int *)(*piVar2 + 0xc) != 0) ||
      (((iVar1 = FUN_0043b3b8(), iVar1 != -1 && (*(int *)(*piVar2 + 0x179c) == 0)) &&
       (*(int *)(*piVar2 + 0xc) != 0)))) &&
     (iVar1 = FUN_0043b538(piVar2,*param_1,auStack_c38,0x400), iVar1 != -1)) {
    FUN_0043a664(param_1,auStack_c38,param_2);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMMonitorDirectory(undefined4 param_1,char *param_2,int *param_3,undefined4 param_4)

{
  int iVar1;
  size_t sVar2;
  
  iVar1 = FUN_0043ade8();
  if (iVar1 != -1) {
    *param_3 = iVar1;
    sVar2 = strlen(param_2);
    if (sVar2 < 0x401) {
      fam_monitor_request(param_1,param_2,param_3,param_4,0x4d);
    }
    else {
      syslog(1,s_path_too_long_10009e84);
      _DAT_0fb52720 = 0x4e;
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamMonitor(void)

{
  if ((fsn_resources == '\0') && (database_loaded_flag == 0)) {
    database_loaded_flag = XtAppAddInput(app_context,database_root_node,1,FUN_00428044,0);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMMonitorFile(undefined4 param_1,char *param_2,int *param_3,undefined4 param_4)

{
  int iVar1;
  size_t sVar2;
  
  iVar1 = FUN_0043ade8();
  if (iVar1 != -1) {
    *param_3 = iVar1;
    sVar2 = strlen(param_2);
    if (sVar2 < 0x401) {
      fam_monitor_request(param_1,param_2,param_3,param_4,0x57);
    }
    else {
      syslog(1,s_path_too_long_10009e94);
      _DAT_0fb52720 = 0x4e;
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
