// icons.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/icons.h"

void isSuperByInfo__14ByteCodeLoaderFPcP8RuleInfo(undefined4 param_1,char *param_2,int param_3)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = *(undefined4 **)(param_3 + 0x30);
  while ((puVar2 != (undefined4 *)0x0 && (iVar1 = strcmp(param_2,(char *)*puVar2), iVar1 != 0))) {
    puVar2 = (undefined4 *)puVar2[1];
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void isSuperByType__14ByteCodeLoaderFPcT1(undefined4 param_1,char *param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 *puVar2;
  
  iVar1 = FUN_00434cd0(param_1,param_3);
  if (iVar1 != 0) {
    puVar2 = *(undefined4 **)(iVar1 + 0x30);
    while ((puVar2 != (undefined4 *)0x0 && (iVar1 = strcmp(param_2,(char *)*puVar2), iVar1 != 0))) {
      puVar2 = (undefined4 *)puVar2[1];
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FindInfoByType__14ByteCodeLoaderFPc(int *param_1,char *param_2)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = (undefined4 *)*param_1;
  while ((puVar2 != (undefined4 *)0x0 && (iVar1 = strcmp(param_2,(char *)*puVar2), iVar1 != 0))) {
    puVar2 = (undefined4 *)puVar2[0x1a];
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void scale__13ByteCodedIconFf(int param_1,float param_2)

{
  *(float *)(param_1 + 0x20) = *(float *)(param_1 + 0x20) * param_2;
  *(float *)(param_1 + 0x24) = *(float *)(param_1 + 0x24) * param_2;
  *(float *)(param_1 + 0x28) = *(float *)(param_1 + 0x28) * param_2;
  *(float *)(param_1 + 0x2c) = *(float *)(param_1 + 0x2c) * param_2;
  *(float *)(param_1 + 0x30) = *(float *)(param_1 + 0x30) * param_2;
  *(float *)(param_1 + 0x34) = *(float *)(param_1 + 0x34) * param_2;
  *(float *)(param_1 + 0x38) = *(float *)(param_1 + 0x38) * param_2;
  *(float *)(param_1 + 0x3c) = *(float *)(param_1 + 0x3c) * param_2;
  *(float *)(param_1 + 0x40) = *(float *)(param_1 + 0x40) * param_2;
  *(float *)(param_1 + 0x44) = *(float *)(param_1 + 0x44) * param_2;
  *(float *)(param_1 + 0x48) = *(float *)(param_1 + 0x48) * param_2;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void LoadFileTypingRules__14ByteCodeLoaderFPc(int *param_1,char *param_2)

{
  char *pcVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  int *__buf;
  size_t sVar5;
  undefined4 *puVar6;
  int *piVar7;
  char *pcVar8;
  int *piVar9;
  size_t __nbytes;
  int iVar10;
  int iVar11;
  undefined4 *puStack_cc;
  undefined4 *puStack_c0;
  stat sStack_b8;
  undefined1 auStack_30 [4];
  int iStack_2c;
  undefined1 auStack_28 [24];
  int iStack_10;
  int iStack_c;
  
  iVar10 = 0;
  iVar11 = 0;
  iVar3 = open(param_2,0);
  if (iVar3 != -1) {
    fstat(iVar3,&sStack_b8);
    if (0xc < sStack_b8.st_blksize) {
      read(iVar3,auStack_30,0xc);
      iVar4 = bcmp(auStack_30,&magic1,4);
      if (((iVar4 == 0) && (iVar4 = bcmp(auStack_28,&magic3,4), iVar4 == 0)) &&
         (iStack_2c == magic2)) {
        __nbytes = sStack_b8.st_blksize - 0xc;
        __buf = (int *)__nw__FUi(__nbytes);
        if (__buf == (int *)0x0) {
          close(iVar3);
        }
        else {
          sVar5 = read(iVar3,__buf,__nbytes);
          if (__nbytes == sVar5) {
            puVar6 = (undefined4 *)__nw__FUi(8);
            iVar3 = param_1[4];
            piVar7 = (int *)((int)__buf + __nbytes);
            *puVar6 = __buf;
            puVar6[1] = iVar3;
            param_1[4] = (int)puVar6;
            for (; __buf < piVar7; __buf = (int *)((int)__buf + (iStack_10 + 3U & 0xfffffffc) + 8))
            {
              iStack_c = *__buf;
              iStack_10 = __buf[1];
              if ((iStack_c < 4) || (0x20 < iStack_c)) {
                if (iStack_c == 1) {
                  iVar10 = FUN_00435444(0);
                  if (*param_1 == 0) {
                    param_1[1] = iVar10;
                    *param_1 = iVar10;
                  }
                  else {
                    *(int *)(param_1[1] + 0x68) = iVar10;
                    param_1[1] = iVar10;
                  }
                  *(int **)param_1[1] = __buf + 2;
                }
                else if (iStack_c == 2) {
                  *(int **)(iVar10 + 8) = __buf + 2;
                  *(int *)(iVar10 + 0xc) = iStack_10;
                }
                else if (iStack_c == 3) {
                  *(int **)(iVar10 + 0x1c) = __buf + 2;
                  *(int *)(iVar10 + 0x20) = iStack_10;
                }
                else if (iStack_c == 0x21) {
                  bcopy(__buf + 2,(void *)(iVar10 + 0x38),4);
                  bcopy(__buf + 3,(void *)(iVar10 + 0x3c),4);
                  bcopy(__buf + 4,(void *)(iVar10 + 0x40),4);
                  bcopy(__buf + 5,(void *)(iVar10 + 0x44),4);
                }
                else if (iStack_c == 0x22) {
                  bcopy(__buf + 2,(void *)(iVar10 + 0x48),4);
                  bcopy(__buf + 3,(void *)(iVar10 + 0x4c),4);
                }
                else if (iStack_c == 0x23) {
                  *(int **)(iVar10 + 4) = __buf + 2;
                }
                else if (iStack_c == 0x24) {
                  *(int **)(iVar10 + 0x18) = __buf + 2;
                }
                else if (iStack_c == 0x25) {
                  *(int **)(iVar10 + 0x10) = __buf + 2;
                  *(int *)(iVar10 + 0x14) = iStack_10;
                }
                else if (iStack_c == 0x26) {
                  *(int **)(iVar10 + 0x24) = __buf + 2;
                  *(int *)(iVar10 + 0x28) = iStack_10;
                }
                else if (iStack_c == 0x2b) {
                  bcopy(__buf + 2,(void *)(iVar10 + 100),4);
                }
                else if (iStack_c == 0x2c) {
                  iVar3 = iStack_10 + 8;
                  iStack_c = 0x2c;
                  piVar9 = __buf + 2;
                  while (piVar9 < (int *)((int)__buf + iVar3)) {
                    if (*(int *)(iVar10 + 0x2c) == 0) {
                      puVar6 = (undefined4 *)__nw__FUi(0xc);
                      *(undefined4 **)(iVar10 + 0x2c) = puVar6;
                    }
                    else {
                      puVar6 = (undefined4 *)__nw__FUi(0xc);
                      puStack_c0[2] = puVar6;
                    }
                    puVar6[2] = 0;
                    *puVar6 = piVar9;
                    cVar2 = *(char *)piVar9;
                    while (cVar2 != '\0') {
                      pcVar8 = (char *)((int)piVar9 + 1);
                      piVar9 = (int *)((int)piVar9 + 1);
                      cVar2 = *pcVar8;
                    }
                    pcVar8 = (char *)((int)piVar9 + 1);
                    puVar6[1] = pcVar8;
                    cVar2 = *pcVar8;
                    while (cVar2 != '\0') {
                      pcVar1 = pcVar8 + 1;
                      pcVar8 = pcVar8 + 1;
                      cVar2 = *pcVar1;
                    }
                    puStack_c0 = puVar6;
                    piVar9 = (int *)(pcVar8 + 1);
                  }
                }
                else if (iStack_c == 0x2d) {
                  iVar3 = iStack_10 + 8;
                  iStack_c = 0x2d;
                  for (piVar9 = __buf + 2; piVar9 < (int *)((int)__buf + iVar3);
                      piVar9 = (int *)((int)piVar9 + 1)) {
                    if (*(int *)(iVar10 + 0x30) == 0) {
                      puVar6 = (undefined4 *)__nw__FUi(8);
                      *(undefined4 **)(iVar10 + 0x30) = puVar6;
                    }
                    else {
                      puVar6 = (undefined4 *)__nw__FUi(8);
                      puStack_cc[1] = puVar6;
                    }
                    puVar6[1] = 0;
                    *puVar6 = piVar9;
                    cVar2 = *(char *)piVar9;
                    while (cVar2 != '\0') {
                      pcVar8 = (char *)((int)piVar9 + 1);
                      piVar9 = (int *)((int)piVar9 + 1);
                      cVar2 = *pcVar8;
                    }
                    puStack_cc = puVar6;
                  }
                }
                else if (iStack_c == 0x2e) {
                  *(undefined4 *)(iVar10 + 0x34) = 1;
                }
                else if (iStack_c == 0x27) {
                  iVar11 = FUN_0043551c(0);
                  if (param_1[2] == 0) {
                    param_1[3] = iVar11;
                    param_1[2] = iVar11;
                  }
                  else {
                    *(int *)(param_1[3] + 0x10) = iVar11;
                    param_1[3] = iVar11;
                  }
                  *(int **)param_1[3] = __buf + 2;
                }
                else if (iStack_c == 0x28) {
                  *(int **)(iVar11 + 4) = __buf + 2;
                }
                else if (iStack_c == 0x29) {
                  bcopy(__buf + 2,(void *)(iVar11 + 8),4);
                }
                else if (iStack_c == 0x2a) {
                  *(int **)(iVar11 + 0xc) = __buf + 2;
                }
              }
              else {
                *(int **)(iVar10 + iStack_c * 4 + 0x40) = __buf + 2;
              }
            }
          }
          else {
            __dl__FPv(__buf);
            close(iVar3);
          }
        }
      }
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FindIconByName__14ByteCodeLoaderFPc(int *param_1)

{
  int iVar1;
  int iVar2;
  
  iVar2 = *param_1;
  FUN_004357ec(&TheFileIconInterpreter);
  if ((DAT_10009c90 == 0) && (DAT_10009c8c == 0)) {
    FUN_00435938(&TheFileIconInterpreter);
    FUN_004349f8(param_1,s_Unknown_10009a20);
  }
  else {
    for (; iVar2 != 0; iVar2 = *(int *)(iVar2 + 0x68)) {
      if ((((*(int *)(iVar2 + 4) != 0) && (DAT_10009c90 == *(int *)(iVar2 + 0x34))) &&
          (DAT_10009c80 != 0)) &&
         (iVar1 = FUN_00435a28(&TheFileIconInterpreter,*(int *)(iVar2 + 4),
                               *(undefined4 *)(iVar2 + 8),*(undefined4 *)(iVar2 + 0x10)), iVar1 != 0
         )) {
        FUN_00435938(&TheFileIconInterpreter);
        FUN_00435034(0,iVar2);
        halt_baddata();
      }
    }
    FUN_00435938(&TheFileIconInterpreter);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void SetFile__19FileIconInterpreterFPc(int param_1,char *param_2)

{
  char *pcVar1;
  int iVar2;
  ssize_t sVar3;
  
  *(char **)(param_1 + 0x228) = param_2;
  if (param_2 != (char *)0x0) {
    pcVar1 = strrchr(param_2,0x2f);
    *(char **)(param_1 + 0x22c) = pcVar1;
    if (pcVar1 == (char *)0x0) {
      *(undefined4 *)(param_1 + 0x22c) = *(undefined4 *)(param_1 + 0x228);
    }
    else {
      *(int *)(param_1 + 0x22c) = *(int *)(param_1 + 0x22c) + 1;
    }
  }
  iVar2 = stat(*(char **)(param_1 + 0x228),(stat *)(param_1 + 0x244));
  *(uint *)(param_1 + 0x230) = (uint)(iVar2 == 0);
  if (((iVar2 == 0) == 0) || ((*(uint *)(param_1 + 600) & 0xf000 | 0x8000) != 0x8000)) {
    *(undefined4 *)(param_1 + 0x240) = 1;
  }
  else {
    *(undefined4 *)(param_1 + 0x240) = 0;
  }
  if (*(int *)(param_1 + 0x240) == 0) {
    iVar2 = open(*(char **)(param_1 + 0x228),4);
    *(int *)(param_1 + 0x238) = iVar2;
    if (iVar2 == -1) {
      *(undefined4 *)(param_1 + 0x23c) = 0;
    }
    else {
      *(undefined4 *)(param_1 + 0x23c) = 1;
    }
  }
  else {
    *(undefined4 *)(param_1 + 0x23c) = 0;
  }
  if (*(int *)(param_1 + 0x23c) == 0) {
    *(undefined4 *)(param_1 + 0x234) = 0;
  }
  else {
    sVar3 = read(*(int *)(param_1 + 0x238),(void *)(param_1 + 0x20),0x200);
    *(ssize_t *)(param_1 + 0x2cc) = sVar3;
    if (sVar3 < 0) {
      *(undefined4 *)(param_1 + 0x234) = 0;
    }
    else {
      *(undefined4 *)(param_1 + 0x234) = 1;
    }
  }
  *(undefined4 *)(param_1 + 0x220) = 0;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void run__19FileIconInterpreterFPcPvT1(float *param_1,char *param_2,int param_3,int param_4)

{
  int *piVar1;
  byte *pbVar2;
  uint uVar3;
  uint uVar4;
  float *pfVar5;
  size_t sVar6;
  size_t __n;
  int iVar7;
  int iVar8;
  char *pcVar9;
  byte *pbVar10;
  char cVar11;
  float fVar12;
  float fVar13;
  float *pfVar14;
  float *pfVar15;
  float *pfVar16;
  float fVar17;
  char *pcVar18;
  int iVar19;
  char *__s1;
  uint in_fcsr;
  stat sStack_197c;
  char acStack_18f4 [272];
  float *pfStack_17e4;
  float fStack_17e0;
  ushort uStack_17dc;
  byte bStack_17d9;
  float fStack_17d8;
  short sStack_17d4;
  byte bStack_17d1;
  char *pcStack_17d0;
  int iStack_17cc;
  float fStack_17c8;
  float fStack_17c4;
  float afStack_17bc [511];
  char *pcStack_fc0;
  float fStack_fbc;
  float fStack_fb8;
  float fStack_fb4;
  float afStack_fa8 [1002];
  
  iStack_17cc = 0;
  cVar11 = *param_2;
  pfVar16 = afStack_fa8;
  iVar19 = 0;
  __s1 = pcStack_fc0;
  pcVar18 = param_2;
joined_r0x00435ac4:
  do {
    while( true ) {
      while( true ) {
        while( true ) {
          while( true ) {
            while( true ) {
              while( true ) {
                while( true ) {
                  while( true ) {
                    while( true ) {
                      while( true ) {
                        while( true ) {
                          while( true ) {
                            while( true ) {
                              while( true ) {
                                while( true ) {
                                  while( true ) {
                                    while( true ) {
                                      while( true ) {
                                        while( true ) {
                                          while( true ) {
                                            while( true ) {
                                              while( true ) {
                                                while( true ) {
                                                  while( true ) {
                                                    while( true ) {
                                                      while( true ) {
                                                        while( true ) {
                                                          while( true ) {
                                                            while( true ) {
                                                              while( true ) {
                                                                while( true ) {
                                                                  while( true ) {
                                                                    while( true ) {
                                                                      while( true ) {
                                                                        while( true ) {
                                                                          while( true ) {
                                                                            while( true ) {
                                                                              while( true ) {
                                                                                while( true ) {
                                                                                  while( true ) {
                                                                                    while( true ) {
                                                                                      while( true )
                                                                                      {
                                                                                        while( true 
                                                  ) {
                                                    while( true ) {
                                                      while( true ) {
                                                        while( true ) {
                                                          while( true ) {
                                                            while( true ) {
                                                              while( true ) {
                                                                while( true ) {
                                                                  while( true ) {
                                                                    while( true ) {
                                                                      while( true ) {
                                                                        if (cVar11 == '\x1b') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                                          halt_baddata();
                                                                        }
                                                                        if (cVar11 != '\x1c') break;
                                                                        __s1 = (char *)pfVar16[-1];
                                                                        if (__s1 == (char *)pfVar16[
                                                  -2]) {
                                                    pfVar16[-2] = 1.4013e-45;
                                                  }
                                                  else {
                                                    pfVar16[-2] = 0.0;
                                                  }
                                                  pfVar16 = pfVar16 + -1;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 == '\x10') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 != '\x11') break;
                                                  __s1 = (char *)pfVar16[-1];
                                                  if (__s1 == (char *)0x0) {
                                                    pfVar16[-1] = 1.4013e-45;
                                                  }
                                                  else {
                                                    pfVar16[-1] = 0.0;
                                                  }
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 == '\"') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 != '#') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  if ((int)pfVar16[-1] < (int)__s1) {
                                                    pfVar16[-2] = 1.4013e-45;
                                                  }
                                                  else {
                                                    pfVar16[-2] = 0.0;
                                                  }
                                                  pfVar16 = pfVar16 + -1;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 == '\x1f') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 != ' ') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  if ((int)__s1 < (int)pfVar16[-1]) {
                                                    pfVar16[-2] = 0.0;
                                                  }
                                                  else {
                                                    pfVar16[-2] = 1.4013e-45;
                                                  }
                                                  pfVar16 = pfVar16 + -1;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 == '.') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 != '/') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  if ((int)__s1 < (int)pfVar16[-1]) {
                                                    pfVar16[-2] = 1.4013e-45;
                                                  }
                                                  else {
                                                    pfVar16[-2] = 0.0;
                                                  }
                                                  pfVar16 = pfVar16 + -1;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 == '&') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 != '\'') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  if ((int)pfVar16[-1] < (int)__s1) {
                                                    pfVar16[-2] = 0.0;
                                                  }
                                                  else {
                                                    pfVar16[-2] = 1.4013e-45;
                                                  }
                                                  pfVar16 = pfVar16 + -1;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 == '6') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 != '7') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  if (__s1 == (char *)pfVar16[-1]) {
                                                    pfVar16[-2] = 0.0;
                                                  }
                                                  else {
                                                    pfVar16[-2] = 1.4013e-45;
                                                  }
                                                  pfVar16 = pfVar16 + -1;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '?') break;
                                                  pfVar16[-2] = pfVar16[-2] + pfVar16[-1];
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  pfVar16 = pfVar16 + -1;
                                                  }
                                                  if (cVar11 != '@') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  pfVar16[-2] = (float)(__s1 + (int)pfVar16[-1]);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  pfVar16 = pfVar16 + -1;
                                                  }
                                                  if (cVar11 != '0') break;
                                                  pfVar16[-2] = pfVar16[-2] - pfVar16[-1];
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  pfVar16 = pfVar16 + -1;
                                                  }
                                                  if (cVar11 != '1') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  pfVar16[-2] = (float)((int)__s1 - (int)pfVar16[-1]
                                                                       );
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  pfVar16 = pfVar16 + -1;
                                                  }
                                                  if (cVar11 != 'X') break;
                                                  pfVar5 = pfVar16 + -1;
                                                  pfVar15 = pfVar16 + -2;
                                                  pfVar14 = pfVar16 + -2;
                                                  pfVar16 = pfVar16 + -1;
                                                  *pfVar14 = *pfVar15 * *pfVar5;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != 'Y') break;
                                                  pfVar5 = pfVar16 + -1;
                                                  __s1 = (char *)pfVar16[-2];
                                                  pfVar15 = pfVar16 + -2;
                                                  pfVar16 = pfVar16 + -1;
                                                  *pfVar15 = (float)((int)__s1 * (int)*pfVar5);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != 'L') break;
                                                  pfVar5 = pfVar16 + -1;
                                                  pfVar15 = pfVar16 + -2;
                                                  pfVar14 = pfVar16 + -2;
                                                  pfVar16 = pfVar16 + -1;
                                                  *pfVar14 = *pfVar15 / *pfVar5;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 == 'M') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 == '3') {
                                                    fVar17 = pfVar16[-2];
                                                    FUN_004355f8(pfVar16[-1]);
                                                    FUN_004355f8(fVar17);
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 == '4') {
                    // WARNING: Bad instruction - Truncating control flow here
                                                    halt_baddata();
                                                  }
                                                  if (cVar11 != '\x02') break;
                                                  pfVar5 = pfVar16 + -1;
                                                  pfVar15 = pfVar16 + -2;
                                                  fVar17 = *pfVar15;
                                                  pfVar16 = pfVar16 + -1;
                                                  uVar3 = FUN_004355f8(*pfVar5);
                                                  uVar4 = FUN_004355f8(fVar17);
                                                  *pfVar15 = (float)(int)(uVar4 & uVar3);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '\x03') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  pfVar16[-2] = (float)((uint)__s1 &
                                                                       (uint)pfVar16[-1]);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  pfVar16 = pfVar16 + -1;
                                                  }
                                                  if (cVar11 != ':') break;
                                                  pfVar5 = pfVar16 + -1;
                                                  pfVar15 = pfVar16 + -2;
                                                  fVar17 = *pfVar15;
                                                  pfVar16 = pfVar16 + -1;
                                                  uVar3 = FUN_004355f8(*pfVar5);
                                                  uVar4 = FUN_004355f8(fVar17);
                                                  *pfVar15 = (float)(int)(uVar4 | uVar3);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != ';') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  pfVar16[-2] = (float)((uint)__s1 |
                                                                       (uint)pfVar16[-1]);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  pfVar16 = pfVar16 + -1;
                                                  }
                                                  if (cVar11 != '_') break;
                                                  pfVar5 = pfVar16 + -1;
                                                  pfVar15 = pfVar16 + -2;
                                                  fVar17 = *pfVar15;
                                                  pfVar16 = pfVar16 + -1;
                                                  uVar3 = FUN_004355f8(*pfVar5);
                                                  uVar4 = FUN_004355f8(fVar17);
                                                  *pfVar15 = (float)(int)(uVar4 ^ uVar3);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '`') break;
                                                  __s1 = (char *)pfVar16[-2];
                                                  pfVar16[-2] = (float)((uint)__s1 ^
                                                                       (uint)pfVar16[-1]);
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  pfVar16 = pfVar16 + -1;
                                                  }
                                                  if (cVar11 != '5') break;
                                                  fStack_17c8 = pfVar16[-1];
                                                  pcVar18 = pcVar18 + 1;
                                                  fStack_17c4 = pfVar16[-2];
                                                  pfVar16 = pfVar16 + -2;
                                                  cVar11 = *pcVar18;
                                                  iVar19 = 0;
                                                  }
                                                  if (cVar11 != '\x13') break;
                                                  fVar17 = pfVar16[-2];
                                                  fVar12 = pfVar16[-1];
                                                  pfVar16 = pfVar16 + -2;
                                                  iVar19 = 0;
                                                  set_gl_color(iStack_17cc);
                                                  move2(fStack_17c4,fStack_17c8);
                                                  draw2(fVar17,fVar12);
                                                  cVar11 = pcVar18[1];
                                                  fStack_17c4 = fVar17;
                                                  fStack_17c8 = fVar12;
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '\x0f') break;
                                                  if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
                                                    fVar17 = ROUND(pfVar16[-1]);
                                                  }
                                                  else {
                                                    fVar17 = FLOOR(pfVar16[-1]);
                                                  }
                                                  iStack_17cc = (int)fVar17;
                                                  pfVar16 = pfVar16 + -1;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '\n') break;
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  iVar19 = 0;
                                                  }
                                                  if (cVar11 != 'A') break;
                                                  afStack_17bc[1] = pfVar16[-1];
                                                  pcVar18 = pcVar18 + 1;
                                                  afStack_17bc[0] = pfVar16[-2];
                                                  pfVar16 = pfVar16 + -2;
                                                  cVar11 = *pcVar18;
                                                  iVar19 = 1;
                                                  }
                                                  if ((cVar11 != '>') && (cVar11 != ']')) break;
                                                  if (iVar19 < 0xff) {
                                                    afStack_17bc[iVar19 * 2] = pfVar16[-2];
                                                    pfVar5 = pfVar16 + -1;
                                                    iVar7 = iVar19 * 2;
                                                    iVar19 = iVar19 + 1;
                                                    pfVar16 = pfVar16 + -2;
                                                    afStack_17bc[iVar7 + 1] = *pfVar5;
                                                  }
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '=') break;
                                                  iVar7 = 1;
                                                  set_gl_color(iStack_17cc);
                                                  if (iVar19 != 0) {
                                                    pmv2(afStack_17bc[0],afStack_17bc[1]);
                                                  }
                                                  pfVar5 = afStack_17bc;
                                                  if (1 < iVar19) {
                                                    do {
                                                      pfVar5 = pfVar5 + 2;
                                                      pdr2(*pfVar5,pfVar5[1]);
                                                      iVar7 = iVar7 + 1;
                                                    } while (iVar7 != iVar19);
                                                  }
                                                  iVar19 = 0;
                                                  pclos();
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '\x14') break;
                                                  iVar7 = 0;
                                                  set_gl_color(iStack_17cc);
                                                  bgnclosedline();
                                                  pfVar5 = afStack_17bc;
                                                  if (0 < iVar19) {
                                                    do {
                                                      v2f(pfVar5);
                                                      iVar7 = iVar7 + 1;
                                                      pfVar5 = pfVar5 + 2;
                                                    } while (iVar7 != iVar19);
                                                  }
                                                  iVar19 = 0;
                                                  endclosedline();
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '\x15') break;
                                                  iVar7 = 0;
                                                  set_gl_color(iStack_17cc);
                                                  bgnline();
                                                  pfVar5 = afStack_17bc;
                                                  if (0 < iVar19) {
                                                    do {
                                                      v2f(pfVar5);
                                                      iVar7 = iVar7 + 1;
                                                      pfVar5 = pfVar5 + 2;
                                                    } while (iVar7 != iVar19);
                                                  }
                                                  iVar19 = 0;
                                                  endline();
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '\x18') break;
                                                  iVar7 = 0;
                                                  set_gl_color(iStack_17cc);
                                                  bgnpoint();
                                                  pfVar5 = afStack_17bc;
                                                  if (0 < iVar19) {
                                                    do {
                                                      v2f(pfVar5);
                                                      iVar7 = iVar7 + 1;
                                                      pfVar5 = pfVar5 + 2;
                                                    } while (iVar7 != iVar19);
                                                  }
                                                  iVar19 = 0;
                                                  endpoint();
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                  }
                                                  if (cVar11 != '\x19') break;
                                                  iVar7 = 0;
                                                  set_gl_color(iStack_17cc);
                                                  bgnpolygon();
                                                  pfVar5 = afStack_17bc;
                                                  if (0 < iVar19) {
                                                    do {
                                                      v2f(pfVar5);
                                                      iVar7 = iVar7 + 1;
                                                      pfVar5 = pfVar5 + 2;
                                                    } while (iVar7 != iVar19);
                                                  }
                                                  iVar19 = 0;
                                                  endpolygon();
                                                  cVar11 = pcVar18[1];
                                                  pcVar18 = pcVar18 + 1;
                                                }
                                                if (cVar11 != '\x17') break;
                                                if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
                                                  fVar17 = ROUND(pfVar16[-1]);
                                                }
                                                else {
                                                  fVar17 = FLOOR(pfVar16[-1]);
                                                }
                                                __s1 = (char *)(int)fVar17;
                                                pfVar16 = pfVar16 + -1;
                                                iVar7 = 0;
                                                set_gl_color(iStack_17cc);
                                                bgnpolygon();
                                                pfVar5 = afStack_17bc;
                                                if (0 < iVar19) {
                                                  do {
                                                    v2f(pfVar5);
                                                    iVar7 = iVar7 + 1;
                                                    pfVar5 = pfVar5 + 2;
                                                  } while (iVar7 != iVar19);
                                                }
                                                iVar7 = 0;
                                                endpolygon();
                                                set_gl_color(__s1);
                                                bgnclosedline();
                                                pfVar5 = afStack_17bc;
                                                if (0 < iVar19) {
                                                  do {
                                                    v2f(pfVar5);
                                                    iVar7 = iVar7 + 1;
                                                    pfVar5 = pfVar5 + 2;
                                                  } while (iVar7 != iVar19);
                                                }
                                                iVar19 = 0;
                                                endclosedline();
                                                cVar11 = pcVar18[1];
                                                pcVar18 = pcVar18 + 1;
                                              }
                                              if (cVar11 != '\a') break;
                                              pfVar16 = pfVar16 + -1;
                                              if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
                                                fVar17 = ROUND(*pfVar16);
                                              }
                                              else {
                                                fVar17 = FLOOR(*pfVar16);
                                              }
                                              __s1 = (char *)(int)fVar17;
                                              iVar7 = 1;
                                              set_gl_color(iStack_17cc);
                                              if (iVar19 != 0) {
                                                pmv2(afStack_17bc[0],afStack_17bc[1]);
                                              }
                                              pfVar5 = afStack_17bc;
                                              if (1 < iVar19) {
                                                do {
                                                  pfVar5 = pfVar5 + 2;
                                                  pdr2(*pfVar5,pfVar5[1]);
                                                  iVar7 = iVar7 + 1;
                                                } while (iVar7 != iVar19);
                                              }
                                              iVar7 = 1;
                                              pclos();
                                              set_gl_color(__s1);
                                              if (iVar19 != 0) {
                                                move2(afStack_17bc[0],afStack_17bc[1]);
                                              }
                                              pfVar5 = afStack_17bc;
                                              if (1 < iVar19) {
                                                do {
                                                  pfVar5 = pfVar5 + 2;
                                                  draw2(*pfVar5,pfVar5[1]);
                                                  iVar7 = iVar7 + 1;
                                                } while (iVar7 != iVar19);
                                              }
                                              iVar19 = 0;
                                              draw2(afStack_17bc[0],afStack_17bc[1]);
                                              cVar11 = pcVar18[1];
                                              pcVar18 = pcVar18 + 1;
                                            }
                                            if (cVar11 != '\x04') break;
                                            fStack_fbc = pfVar16[-1];
                                            fStack_fb8 = pfVar16[-2];
                                            fStack_fb4 = pfVar16[-3];
                                            fVar12 = pfVar16[-4];
                                            fVar17 = pfVar16[-5];
                                            pfVar16 = pfVar16 + -5;
                                            set_gl_color(iStack_17cc);
                                            arc(fVar17,fVar12);
                                            cVar11 = pcVar18[1];
                                            pcVar18 = pcVar18 + 1;
                                          }
                                          if (cVar11 != '\x05') break;
                                          fStack_fbc = pfVar16[-1];
                                          fStack_fb8 = pfVar16[-2];
                                          fStack_fb4 = pfVar16[-3];
                                          fVar12 = pfVar16[-4];
                                          fVar17 = pfVar16[-5];
                                          pfVar16 = pfVar16 + -5;
                                          set_gl_color(iStack_17cc);
                                          arcf(fVar17,fVar12);
                                          cVar11 = pcVar18[1];
                                          pcVar18 = pcVar18 + 1;
                                        }
                                        if (cVar11 == '\x1a') {
                    // WARNING: Bad instruction - Truncating control flow here
                                          halt_baddata();
                                        }
                                        if (cVar11 == '\0') {
                    // WARNING: Bad instruction - Truncating control flow here
                                          halt_baddata();
                                        }
                                        if (cVar11 != '\x01') break;
                                        __s1 = (char *)pfVar16[-2];
                                        if ((__s1 == (char *)0x0) || (pfVar16[-1] == 0.0)) {
                                          pfVar16[-2] = 0.0;
                                        }
                                        else {
                                          pfVar16[-2] = 1.4013e-45;
                                        }
                                        pfVar16 = pfVar16 + -1;
                                        cVar11 = pcVar18[1];
                                        pcVar18 = pcVar18 + 1;
                                      }
                                      if (cVar11 == '8') {
                    // WARNING: Bad instruction - Truncating control flow here
                                        halt_baddata();
                                      }
                                      if (cVar11 != '9') break;
                                      __s1 = (char *)pfVar16[-2];
                                      if ((__s1 == (char *)0x0) && (pfVar16[-1] == 0.0)) {
                                        pfVar16[-2] = 0.0;
                                      }
                                      else {
                                        pfVar16[-2] = 1.4013e-45;
                                      }
                                      pfVar16 = pfVar16 + -1;
                                      cVar11 = pcVar18[1];
                                      pcVar18 = pcVar18 + 1;
                                    }
                                    if (cVar11 != 'B') break;
                                    cVar11 = pcVar18[1];
                                    pcVar18 = pcVar18 + 1;
                                    pfVar16 = pfVar16 + -1;
                                  }
                                  if (cVar11 != 'C') break;
                                  cVar11 = pcVar18[1];
                                  pcVar18 = pcVar18 + 1;
                                  pfVar16 = pfVar16 + -1;
                                }
                                if (cVar11 == '\b') {
                    // WARNING: Bad instruction - Truncating control flow here
                                  halt_baddata();
                                }
                                if (cVar11 != '\t') break;
                                if (pfVar16[-1] == 0.0) {
                                  pcStack_17d0 = *(char **)(pcVar18 + 1);
                                  pcVar18 = param_2 + (int)pcStack_17d0;
                                }
                                else {
                                  pcVar18 = pcVar18 + 5;
                                }
                                cVar11 = *pcVar18;
                              }
                              if (cVar11 == '\v') {
                    // WARNING: Bad instruction - Truncating control flow here
                                halt_baddata();
                              }
                              if (cVar11 != '\f') break;
                              if (pfVar16[-1] == 0.0) {
                                pcVar18 = pcVar18 + 5;
                              }
                              else {
                                pcStack_17d0 = *(char **)(pcVar18 + 1);
                                pcVar18 = param_2 + (int)pcStack_17d0;
                              }
                              cVar11 = *pcVar18;
                            }
                            if (cVar11 != '\r') break;
                            pcStack_17d0 = *(char **)(pcVar18 + 1);
                            cVar11 = param_2[(int)pcStack_17d0];
                            pcVar18 = param_2 + (int)pcStack_17d0;
                          }
                          if (cVar11 != '%') break;
                          cVar11 = pcVar18[1];
                          pcVar18 = pcVar18 + 1;
                        }
                        if (cVar11 != 'S') break;
                        pcStack_17d0 = *(char **)(pcVar18 + 1);
                        *(float *)(pcStack_17d0 + param_3) = pfVar16[-1];
                        cVar11 = pcVar18[5];
                        pcVar18 = pcVar18 + 5;
                      }
                      if (cVar11 != 'T') break;
                      pcStack_17d0 = *(char **)(pcVar18 + 1);
                      __s1 = (char *)pfVar16[-1];
                      *(char **)(pcStack_17d0 + param_3) = __s1;
                      cVar11 = pcVar18[5];
                      pcVar18 = pcVar18 + 5;
                    }
                    if (cVar11 != '+') break;
                    pcStack_17d0 = *(char **)(pcVar18 + 1);
                    *pfVar16 = *(float *)(pcStack_17d0 + param_3);
                    cVar11 = pcVar18[5];
                    pcVar18 = pcVar18 + 5;
                    pfVar16 = pfVar16 + 1;
                  }
                  if (cVar11 != ',') break;
                  pcStack_17d0 = *(char **)(pcVar18 + 1);
                  __s1 = *(char **)(pcStack_17d0 + param_3);
                  *pfVar16 = (float)__s1;
                  cVar11 = pcVar18[5];
                  pcVar18 = pcVar18 + 5;
                  pfVar16 = pfVar16 + 1;
                }
                if (cVar11 != ')') break;
                *(char *)pfVar16 = pcVar18[1];
                *(char *)((int)pfVar16 + 1) = pcVar18[2];
                *(char *)((int)pfVar16 + 2) = pcVar18[3];
                *(char *)((int)pfVar16 + 3) = pcVar18[4];
                cVar11 = pcVar18[5];
                pcVar18 = pcVar18 + 5;
                pfVar16 = pfVar16 + 1;
              }
              if (cVar11 != '*') break;
              pcStack_17d0 = *(char **)(pcVar18 + 1);
              *pfVar16 = (float)pcStack_17d0;
              cVar11 = pcVar18[5];
              __s1 = pcStack_17d0;
              pcVar18 = pcVar18 + 5;
              pfVar16 = pfVar16 + 1;
            }
            if (cVar11 != '^') break;
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
          }
          if (cVar11 != '\x1d') break;
          cVar11 = pcVar18[1];
          pcVar18 = pcVar18 + 1;
        }
        if (cVar11 != 'H') break;
        cVar11 = pcVar18[1];
        pcVar18 = pcVar18 + 1;
      }
      if (cVar11 != '\x06') break;
      pcVar18 = pcVar18 + 1;
      if (param_1[0x88] == 0.0) {
        if (param_1[0x8d] == 0.0) {
          __s1 = (char *)0x0;
        }
        else if ((int)param_1[0xb3] < 1) {
          __s1 = (char *)0x0;
        }
        else {
          pfStack_17e4 = param_1 + 8;
          __s1 = (char *)0x1;
          pfVar5 = (float *)((int)pfStack_17e4 + (int)param_1[0xb3]);
          for (; pfStack_17e4 != pfVar5; pfStack_17e4 = (float *)((int)pfStack_17e4 + 1)) {
            if (((uint)*pfStack_17e4 & 0x80000000) != 0) {
              __s1 = (char *)0x0;
              break;
            }
          }
        }
        param_1[0x88] = 1.4013e-45;
        param_1[0x89] = (float)__s1;
        *pfVar16 = (float)__s1;
        cVar11 = *pcVar18;
        pfVar16 = pfVar16 + 1;
      }
      else {
        *pfVar16 = param_1[0x89];
        cVar11 = *pcVar18;
        pfVar16 = pfVar16 + 1;
      }
    }
    if (cVar11 != '2') {
      if (cVar11 == 'K') {
        if (param_1[0x8c] == 0.0) {
          *pfVar16 = -NAN;
        }
        else {
          *pfVar16 = param_1[0x9d];
        }
        cVar11 = pcVar18[1];
        pcVar18 = pcVar18 + 1;
        pfVar16 = pfVar16 + 1;
      }
      else if (cVar11 == '(') {
        if (param_1[0x8c] == 0.0) {
          *pfVar16 = -NAN;
        }
        else {
          *pfVar16 = param_1[0x97];
        }
        cVar11 = pcVar18[1];
        pcVar18 = pcVar18 + 1;
        pfVar16 = pfVar16 + 1;
      }
      else {
        if (cVar11 == 'W') {
          pcVar18 = pcVar18 + 1;
          if (param_1[0x8d] == 0.0) {
            *pfVar16 = -NAN;
            cVar11 = *pcVar18;
            pfVar16 = pfVar16 + 1;
            goto joined_r0x00435ac4;
          }
          fVar17 = param_1[0xb3];
          if (0x47 < (int)fVar17) {
            iVar7 = getshort__FPc(param_1 + 8);
            if (iVar7 == 0x160) {
              pcVar9 = (char *)getshort__FPc(param_1 + 0xd);
              if (((pcVar9 != __s1) == 0x108) && (__s1 != (char *)0x10b)) {
                *pfVar16 = -NAN;
                cVar11 = *pcVar18;
                pfVar16 = pfVar16 + 1;
              }
              else if ((*(byte *)((int)param_1 + 0x32) & 0x80) == 0) {
                *pfVar16 = -NAN;
                cVar11 = *pcVar18;
                pfVar16 = pfVar16 + 1;
              }
              else if (((uint)param_1[0x96] & 0x49) == 0) {
                *pfVar16 = -NAN;
                cVar11 = *pcVar18;
                pfVar16 = pfVar16 + 1;
              }
              else {
                fVar17 = (float)getlong__FPc(param_1 + 0x19);
                *pfVar16 = fVar17;
                cVar11 = *pcVar18;
                pfVar16 = pfVar16 + 1;
              }
              goto joined_r0x00435ac4;
            }
            fVar17 = param_1[0xb3];
          }
          if ((int)fVar17 < 0xd) {
            *pfVar16 = -NAN;
            cVar11 = *pcVar18;
            pfVar16 = pfVar16 + 1;
          }
          else if ((*(char *)(param_1 + 8) == '#') && (*(char *)((int)param_1 + 0x21) == '!')) {
            iVar7 = 3;
            if (3 < (int)fVar17) {
              iVar8 = (int)param_1 + 3;
              do {
                if (*(char *)(iVar8 + 0x20) == '\n') break;
                iVar7 = iVar7 + 1;
                iVar8 = iVar8 + 1;
              } while (iVar7 < (int)fVar17);
            }
            if (iVar7 < (int)fVar17) {
              if ((int)fVar17 - iVar7 < 7) {
                *pfVar16 = -NAN;
                cVar11 = *pcVar18;
                pfVar16 = pfVar16 + 1;
              }
              else {
                iVar8 = strncmp((char *)((int)param_1 + iVar7 + 0x21),s__Tag_10009d38,5);
                if (iVar8 == 0) {
                  __s1 = (char *)strtol((char *)((int)param_1 + iVar7 + 0x26),(char **)&pfStack_17e4
                                        ,0);
                  if ((pfStack_17e4 == (float *)0x0) || (*(byte *)pfStack_17e4 != 10)) {
                    *pfVar16 = -NAN;
                    cVar11 = *pcVar18;
                    pfVar16 = pfVar16 + 1;
                  }
                  else if (((uint)param_1[0x96] & 0x49) == 0) {
                    *pfVar16 = -NAN;
                    cVar11 = *pcVar18;
                    pfVar16 = pfVar16 + 1;
                  }
                  else {
                    *pfVar16 = (float)__s1;
                    cVar11 = *pcVar18;
                    pfVar16 = pfVar16 + 1;
                  }
                }
                else {
                  *pfVar16 = -NAN;
                  cVar11 = *pcVar18;
                  pfVar16 = pfVar16 + 1;
                }
              }
            }
            else {
              *pfVar16 = -NAN;
              cVar11 = *pcVar18;
              pfVar16 = pfVar16 + 1;
            }
          }
          else {
            *pfVar16 = -NAN;
            cVar11 = *pcVar18;
            pfVar16 = pfVar16 + 1;
          }
          goto joined_r0x00435ac4;
        }
        if (cVar11 == '\x0e') {
          __s1 = (char *)pfVar16[-1];
          pcVar18 = pcVar18 + 1;
          if ((int)__s1 < 0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8f] == 0.0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8d] == 0.0) {
            iVar7 = parse_typed_value(param_1[0x8e],__s1,&bStack_17d1,1);
            fVar17 = (float)(uint)bStack_17d1;
            if (iVar7 != 0) {
              fVar17 = -NAN;
            }
          }
          else if ((char *)param_1[0xb3] < __s1 + 1) {
            if ((char *)param_1[0xb3] == (char *)0x200) {
              iVar7 = parse_typed_value(param_1[0x8e],__s1,&bStack_17d1,1);
              fVar17 = (float)(uint)bStack_17d1;
              if (iVar7 != 0) {
                fVar17 = -NAN;
              }
            }
            else {
              fVar17 = -NAN;
            }
          }
          else {
            fVar17 = (float)(uint)(byte)((char *)((int)param_1 + (int)__s1))[0x20];
          }
          pfVar16[-1] = fVar17;
          cVar11 = *pcVar18;
        }
        else if (cVar11 == 'J') {
          __s1 = (char *)pfVar16[-1];
          pcVar18 = pcVar18 + 1;
          if ((int)__s1 < 0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8f] == 0.0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8d] == 0.0) {
            iVar7 = parse_typed_value(param_1[0x8e],__s1,&sStack_17d4,2);
            fVar17 = (float)(int)sStack_17d4;
            if (iVar7 != 0) {
              fVar17 = -NAN;
            }
          }
          else if ((char *)param_1[0xb3] < __s1 + 2) {
            if ((char *)param_1[0xb3] == (char *)0x200) {
              iVar7 = parse_typed_value(param_1[0x8e],__s1,&sStack_17d4,2);
              fVar17 = (float)(int)sStack_17d4;
              if (iVar7 != 0) {
                fVar17 = -NAN;
              }
            }
            else {
              fVar17 = -NAN;
            }
          }
          else {
            fVar17 = (float)getshort__FPc((char *)((int)param_1 + (int)__s1) + 0x20);
            sStack_17d4 = SUB42(fVar17,0);
          }
          pfVar16[-1] = fVar17;
          cVar11 = *pcVar18;
        }
        else if (cVar11 == '-') {
          __s1 = (char *)pfVar16[-1];
          pcVar18 = pcVar18 + 1;
          if ((int)__s1 < 0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8f] == 0.0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8d] == 0.0) {
            iVar7 = parse_typed_value(param_1[0x8e],__s1,&fStack_17d8,4);
            fVar17 = fStack_17d8;
            if (iVar7 != 0) {
              fVar17 = -NAN;
            }
          }
          else if ((char *)param_1[0xb3] < __s1 + 4) {
            if ((char *)param_1[0xb3] == (char *)0x200) {
              iVar7 = parse_typed_value(param_1[0x8e],__s1,&fStack_17d8,4);
              fVar17 = fStack_17d8;
              if (iVar7 != 0) {
                fVar17 = -NAN;
              }
            }
            else {
              fVar17 = -NAN;
            }
          }
          else {
            fStack_17d8 = (float)getlong__FPc((char *)((int)param_1 + (int)__s1) + 0x20);
            fVar17 = fStack_17d8;
          }
          pfVar16[-1] = fVar17;
          cVar11 = *pcVar18;
        }
        else if (cVar11 == 'Z') {
          __s1 = (char *)pfVar16[-1];
          pcVar18 = pcVar18 + 1;
          if (param_1[0x8f] == 0.0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8d] == 0.0) {
            iVar7 = parse_typed_value(param_1[0x8e],__s1,&bStack_17d9,1);
            fVar17 = (float)(uint)bStack_17d9;
            if (iVar7 != 0) {
              fVar17 = -NAN;
            }
          }
          else if ((char *)param_1[0xb3] < __s1 + 1) {
            if ((char *)param_1[0xb3] == (char *)0x200) {
              iVar7 = parse_typed_value(param_1[0x8e],__s1,&bStack_17d9,1);
              fVar17 = (float)(uint)bStack_17d9;
              if (iVar7 != 0) {
                fVar17 = -NAN;
              }
            }
            else {
              fVar17 = -NAN;
            }
          }
          else {
            fVar17 = (float)(uint)(byte)((char *)((int)param_1 + (int)__s1))[0x20];
          }
          pfVar16[-1] = fVar17;
          cVar11 = *pcVar18;
        }
        else if (cVar11 == '\\') {
          __s1 = (char *)pfVar16[-1];
          pcVar18 = pcVar18 + 1;
          if ((int)__s1 < 0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8f] == 0.0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8d] == 0.0) {
            iVar7 = parse_typed_value(param_1[0x8e],__s1,&uStack_17dc,2);
            if (iVar7 == 0) {
              fVar17 = (float)(uint)uStack_17dc;
            }
            else {
              fVar17 = -NAN;
            }
          }
          else if ((char *)param_1[0xb3] < __s1 + 2) {
            if ((char *)param_1[0xb3] == (char *)0x200) {
              iVar7 = parse_typed_value(param_1[0x8e],__s1,&uStack_17dc,2);
              if (iVar7 == 0) {
                fVar17 = (float)(uint)uStack_17dc;
              }
              else {
                fVar17 = -NAN;
              }
            }
            else {
              fVar17 = -NAN;
            }
          }
          else {
            uStack_17dc = getshort__FPc((char *)((int)param_1 + (int)__s1) + 0x20);
            fVar17 = (float)(uint)uStack_17dc;
          }
          pfVar16[-1] = fVar17;
          cVar11 = *pcVar18;
        }
        else if (cVar11 == '[') {
          __s1 = (char *)pfVar16[-1];
          pcVar18 = pcVar18 + 1;
          if ((int)__s1 < 0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8f] == 0.0) {
            fVar17 = -NAN;
          }
          else if (param_1[0x8d] == 0.0) {
            iVar7 = parse_typed_value(param_1[0x8e],__s1,&fStack_17e0,4);
            fVar17 = fStack_17e0;
            if (iVar7 != 0) {
              fVar17 = -NAN;
            }
          }
          else if ((char *)param_1[0xb3] < __s1 + 4) {
            if ((char *)param_1[0xb3] == (char *)0x200) {
              iVar7 = parse_typed_value(param_1[0x8e],__s1,&fStack_17e0,4);
              fVar17 = fStack_17e0;
              if (iVar7 != 0) {
                fVar17 = -NAN;
              }
            }
            else {
              fVar17 = -NAN;
            }
          }
          else {
            fStack_17e0 = (float)getlong__FPc((char *)((int)param_1 + (int)__s1) + 0x20);
            fVar17 = fStack_17e0;
          }
          pfVar16[-1] = fVar17;
          cVar11 = *pcVar18;
        }
        else if (cVar11 == 'G') {
          piVar1 = (int *)(pcVar18 + 1);
          pcVar18 = pcVar18 + 5;
          pcStack_17d0 = (char *)*piVar1;
          sVar6 = strlen(pcStack_17d0 + param_4);
          __s1 = (char *)__nw__FUi();
          bcopy(pcStack_17d0 + param_4,__s1,sVar6 + 1);
          *pfVar16 = (float)__s1;
          cVar11 = *pcVar18;
          pfVar16 = pfVar16 + 1;
        }
        else {
          if (cVar11 == '\x16') {
            halt_baddata();
          }
          if (cVar11 == '\x1e') {
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
          }
          else if (cVar11 == 'U') {
            pcVar9 = (char *)pfVar16[-1];
            __s1 = (char *)pfVar16[-2];
            iVar7 = strcmp(__s1,pcVar9);
            pfVar16[-2] = (float)(uint)(iVar7 == 0);
            __dl__FPv(__s1);
            __dl__FPv(pcVar9);
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + -1;
          }
          else if (cVar11 == '\x12') {
            __s1 = (char *)pfVar16[-1];
            pfVar5 = pfVar16 + -1;
            sVar6 = strlen((char *)param_1[0x8a]);
            __n = strlen(__s1);
            if ((int)(__n + sVar6 + 1) < 0xff) {
              bcopy((void *)param_1[0x8a],acStack_18f4,sVar6);
              acStack_18f4[sVar6] = '/';
              bcopy(__s1,acStack_18f4 + sVar6 + 1,__n);
              (acStack_18f4 + sVar6)[__n + 1] = '\0';
              iVar7 = stat(acStack_18f4,&sStack_197c);
              __dl__FPv(__s1);
              if (iVar7 == 0) {
                *pfVar5 = 1.4013e-45;
              }
              else {
                *pfVar5 = 0.0;
              }
            }
            else {
              __dl__FPv(__s1);
              *pfVar5 = 0.0;
            }
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
          }
          else if (cVar11 == 'V') {
            fVar17 = pfVar16[-1];
            __s1 = (char *)pfVar16[-2];
            pfVar5 = pfVar16 + -2;
            if (((param_1[0x8f] == 0.0) || ((int)__s1 < 0)) || ((int)fVar17 < 0)) {
              pfStack_17e4 = (float *)__nw__FUi(1);
              *(byte *)pfStack_17e4 = 0;
              *pfVar5 = (float)pfStack_17e4;
            }
            else if (param_1[0x8d] == 0.0) {
              lseek((int)param_1[0x8e],(__off_t)__s1,0);
              pfStack_17e4 = (float *)__nw__FUi((int)fVar17 + 1);
              read((int)param_1[0x8e],pfStack_17e4,(size_t)fVar17);
              *(byte *)((int)pfStack_17e4 + (int)fVar17) = 0;
              *pfVar5 = (float)pfStack_17e4;
            }
            else if ((int)param_1[0xb3] < (int)(__s1 + (int)fVar17)) {
              if (param_1[0xb3] == 7.17465e-43) {
                lseek((int)param_1[0x8e],(__off_t)__s1,0);
                pfStack_17e4 = (float *)__nw__FUi((int)fVar17 + 1);
                read((int)param_1[0x8e],pfStack_17e4,(size_t)fVar17);
                *(byte *)((int)pfStack_17e4 + (int)fVar17) = 0;
                *pfVar5 = (float)pfStack_17e4;
              }
              else {
                pfStack_17e4 = (float *)__nw__FUi(1);
                *(byte *)pfStack_17e4 = 0;
                *pfVar5 = (float)pfStack_17e4;
              }
            }
            else {
              fVar12 = 0.0;
              pfStack_17e4 = (float *)__nw__FUi((int)fVar17 + 1);
              if (0 < (int)fVar17) {
                if ((float)((uint)fVar17 & 3) != 0.0) {
                  pcVar9 = (char *)((int)param_1 + (int)__s1);
                  do {
                    pbVar2 = (byte *)(pcVar9 + 0x20);
                    pbVar10 = (byte *)((int)pfStack_17e4 + (int)fVar12);
                    fVar12 = (float)((int)fVar12 + 1);
                    pcVar9 = pcVar9 + 1;
                    *pbVar10 = *pbVar2;
                  } while ((float)((uint)fVar17 & 3) != fVar12);
                  if (fVar12 == fVar17) goto LAB_00437ddc;
                }
                pcVar9 = (char *)((int)param_1 + (int)__s1) + (int)fVar12;
                fVar13 = fVar12;
                do {
                  *(char *)((int)pfStack_17e4 + (int)fVar13) = pcVar9[0x20];
                  *(char *)((int)pfStack_17e4 + (int)fVar13 + 1U) = pcVar9[0x21];
                  *(char *)((int)pfStack_17e4 + (int)fVar13 + 2U) = pcVar9[0x22];
                  pbVar2 = (byte *)(pcVar9 + 0x23);
                  fVar12 = (float)((int)fVar13 + 4);
                  pcVar9 = pcVar9 + 4;
                  *(byte *)((int)pfStack_17e4 + (int)fVar13 + 3U) = *pbVar2;
                  fVar13 = fVar12;
                } while (fVar12 != fVar17);
              }
LAB_00437ddc:
              *(byte *)((int)pfStack_17e4 + (int)fVar12) = 0;
              *pfVar5 = (float)pfStack_17e4;
            }
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + -1;
          }
          else if (cVar11 == '!') {
            fVar17 = pfVar16[-1];
            __s1 = (char *)FUN_004382f4(param_1[0x8b],fVar17);
            pfVar16[-1] = (float)__s1;
            __dl__FPv(fVar17);
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
          }
          else if (cVar11 == 'Q') {
            *pfVar16 = *param_1;
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == 'O') {
            *pfVar16 = param_1[1];
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == 'P') {
            *pfVar16 = param_1[2];
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == 'R') {
            *pfVar16 = param_1[3];
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == 'N') {
            *pfVar16 = param_1[4];
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == 'I') {
            *pfVar16 = param_1[5];
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == '$') {
            *pfVar16 = param_1[6];
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == '<') {
            *pfVar16 = param_1[7];
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + 1;
          }
          else if (cVar11 == 'D') {
            printf(&DAT_10009d2c);
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + -1;
          }
          else if (cVar11 == 'E') {
            __s1 = (char *)pfVar16[-1];
            printf(&DAT_10009d30,__s1);
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + -1;
          }
          else if (cVar11 == 'F') {
            __s1 = (char *)pfVar16[-1];
            printf(&DAT_10009d34,__s1);
            __dl__FPv(__s1);
            cVar11 = pcVar18[1];
            pcVar18 = pcVar18 + 1;
            pfVar16 = pfVar16 + -1;
          }
        }
      }
      goto joined_r0x00435ac4;
    }
    if (param_1[0x8c] == 0.0) {
      *pfVar16 = -NAN;
    }
    else {
      *pfVar16 = param_1[0x96];
    }
    cVar11 = pcVar18[1];
    pcVar18 = pcVar18 + 1;
    pfVar16 = pfVar16 + 1;
  } while( true );
}

void FindInfoByName__14ByteCodeLoaderFPc(int *param_1)

{
  int iVar1;
  int iVar2;
  
  iVar2 = *param_1;
  FUN_004357ec(&TheFileIconInterpreter);
  while( true ) {
    if (iVar2 == 0) {
      FUN_00435938(&TheFileIconInterpreter);
                    // WARNING: Bad instruction - Truncating control flow here
      halt_baddata();
    }
    if ((((*(int *)(iVar2 + 4) != 0) && (DAT_10009c90 == *(int *)(iVar2 + 0x34))) &&
        (DAT_10009c80 != 0)) &&
       (iVar1 = FUN_00435a28(&TheFileIconInterpreter,*(int *)(iVar2 + 4),*(undefined4 *)(iVar2 + 8),
                             *(undefined4 *)(iVar2 + 0x10)), iVar1 != 0)) break;
    iVar2 = *(int *)(iVar2 + 0x68);
  }
  FUN_00435938(&TheFileIconInterpreter);
  halt_baddata();
}

void isSuperByName__14ByteCodeLoaderFPcT1(undefined4 param_1,char *param_2,undefined4 param_3)

{
  int iVar1;
  undefined4 *puVar2;
  
  iVar1 = FUN_00434be4(param_1,param_3);
  if (iVar1 != 0) {
    puVar2 = *(undefined4 **)(iVar1 + 0x30);
    while ((puVar2 != (undefined4 *)0x0 && (iVar1 = strcmp(param_2,(char *)*puVar2), iVar1 != 0))) {
      puVar2 = (undefined4 *)puVar2[1];
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void UnSetFile__19FileIconInterpreterFv(int param_1)

{
  if (*(int *)(param_1 + 0x23c) != 0) {
    close(*(int *)(param_1 + 0x238));
  }
  *(undefined4 *)(param_1 + 0x228) = 0;
  *(undefined4 *)(param_1 + 0x22c) = 0;
  *(undefined4 *)(param_1 + 0x23c) = 0;
  *(undefined4 *)(param_1 + 0x230) = 0;
  *(undefined4 *)(param_1 + 0x240) = 0;
  *(undefined4 *)(param_1 + 0x234) = 0;
  *(undefined4 *)(param_1 + 0x220) = 0;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FindIconByType__14ByteCodeLoaderFPc(int *param_1,char *param_2)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = (undefined4 *)*param_1;
  while( true ) {
    if (puVar2 == (undefined4 *)0x0) {
                    // WARNING: Bad instruction - Truncating control flow here
      halt_baddata();
    }
    iVar1 = strcmp(param_2,(char *)*puVar2);
    if (iVar1 == 0) break;
    puVar2 = (undefined4 *)puVar2[0x1a];
  }
  FUN_00435034(0,puVar2);
  halt_baddata();
}
