// init.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/init.h"

void init_color_menus(void)

{
  undefined4 local_c;
  undefined4 local_8;
  
  local_c = 0xe3f48f1;
  local_8 = 1;
  if (displayHeight == 0) {
    XtSetValues(file_height_none_toggle,&local_c,1);
    XtSetSensitive(dir_height_menu_button,0);
  }
  else if (displayHeight == 1) {
    XtSetValues(file_height_linear_toggle,&local_c,1);
  }
  else if (displayHeight == 2) {
    XtSetValues(file_height_exag_toggle,&local_c,1);
  }
  if (displayDirectoryHeight == 0) {
    XtSetValues(dir_flat_toggle,&local_c,1);
  }
  else if (displayDirectoryHeight == 1) {
    XtSetValues(dir_files_only_toggle,&local_c,1);
  }
  else if (displayDirectoryHeight == 2) {
    XtSetValues(dir_children_toggle,&local_c,1);
  }
  if (altcontext[0xc51] != '\0') {
    XtSetValues(autoscan_split_toggle,&local_c,1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void get_panel_value(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 local_78;
  undefined4 local_74;
  undefined4 local_70;
  undefined4 local_24;
  undefined4 local_20;
  undefined4 local_1c;
  undefined4 local_18;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_c;
  undefined4 local_8;
  undefined4 local_4;
  
  local_78 = 0;
  local_4 = XmCreateMenuBar(param_1,"menuBar",&local_74,0);
  XtManageChild(local_4);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_c = XmCreatePulldownMenu(local_4,"session_pane",&local_74,local_78);
  XtAddCallback(local_c,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(local_c,0xe3f4c38,overlayMenuUnmappedCB,0);
  install_help_callback(local_c,&sessionHelp);
  local_78 = 0;
  autoscan_split_toggle = XmCreateToggleButton(local_c,"menuSplit",&local_74,0);
  XtManageChild(autoscan_split_toggle);
  XtAddCallback(autoscan_split_toggle,0xe3f4ca5,autoscan_toggle_callback,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_c,"menuRescan",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,rescanDatabase,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_c,"menuSave",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,dumpDatabaseCB,0);
  configure_context_widget(local_c);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_c,"menuQuit",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,quit_application,0);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_c;
  local_8 = XmCreateCascadeButton(local_4,"menuSession",&local_74,1);
  XtManageChild(local_8);
  install_help_callback(local_8,&sessionHelp);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_14 = XmCreatePulldownMenu(local_4,"show_pane",&local_74,local_78);
  XtAddCallback(local_14,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(local_14,0xe3f4c38,overlayMenuUnmappedCB,0);
  XtManageChild(local_14);
  install_help_callback(local_14,&showHelp);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuOverview",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,showOverview,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuControls",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,show_controls,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuLegend",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,toggle_legend,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_14,"menuPreferences",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,showPreferencePanel,0);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_18 = XmCreatePulldownMenu(local_14,"hide_pane",&local_74,local_78);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuOverview",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,hideOverview,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuControls",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,init_panel_layout,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuLegend",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,controls_button_callback,0);
  local_78 = 0;
  local_24 = XmCreatePushButton(local_18,"menuPreferences",&local_74,0);
  XtManageChild(local_24);
  XtAddCallback(local_24,0xe3f35b3,hidePreferencePanel,0);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_18;
  uVar1 = XmCreateCascadeButton(local_14,"menuHide",&local_74,1);
  XtManageChild(uVar1);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_14;
  local_8 = XmCreateCascadeButton(local_4,"menuShow",&local_74,1);
  XtManageChild(local_8);
  install_help_callback(local_8,&showHelp);
  local_78 = 0;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_10 = XmCreatePulldownMenu(local_4,"display_pane",&local_74,local_78);
  XtAddCallback(local_10,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(local_10,0xe3f4c38,overlayMenuUnmappedCB,0);
  XtManageChild(local_10);
  install_help_callback(local_10,&displayHelp);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_70 = local_10;
  local_8 = XmCreateCascadeButton(local_4,"menuDisplay",&local_74,1);
  XtManageChild(local_8);
  install_help_callback(local_8,&displayHelp);
  local_70 = 1;
  local_74 = 0xe3f464e;
  local_78 = 1;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_70 = XmCreatePulldownMenu(local_10,"dheight_pane",&local_74,local_78);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_1c = local_70;
  uVar1 = XmCreateCascadeButton(local_10,"menuHeight",&local_74,1);
  XtManageChild(uVar1);
  local_78 = 0;
  file_height_none_toggle = XmCreateToggleButton(local_1c,"menuHeightNone",&local_74,0);
  XtManageChild(file_height_none_toggle);
  XtAddCallback(file_height_none_toggle,0xe3f4ca5,file_height_mode_callback,0);
  local_78 = 0;
  file_height_linear_toggle = XmCreateToggleButton(local_1c,"menuHeightLinear",&local_74,0);
  XtManageChild(file_height_linear_toggle);
  XtAddCallback(file_height_linear_toggle,0xe3f4ca5,file_height_mode_callback,1);
  local_78 = 0;
  file_height_exag_toggle = XmCreateToggleButton(local_1c,"menuHeightExaggerated",&local_74,0);
  XtManageChild(file_height_exag_toggle);
  XtAddCallback(file_height_exag_toggle,0xe3f4ca5,file_height_mode_callback,2);
  local_74 = 0xe3f464e;
  local_78 = 1;
  local_70 = 1;
  setup_menu_resources(display,0,&local_74,&local_78);
  local_70 = XmCreatePulldownMenu(local_10,"ddir_pane",&local_74,local_78);
  local_74 = 0xe3f4a31;
  local_78 = 1;
  local_20 = local_70;
  dir_height_menu_button = XmCreateCascadeButton(local_10,"menuDirectoryHeight",&local_74,1);
  XtManageChild(dir_height_menu_button);
  local_78 = 0;
  dir_flat_toggle = XmCreateToggleButton(local_20,"menuDirectoryFlat",&local_74,0);
  XtManageChild(dir_flat_toggle);
  XtAddCallback(dir_flat_toggle,0xe3f4ca5,dir_height_mode_callback,0);
  local_78 = 0;
  dir_files_only_toggle = XmCreateToggleButton(local_20,"menuDirectoryFilesOnly",&local_74,0);
  XtManageChild(dir_files_only_toggle);
  XtAddCallback(dir_files_only_toggle,0xe3f4ca5,dir_height_mode_callback,1);
  local_78 = 0;
  dir_children_toggle = XmCreateToggleButton(local_20,"menuDirectoryChildren",&local_74,0);
  XtManageChild(dir_children_toggle);
  XtAddCallback(dir_children_toggle,0xe3f4ca5,dir_height_mode_callback,2);
  init_context_menus(local_4,param_1);
  finalize_menu_setup(local_4);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_context_windows(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  int unaff_gp;
  
  puVar2 = (undefined4 *)**(undefined4 **)(unaff_gp + -0x7684);
  puVar1 = (undefined4 *)**(undefined4 **)(unaff_gp + -0x7680);
  puVar3 = puVar2;
  do {
    puVar4 = puVar3 + 3;
    *puVar1 = *puVar3;
    puVar1[1] = puVar3[1];
    puVar1[2] = puVar3[2];
    puVar1 = puVar1 + 3;
    puVar3 = puVar4;
  } while (puVar4 != puVar2 + 0x315);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void add_directory_monitor(int param_1)

{
  undefined4 uVar1;
  int unaff_gp;
  
  if ((**(char **)(unaff_gp + -0x75dc) == '\0') && (-1 < *(int *)(param_1 + 0x74) << 10)) {
    uVar1 = (**(code **)(unaff_gp + -0x7a84))(0,param_1);
    (**(code **)(unaff_gp + -0x7718))(*(int *)(unaff_gp + -0x7f94) + 0x6c70,uVar1,param_1 + 0x60);
    *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) | 0x20;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void flush_rendering(int param_1)

{
  int unaff_gp;
  
  if ((**(char **)(unaff_gp + -0x75dc) == '\0') && (*(int *)(param_1 + 0x74) << 10 < 0)) {
    (**(code **)(unaff_gp + -0x7a84))(0,param_1);
    (**(code **)(unaff_gp + -0x7714))(*(int *)(unaff_gp + -0x7f94) + 0x6c70,param_1 + 0x60);
    *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) & 0xdf;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_camera_state(void)

{
  int unaff_gp;
  undefined4 uVar1;
  undefined4 in_register_00001040;
  float fVar2;
  undefined4 in_register_00001080;
  
  fVar2 = (float)(((double)(int)*(short *)(**(int **)(unaff_gp + -0x7684) + 0xe) /
                  (double)CONCAT44(in_register_00001040,
                                   *(undefined4 *)(*(int *)(unaff_gp + -0x7fa4) + -0x58d4))) *
                 (double)CONCAT44(in_register_00001080,
                                  *(undefined4 *)(*(int *)(unaff_gp + -0x7fa4) + -0x58cc)));
  uVar1 = (**(code **)(unaff_gp + -0x7ca4))();
  *(undefined4 *)(**(int **)(unaff_gp + -0x7684) + 0x20) = uVar1;
  uVar1 = (**(code **)(unaff_gp + -0x7ca0))(fVar2);
  *(undefined4 *)(**(int **)(unaff_gp + -0x7684) + 0x24) = uVar1;
  uVar1 = (**(code **)(unaff_gp + -0x7c90))(fVar2);
  *(undefined4 *)(**(int **)(unaff_gp + -0x7684) + 0x28) = uVar1;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void initResources(undefined4 param_1)

{
  int iVar1;
  undefined4 uVar2;
  
  XtAppAddConverter(app_context,0xf661c25,"CpColor",cp_color_converter,0,0);
  XtGetApplicationResources(param_1,&landscape_name,&PTR_s_landscape_10008918,1,0,0);
  if (landscape_name == (char *)0x0) {
    iVar1 = getgdesc(9);
    if (iVar1 < 4) {
      landscape_name = "indigo";
    }
    else {
      landscape_name = "grass";
    }
  }
  if (landscape_name == (char *)0x0) {
    XtGetApplicationResources(param_1,&fsn_resources,&PTR_s_noscan_10007c30,0x76,0,0);
  }
  else {
    uVar2 = XtCreateWidget(landscape_name,applicationShellWidgetClass,param_1,0,0);
    XtGetApplicationResources(uVar2,&fsn_resources,&PTR_s_noscan_10007c30,0x76,0,0);
    XtDestroyWidget(uVar2);
  }
  init_icon_resources(param_1,&icon_resource_1,&icon_resource_2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createHelpMenu(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uStack_2c;
  undefined4 uStack_28;
  undefined4 uStack_24;
  
  uStack_2c = 0;
  setup_menu_resources(display,0,&uStack_28,&uStack_2c);
  uVar1 = XmCreatePulldownMenu(param_1,"help_menu",&uStack_28,uStack_2c);
  XtAddCallback(uVar1,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(uVar1,0xe3f4c38,overlayMenuUnmappedCB,0);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"window_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,help_callback,&topHelp);
  XtManageChild(uVar2);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"context_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,quit_menu_callback,0);
  XtManageChild(uVar2);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"mode_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,help_callback,&modeHelp);
  XtManageChild(uVar2);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"version_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,help_callback,&versionHelp);
  XtManageChild(uVar2);
  uStack_28 = 0xe3f4a31;
  uStack_2c = 1;
  uStack_24 = uVar1;
  uVar1 = XmCreateCascadeButton(param_1,"helpButton",&uStack_28,1);
  XtManageChild(uVar1);
  uStack_2c = 1;
  uStack_28 = 0xe3f429f;
  uStack_24 = uVar1;
  XtSetValues(param_1,&uStack_28,1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_panel_layout(void)

{
  undefined4 local_50;
  undefined4 local_4c;
  
  local_50 = 0xe3f40cb;
  local_4c = 1;
  controlsShowing = 0;
  XtSetValues(panel_vsep_widget,&local_50,1);
  XtUnmanageChild(copy_button_widget);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamMonitor(void)

{
  if ((fsn_resources == '\0') && (database_loaded_flag == 0)) {
    database_loaded_flag = XtAppAddInput(app_context,database_root_node,1,database_input_handler,0);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setup_fam_monitoring(void)

{
  undefined4 uVar1;
  int unaff_gp;
  
  if ((**(char **)(unaff_gp + -0x75dc) == '\0') &&
     (*(int *)(*(int *)(unaff_gp + -0x7f98) + 0x78b0) == 0)) {
    uVar1 = (**(code **)(unaff_gp + -0x7f30))
                      (**(undefined4 **)(unaff_gp + -0x7600),
                       *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c70),1,
                       *(int *)(unaff_gp + -0x7fe0) + -0x7fbc,0);
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x78b0) = uVar1;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setup_context_widgets(void)

{
  undefined4 uVar1;
  int iVar2;
  char *pcVar3;
  undefined4 local_a0;
  undefined4 local_9c;
  undefined4 local_98;
  undefined4 local_94;
  undefined4 local_90;
  undefined4 local_8c;
  undefined4 local_88;
  undefined4 local_84;
  undefined4 local_80;
  undefined4 local_7c;
  char *local_78;
  undefined4 local_74;
  char *local_70;
  undefined4 *local_6c;
  undefined4 local_68;
  undefined4 local_64;
  
  uVar1 = XtCreateWidget("contextTopWidget",xmFormWidgetClass,context_top_widget,&local_a0,0);
  *(undefined4 *)(curcontextwindows + 0xc) = uVar1;
  install_help_callback(*(undefined4 *)(curcontextwindows + 0xc),&infoHelp);
  local_9c = 1;
  local_a0 = 0xe3f4b1d;
  local_98 = 0xe3f40cb;
  local_90 = 0xe3f46dd;
  local_94 = 1;
  local_8c = 1;
  local_94 = create_context_widget(*(undefined4 *)(curcontextwindows + 0xc),&local_a0,3);
  local_8c = 1;
  local_a0 = 0xe3f4b1d;
  local_98 = 0xe3f4ba9;
  local_90 = 0xe3f40cb;
  local_88 = 0xe3f46dd;
  local_9c = 3;
  local_84 = 1;
  local_94 = XtCreateManagedWidget
                       ("panelhsep",xmSeparatorWidgetClass,*(undefined4 *)(curcontextwindows + 0xc),&local_a0
                        ,4);
  local_7c = blankXmString;
  local_a0 = 0xe3f4b1d;
  local_98 = 0xe3f4ba9;
  local_90 = 0xe3f40cb;
  local_88 = 0xe3f46dd;
  local_80 = 0xe3f40b5;
  local_9c = 3;
  local_8c = 1;
  local_84 = 1;
  uVar1 = 5;
  if (context_count != 0) {
    local_74 = cached_context_ptr;
    local_78 = (char *)0xf6615f6;
    local_6c = (undefined4 *)lhLabelColor;
    local_70 = (char *)0xf661554;
    uVar1 = 7;
  }
  uVar1 = XtCreateManagedWidget
                    ("locateHighlightName",xmLabelWidgetClass,*(undefined4 *)(curcontextwindows + 0xc),
                     &local_a0,uVar1);
  *(undefined4 *)(curcontextwindows + 0x2c) = uVar1;
  local_a0 = 0xe3f4b1d;
  local_98 = 0xe3f4ba9;
  local_9c = 3;
  local_94 = *(undefined4 *)(curcontextwindows + 0x2c);
  local_84 = 1;
  local_90 = 0xe3f3701;
  local_88 = 0xe3f40cb;
  local_80 = 0xe3f46dd;
  local_8c = 1;
  local_7c = 1;
  iVar2 = init_display_mode();
  if (iVar2 == 0) {
    local_78 = "useOverlay";
  }
  else {
    local_78 = "usePopup";
  }
  local_74 = 1;
  local_70 = "glxConfig";
  local_6c = &display_mode_flags;
  uVar1 = XtCreateManagedWidget
                    ("glwidget",glxMDrawWidgetClass,*(undefined4 *)(curcontextwindows + 0xc),&local_a0,7);
  *(undefined4 *)(curcontextwindows + 8) = uVar1;
  XtAddCallback(*(undefined4 *)(curcontextwindows + 8),"exposeCallback",glwidget_expose_callback,0);
  iVar2 = init_display_mode();
  if (iVar2 == 0) {
    pcVar3 = "overlayExposeWindow";
  }
  else {
    pcVar3 = "popupExposeWindow";
  }
  XtAddCallback(*(undefined4 *)(curcontextwindows + 8),pcVar3,gl_input_callback,0);
  XtAddCallback(*(undefined4 *)(curcontextwindows + 8),"resizeCallback",glwidget_resize_callback,0);
  XtAddCallback(*(undefined4 *)(curcontextwindows + 8),"ginitCallback",glwidget_init_callback,0);
  XtOverrideTranslations(*(undefined4 *)(curcontextwindows + 8),glwidget_translations);
  install_help_callback(*(undefined4 *)(curcontextwindows + 8),&glHelp);
  local_a0 = 0xe3f4b1d;
  local_98 = 0xe3f4ba9;
  local_9c = 4;
  local_94 = *(undefined4 *)(curcontextwindows + 0x2c);
  local_90 = 0xe3f3701;
  local_88 = 0xe3f3753;
  local_8c = 4;
  local_84 = *(undefined4 *)(curcontextwindows + 8);
  local_80 = 0xe3f40cb;
  local_78 = (char *)0xe3f40f2;
  local_7c = 4;
  local_74 = *(undefined4 *)(curcontextwindows + 8);
  local_70 = (char *)0xe3f46dd;
  local_68 = 0xe3f4707;
  local_6c = (undefined4 *)0x4;
  local_64 = *(undefined4 *)(curcontextwindows + 8);
  get_window_properties(*(undefined4 *)(curcontextwindows + 0xc),&local_a0,8);
  local_a0 = 0xe3f4b1d;
  local_98 = 0xe3f4ba9;
  local_9c = 4;
  local_94 = *(undefined4 *)(curcontextwindows + 8);
  local_90 = 0xe3f40cb;
  local_88 = 0xe3f40f2;
  local_8c = 4;
  local_84 = *(undefined4 *)(curcontextwindows + 8);
  if (curcontextid == 0) {
    pcVar3 = "activeButton0";
  }
  else {
    pcVar3 = "activeButton1";
  }
  uVar1 = XmCreateForm(*(undefined4 *)(curcontextwindows + 0xc),pcVar3,&local_a0,4);
  *(undefined4 *)(curcontextwindows + 0x24) = uVar1;
  uVar1 = XmCreateBulletinBoard
                    (*(undefined4 *)(curcontextwindows + 0x24),"activeButtonMask",&local_a0,0);
  *(undefined4 *)(curcontextwindows + 0x28) = uVar1;
  XtManageChild(*(undefined4 *)(curcontextwindows + 0x28));
  XtAddEventHandler(*(undefined4 *)(curcontextwindows + 0x24),4,0,myContext,
                    *(undefined4 *)(curcontextwindows + 8));
  XtAddEventHandler(*(undefined4 *)(curcontextwindows + 0x28),4,0,myContext,
                    *(undefined4 *)(curcontextwindows + 8));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void newOverlayColormap(undefined4 param_1)

{
  int iVar1;
  char **ppcVar2;
  undefined4 uVar3;
  undefined4 *puStack_5c;
  undefined4 uStack_58;
  int iStack_54;
  char *apcStack_50 [20];
  
  iVar1 = init_display_mode();
  apcStack_50[1] = (char *)&uStack_58;
  if (iVar1 == 0) {
    apcStack_50[0] = "overlayWindow";
  }
  else {
    apcStack_50[0] = "popupWindow";
  }
  iStack_54 = 1;
  iVar1 = init_display_mode();
  if (iVar1 == 0) {
    ppcVar2 = apcStack_50 + iStack_54 * 2;
    *ppcVar2 = "overlayVisual";
  }
  else {
    ppcVar2 = apcStack_50 + iStack_54 * 2;
    *ppcVar2 = "popupVisual";
  }
  ppcVar2[1] = (char *)&puStack_5c;
  XtGetValues(param_1,apcStack_50,iStack_54 + 1);
  uVar3 = XCreateColormap(display,uStack_58,*puStack_5c,0);
  iVar1 = init_display_mode();
  if (iVar1 == 0) {
    apcStack_50[0] = "overlayColormap";
  }
  else {
    apcStack_50[0] = "popupColormap";
  }
  apcStack_50[1] = (char *)uVar3;
  XtSetValues(param_1,apcStack_50,1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamUnmonitorDir(int param_1)

{
  if ((fsn_resources == '\0') && (*(int *)(param_1 + 0x74) << 10 < 0)) {
    build_path_string(0,param_1);
    fam_cancel_monitor_wrapper(&database_root_node,param_1 + 0x60);
    *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) & 0xdf;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_gl_state(int param_1,undefined4 param_2)

{
  if (work_proc_id != 0) {
    XtRemoveWorkProc(work_proc_id);
    work_proc_id = 0;
  }
  if (param_1 != 0) {
    work_proc_id = XtAppAddWorkProc(app_context,param_1,param_2);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_database_state(void)

{
  char *pcVar1;
  size_t sVar2;
  char acStack_104 [260];
  
  pcVar1 = getenv("WINEDITOR");
  if (pcVar1 == (char *)0x0) {
    pcVar1 = getenv("EDITOR");
    if (pcVar1 == (char *)0x0) {
      putenv("WINEDITOR=jot");
    }
    else {
      sprintf(acStack_104,"WINEDITOR=winterm -c %s",pcVar1);
      sVar2 = strlen(acStack_104);
      pcVar1 = (char *)XtMalloc(sVar2 + 1);
      pcVar1 = strcpy(pcVar1,acStack_104);
      putenv(pcVar1);
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void activeWorkProc(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_view_transform(void)

{
  int unaff_gp;
  undefined4 uVar1;
  undefined4 in_register_00001040;
  float fVar2;
  undefined4 in_register_00001080;
  
  fVar2 = (float)(((double)(int)*(short *)(**(int **)(unaff_gp + -0x7684) + 0xc) /
                  (double)CONCAT44(in_register_00001040,
                                   *(undefined4 *)(*(int *)(unaff_gp + -0x7fa4) + -0x58e4))) *
                 (double)CONCAT44(in_register_00001080,
                                  *(undefined4 *)(*(int *)(unaff_gp + -0x7fa4) + -0x58dc)));
  uVar1 = (**(code **)(unaff_gp + -0x7ca4))();
  *(undefined4 *)(**(int **)(unaff_gp + -0x7684) + 0x14) = uVar1;
  uVar1 = (**(code **)(unaff_gp + -0x7ca0))(fVar2);
  *(undefined4 *)(**(int **)(unaff_gp + -0x7684) + 0x18) = uVar1;
  uVar1 = (**(code **)(unaff_gp + -0x7c90))(fVar2);
  *(undefined4 *)(**(int **)(unaff_gp + -0x7684) + 0x1c) = uVar1;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamMonitorDir(int param_1)

{
  undefined4 uVar1;
  
  if ((fsn_resources == '\0') && (-1 < *(int *)(param_1 + 0x74) << 10)) {
    uVar1 = build_path_string(0,param_1);
    update_database_entry(&database_root_node,uVar1,param_1 + 0x60);
    *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) | 0x20;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_gl_lists(void)

{
  int iVar1;
  
  if ((fsn_resources == '\0') && (iVar1 = fam_open_wrapper(&database_root_node), iVar1 < 0)) {
    fprintf((FILE *)0xfb52904,
            "Could not run FAM.  This program requires FAM to be installed.\nYou may need to install eoe2.sw.envm to obtain FAM\n"
           );
                    // WARNING: Subroutine does not return
    exit(1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setup_event_handlers(void)

{
  *(undefined4 *)curcontext = view_init_x;
  *(undefined4 *)(curcontext + 4) = view_init_y;
  *(undefined4 *)(curcontext + 8) = view_init_z;
  *(undefined2 *)(curcontext + 0xc) = 0;
  *(short *)(curcontext + 0xe) = (short)view_init_rotation_x;
  *(short *)(curcontext + 0x10) = (short)view_init_rotation_y;
  init_view_transform();
  init_camera_state();
  curcontext[0xc51] = 0;
  curcontext[0xc53] = 0;
  init_context_windows();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_toplevel_resources(undefined4 param_1)

{
  undefined4 uVar1;
  int *piVar2;
  int iVar3;
  int unaff_gp;
  
  (**(code **)(unaff_gp + -0x7e5c))
            (**(undefined4 **)(unaff_gp + -0x7600),*(int *)(unaff_gp + -0x7f5c) + 0x705,
             *(int *)(unaff_gp + -0x7fa4) + 0x2c2c,*(int *)(unaff_gp + -0x7fe0) + -0x4908,0,0);
  (**(code **)(unaff_gp + -0x7e54))
            (param_1,*(int *)(unaff_gp + -0x7f94) + 0x6e20,*(int *)(unaff_gp + -0x7f94) + -0x76e8,1,
             0,0);
  iVar3 = *(int *)(*(int *)(unaff_gp + -0x7f94) + 0x6e20);
  if (iVar3 == 0) {
    iVar3 = (**(code **)(unaff_gp + -0x7cbc))(9);
    piVar2 = (int *)(*(int *)(unaff_gp + -0x7f94) + 0x6e20);
    if (iVar3 < 4) {
      iVar3 = *(int *)(unaff_gp + -0x7fa4) + 0x2c34;
      *piVar2 = iVar3;
    }
    else {
      iVar3 = *(int *)(unaff_gp + -0x7fa4) + 0x2c3c;
      *piVar2 = iVar3;
    }
  }
  if (iVar3 == 0) {
    (**(code **)(unaff_gp + -0x7e54))
              (param_1,*(undefined4 *)(unaff_gp + -0x75dc),*(int *)(unaff_gp + -0x7f98) + 0x7c30,
               0x76,0,0);
  }
  else {
    uVar1 = (**(code **)(unaff_gp + -0x7c64))
                      (iVar3,**(undefined4 **)(unaff_gp + -0x7f7c),param_1,0,0);
    (**(code **)(unaff_gp + -0x7e54))
              (uVar1,*(undefined4 *)(unaff_gp + -0x75dc),*(int *)(unaff_gp + -0x7f98) + 0x7c30,0x76,
               0,0);
    (**(code **)(unaff_gp + -0x7ec8))(uVar1);
  }
  (**(code **)(unaff_gp + -0x77f0))
            (param_1,*(int *)(unaff_gp + -0x7fa4) + 0x2c44,*(int *)(unaff_gp + -0x7fa4) + 0x2c4c);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void calc_v_angle(void)

{
  float fVar1;
  uint in_register_00001040;
  float __x;
  undefined4 in_register_00001080;
  
  __x = (float)(((double)(int)*(short *)(curcontext + 0xe) /
                (double)((ulonglong)in_register_00001040 << 0x20)) *
               (double)CONCAT44(in_register_00001080,0x54442d18));
  fVar1 = sinf(__x);
  *(float *)(curcontext + 0x20) = fVar1;
  fVar1 = cosf(__x);
  *(float *)(curcontext + 0x24) = fVar1;
  fVar1 = tanf(__x);
  *(float *)(curcontext + 0x28) = fVar1;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void quit_application(void)

{
  cleanup_before_exit();
                    // WARNING: Subroutine does not return
  exit(0);
}

void install_help_callback(undefined4 param_1,undefined4 param_2)

{
  int unaff_gp;
  
  (**(code **)(unaff_gp + -0x7c54))
            (param_1,*(int *)(unaff_gp + -0x7f60) + 0x1b37,*(int *)(unaff_gp + -0x7fe0) + -0x4c0c,
             param_2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_display_state(void)

{
  int unaff_gp;
  
  (**(code **)(unaff_gp + -0x7ec8))(*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6e10));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void check_gl_ready(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void allocOverlayColor(undefined4 param_1,undefined4 param_2)

{
  int iVar1;
  undefined1 auStack_70 [12];
  undefined1 auStack_64 [12];
  undefined4 auStack_58 [2];
  char *pcStack_50;
  undefined4 *puStack_4c;
  
  iVar1 = init_display_mode();
  puStack_4c = auStack_58;
  if (iVar1 == 0) {
    pcStack_50 = "overlayColormap";
  }
  else {
    pcStack_50 = "popupColormap";
  }
  XtGetValues(param_1,&pcStack_50,1);
  iVar1 = XAllocNamedColor(display,auStack_58[0],param_2,auStack_64,auStack_70);
  if (iVar1 == 0) {
    fprintf((FILE *)0xfb52904,"Could not allocate overlay color %s\n",param_2);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void finalize_menu_setup(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 uVar2;
  int iVar3;
  int unaff_gp;
  undefined4 local_2c;
  int local_28;
  undefined4 local_24;
  
  local_2c = 0;
  (**(code **)(unaff_gp + -0x77f4))(**(undefined4 **)(unaff_gp + -0x75fc),0,&local_28,&local_2c);
  uVar1 = (**(code **)(unaff_gp + -0x7bcc))
                    (param_1,*(int *)(unaff_gp + -0x7fa4) + 0x1c80,&local_28,local_2c);
  (**(code **)(unaff_gp + -0x7c54))
            (uVar1,*(int *)(unaff_gp + -0x7f60) + 0x1e96,*(undefined4 *)(unaff_gp + -0x7950),0);
  (**(code **)(unaff_gp + -0x7c54))
            (uVar1,*(int *)(unaff_gp + -0x7f60) + 0x28d0,*(undefined4 *)(unaff_gp + -0x7954),0);
  local_2c = 0;
  uVar2 = (**(code **)(unaff_gp + -0x7b20))(uVar1,*(int *)(unaff_gp + -0x7fa4) + 0x1c8c,&local_28,0)
  ;
  iVar3 = *(int *)(unaff_gp + -0x7fe0) + -0x4c0c;
  (**(code **)(unaff_gp + -0x7c54))
            (uVar2,*(int *)(unaff_gp + -0x7f60) + 0x124b,iVar3,*(undefined4 *)(unaff_gp + -0x7660));
  (**(code **)(unaff_gp + -0x7c78))(uVar2);
  local_2c = 0;
  uVar2 = (**(code **)(unaff_gp + -0x7b20))(uVar1,*(int *)(unaff_gp + -0x7fa4) + 0x1c98,&local_28,0)
  ;
  (**(code **)(unaff_gp + -0x7c54))
            (uVar2,*(int *)(unaff_gp + -0x7f60) + 0x124b,*(int *)(unaff_gp + -0x7fe0) + -0x4a54,0);
  (**(code **)(unaff_gp + -0x7c78))(uVar2);
  local_2c = 0;
  uVar2 = (**(code **)(unaff_gp + -0x7b20))(uVar1,*(int *)(unaff_gp + -0x7fa4) + 0x1ca8,&local_28,0)
  ;
  (**(code **)(unaff_gp + -0x7c54))
            (uVar2,*(int *)(unaff_gp + -0x7f60) + 0x124b,iVar3,*(undefined4 *)(unaff_gp + -0x7668));
  (**(code **)(unaff_gp + -0x7c78))(uVar2);
  local_2c = 0;
  uVar2 = (**(code **)(unaff_gp + -0x7b20))(uVar1,*(int *)(unaff_gp + -0x7fa4) + 0x1cb4,&local_28,0)
  ;
  (**(code **)(unaff_gp + -0x7c54))
            (uVar2,*(int *)(unaff_gp + -0x7f60) + 0x124b,iVar3,*(undefined4 *)(unaff_gp + -0x766c));
  (**(code **)(unaff_gp + -0x7c78))(uVar2);
  local_28 = *(int *)(unaff_gp + -0x7f60) + 0x26c9;
  local_2c = 1;
  local_24 = uVar1;
  uVar1 = (**(code **)(unaff_gp + -0x7bf8))
                    (param_1,*(int *)(unaff_gp + -0x7fa4) + 0x1cc4,&local_28,1);
  (**(code **)(unaff_gp + -0x7c78))(uVar1);
  local_2c = 1;
  local_28 = *(int *)(unaff_gp + -0x7f60) + 0x1f37;
  local_24 = uVar1;
  (**(code **)(unaff_gp + -0x7cc0))(param_1,&local_28,1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_rendering(void)

{
  int unaff_gp;
  
  if (**(char **)(unaff_gp + -0x75dc) == '\0') {
    (**(code **)(unaff_gp + -0x7720))(*(int *)(unaff_gp + -0x7f94) + 0x6c70);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void widgetHelp(undefined4 param_1,undefined4 param_2)

{
  XtAddCallback(param_1,0xe3f3e9f,help_callback,param_2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dirfamDone(void)

{
  if (fsn_resources == '\0') {
    init_database_node(&database_root_node);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setup_directory_handler(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 local_2c;
  ushort *local_28;
  undefined4 local_24;
  uint local_20;
  ushort local_2;
  
  if (view_mode_flags == '\0') {
    gl_swap_buffers(1);
    setup_context_widgets();
    view_mode_flags = '\x01';
    gl_swap_buffers(1);
  }
  local_28 = &local_2;
  local_2c = 0xf66160a;
  XtGetValues(context_top_widget,&local_2c,1);
  local_28 = (ushort *)(uint)(local_2 >> 1);
  local_2c = 0xe3f4572;
  local_24 = 0xe3f4566;
  local_20 = (uint)local_28;
  XtSetValues(*(undefined4 *)(altcontextwindows + 0xc),&local_2c,2);
  XtManageChild(*(undefined4 *)(altcontextwindows + 0xc));
  local_2c = 0xe3f4572;
  local_24 = 0xe3f4566;
  local_28 = (ushort *)0x1;
  local_20 = 1000;
  XtSetValues(*(undefined4 *)(altcontextwindows + 0xc),&local_2c,2);
  altcontext[0xc51] = 1;
  uVar1 = XtDisplay(*(undefined4 *)(altcontextwindows + 0x28));
  uVar2 = XtWindow(*(undefined4 *)(altcontextwindows + 0x28));
  XMapWindow(uVar1,uVar2);
  XtManageChild(*(undefined4 *)(curcontextwindows + 0x24));
  uVar1 = XtWindow(*(undefined4 *)(curcontextwindows + 0x24));
  XRaiseWindow(display,uVar1);
  uVar1 = XtDisplay(*(undefined4 *)(curcontextwindows + 0x28));
  uVar2 = XtWindow(*(undefined4 *)(curcontextwindows + 0x28));
  XUnmapWindow(uVar1,uVar2);
  XtManageChild(*(undefined4 *)(altcontextwindows + 0x24));
  uVar1 = XtWindow(*(undefined4 *)(altcontextwindows + 0x24));
  XRaiseWindow(display,uVar1);
  gl_swap_buffers(1);
  draw_mark_overlay();
  gl_swap_buffers(1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_display_mode(void)

{
  int iVar1;
  int unaff_gp;
  
  if (*(char *)(*(int *)(unaff_gp + -0x7f98) + 0x6f04) == '\0') {
    iVar1 = (**(code **)(unaff_gp + -0x7cbc))(0x11);
    if (iVar1 < 2) {
      *(undefined1 *)(*(int *)(unaff_gp + -0x7f98) + 0x6f00) = 1;
    }
    *(undefined1 *)(*(int *)(unaff_gp + -0x7f98) + 0x6f04) = 1;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
