// main.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/main.h"

void restorePositions(void)

{
  FUN_0042e3bc(&fam_connection);
  if (altcontext[0xc51] != '\0') {
    gl_swap_buffers(1);
    FUN_0042e3bc(&fam_request_id);
    gl_swap_buffers(1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void update_display(undefined4 param_1,undefined4 param_2)

{
  int *piVar1;
  int iVar2;
  code *pcVar3;
  int unaff_gp;
  float fVar4;
  undefined4 uVar5;
  uint in_register_00001010;
  double dVar6;
  double in_f6;
  float fVar7;
  undefined4 in_f11;
  
  (**(code **)(unaff_gp + -0x7848))();
  (**(code **)(unaff_gp + -0x7f20))(*(int *)(unaff_gp + -0x7f94) + 0x66ac);
  piVar1 = *(int **)(unaff_gp + -0x76dc);
  **(undefined4 **)(unaff_gp + -0x75cc) = 0;
  iVar2 = *piVar1;
  **(undefined4 **)(unaff_gp + -0x75c8) = 0;
  **(undefined4 **)(unaff_gp + -0x75d4) = 0;
  **(undefined4 **)(unaff_gp + -0x75d0) = 0;
  if (iVar2 == 0) {
    in_f6 = (double)CONCAT44((int)((ulonglong)in_f6 >> 0x20),0x3f800000);
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x66b0) = 0x3f800000;
  }
  else {
    fVar4 = (float)(*(code *)(*(int *)(unaff_gp + -0x7fe8) + 0x1774))
                             (*(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x184));
    *(float *)(*(int *)(unaff_gp + -0x7f94) + 0x66b0) =
         *(float *)(*(int *)(unaff_gp + -0x75dc) + 0x68) / fVar4;
  }
  piVar1 = *(int **)(unaff_gp + -0x76d4);
  *(undefined4 *)(*piVar1 + 0x2c) = 0;
  *(undefined4 *)(*piVar1 + 0x30) = 0;
  (**(code **)(unaff_gp + -0x7a70))(*piVar1);
  uVar5 = (undefined4)((ulonglong)in_f6 >> 0x20);
  if (**(int **)(unaff_gp + -0x76dc) == 0) {
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x66b0) = 0x3f800000;
  }
  else {
    iVar2 = **(int **)(unaff_gp + -0x76d8);
    if (iVar2 == 0) {
      *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x66b4) = 0x3f800000;
    }
    else if ((iVar2 == 1) || (iVar2 != 2)) {
      fVar4 = (float)(*(code *)(*(int *)(unaff_gp + -0x7fe8) + 0x1774))
                               (*(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x18c));
      fVar7 = *(float *)(*(int *)(unaff_gp + -0x75dc) + 0x6c);
      in_f6 = (double)CONCAT44(uVar5,fVar7);
      *(float *)(*(int *)(unaff_gp + -0x7f94) + 0x66b4) = fVar7 / fVar4;
    }
    else {
      fVar4 = (float)(*(code *)(*(int *)(unaff_gp + -0x7fe8) + 0x1774))
                               (*(undefined4 *)(*piVar1 + 0x20));
      in_f6 = (double)*(float *)(*(int *)(unaff_gp + -0x75dc) + 0x6c);
      *(float *)(*(int *)(unaff_gp + -0x7f94) + 0x66b4) = (float)(in_f6 / (double)fVar4);
    }
  }
  dVar6 = (double)*(float *)(*piVar1 + 0x3c);
  fVar4 = (float)(**(code **)(unaff_gp + -0x7b64))
                           (*(undefined4 *)(*(int *)(unaff_gp + -0x75dc) + 0x104),
                            (float)((dVar6 / (double)((ulonglong)in_f6 & 0xffffffff00000000)) /
                                   (double)*(float *)(*(int *)(unaff_gp + -0x75dc) + 0x108)));
  (**(code **)(unaff_gp + -0x7a6c))
            (*piVar1,param_2,0,0,in_f11,
             SUB84((double)((ulonglong)dVar6 & 0xffffffff00000000) / (double)fVar4,0));
  (**(code **)(unaff_gp + -0x7a68))(*piVar1,param_2,0,0);
  uVar5 = (**(code **)(unaff_gp + -0x7b64))
                    (*(undefined4 *)(*(int *)(unaff_gp + -0x75dc) + 0x104),
                     **(float **)(unaff_gp + -0x75c8) /
                     *(float *)(*(int *)(unaff_gp + -0x75dc) + 0x108));
  **(undefined4 **)(unaff_gp + -0x75b8) = uVar5;
  pcVar3 = *(code **)(unaff_gp + -0x783c);
  **(float **)(unaff_gp + -0x75d0) =
       (float)((double)**(float **)(unaff_gp + -0x75d0) +
              (double)((ulonglong)in_register_00001010 << 0x20));
  **(float **)(unaff_gp + -0x75d4) =
       (float)((double)**(float **)(unaff_gp + -0x75d4) -
              (double)((ulonglong)in_register_00001010 << 0x20));
  dVar6 = (double)**(float **)(unaff_gp + -0x75c8);
  **(float **)(unaff_gp + -0x75c8) =
       (float)(dVar6 + (double)((ulonglong)in_register_00001010 << 0x20));
  **(float **)(unaff_gp + -0x75cc) =
       (float)((double)-*(float *)(*piVar1 + 0x3c) / (double)((ulonglong)dVar6 & 0xffffffff00000000)
              - (double)((ulonglong)in_register_00001010 << 0x20));
  (*pcVar3)();
  (**(code **)(unaff_gp + -0x7978))();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void first_traversal(int param_1)

{
  int iVar1;
  double dVar2;
  double dVar3;
  uint unaff_000010b0;
  float fVar4;
  uint in_fcsr;
  
  *(byte *)(param_1 + 0x74) = *(byte *)(param_1 + 0x74) | 0x10;
  if (*(int *)(param_1 + 0xc) == 0) {
    iVar1 = 0;
  }
  else {
    dVar2 = sqrt((double)(*(int *)(param_1 + 0xc) + -1));
    if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
      dVar2 = ROUND(dVar2);
    }
    else {
      dVar2 = FLOOR(dVar2);
    }
    iVar1 = (int)dVar2 + 1;
  }
  if (iVar1 == 0) {
    *(float *)(param_1 + 0x3c) =
         (float)((double)view_offset_x +
                (double)((ulonglong)unaff_000010b0 << 0x20) * (double)view_offset_adjustment);
  }
  else {
    *(float *)(param_1 + 0x3c) =
         (float)((double)iVar1 *
                ((double)view_offset_x +
                (double)((ulonglong)unaff_000010b0 << 0x20) * (double)view_offset_adjustment));
  }
  dVar3 = (double)view_offset_adjustment;
  dVar2 = (double)view_offset_x;
  *(undefined4 *)(param_1 + 0x1c) = 0;
  *(undefined4 *)(param_1 + 0x54) = 0;
  fVar4 = (float)((double)(1 - iVar1) *
                  (dVar2 + (double)((ulonglong)unaff_000010b0 << 0x20) * dVar3) *
                 (double)((ulonglong)dVar2 & 0xffffffff00000000));
  if (*(int *)(param_1 + 0xc) < 1) {
    *(undefined4 *)(param_1 + 0x20) = *(undefined4 *)(param_1 + 0x1c);
    FUN_00412234(param_1);
    if (window_height < *(int *)(param_1 + 0x1c)) {
      window_height = *(int *)(param_1 + 0x1c);
    }
    *(undefined4 *)(param_1 + 0x48) = 0;
    if (0 < *(int *)(param_1 + 0x14)) {
      FUN_00412604(**(undefined4 **)(param_1 + 0x18));
                    // WARNING: Bad instruction - Truncating control flow here
      halt_baddata();
    }
                    // WARNING: Bad instruction - Truncating control flow here
    halt_baddata();
  }
  iVar1 = **(int **)(param_1 + 0x10);
  *(byte *)(iVar1 + 0x28) = *(byte *)(iVar1 + 0x28) | 4;
  *(int *)(param_1 + 0x1c) = *(int *)(param_1 + 0x1c) + *(int *)(iVar1 + 0xc);
  *(float *)(iVar1 + 0x14) = fVar4;
  *(float *)(iVar1 + 0x18) = fVar4;
  update_directory_bounds(iVar1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void need_pups(void)

{
  int iVar1;
  
  if (DAT_10006f04 == '\0') {
    iVar1 = getgdesc(0x11);
    if (iVar1 < 2) {
      DAT_10006f00 = 1;
    }
    DAT_10006f04 = '\x01';
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void AddServer__6ClientFliT2(int *param_1,in_addr_t param_2,u_long param_3,u_long param_4)

{
  undefined2 extraout_var;
  int *piVar1;
  int iVar2;
  sockaddr_in sStack_18;
  int iStack_4;
  
  piVar1 = (int *)__nw__FUi(0x17a0);
  sStack_18.sin_family = 2;
  sStack_18.sin_addr.s_addr = param_2;
  sStack_18.sin_port = pmap_getport(&sStack_18,param_3,param_4,6);
  if ((CONCAT22(extraout_var,sStack_18.sin_port) != 0) && (iStack_4 = socket(2,2,0), -1 < iStack_4))
  {
    iVar2 = connect(iStack_4,(sockaddr *)&sStack_18,0x10);
    if (iVar2 < 0) {
      close(iStack_4);
    }
    else {
      iVar2 = *param_1;
      *param_1 = (int)piVar1;
      piVar1[5] = (int)(piVar1 + 7);
      piVar1[6] = (int)(piVar1 + 7);
      *piVar1 = iStack_4;
      piVar1[3] = 0;
      piVar1[4] = 0;
      piVar1[0x2f7] = (int)(piVar1 + 0x2f9);
      piVar1[0x2f8] = (int)(piVar1 + 0x2f9);
      piVar1[0x2f6] = 0;
      piVar1[0x2f5] = 1;
      piVar1[2] = 0;
      piVar1[0x5e7] = 0;
      piVar1[1] = iVar2;
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void deleteMessage(undefined4 *param_1)

{
  undefined4 *puVar1;
  undefined4 local_c;
  undefined4 local_8;
  
  puVar1 = current_directory_node;
  if (param_1 == current_directory_node) {
    do {
      current_directory_node = (undefined4 *)puVar1[1];
      XmStringFree(*puVar1);
      XtFree(puVar1);
      if (current_directory_node == (undefined4 *)0x0) break;
      puVar1 = current_directory_node;
    } while (*(char *)(current_directory_node + 2) != '\0');
    if (current_directory_node == (undefined4 *)0x0) {
      local_8 = blankXmString;
    }
    else {
      local_8 = *current_directory_node;
    }
    local_c = 0xe3f40b5;
    XtSetValues(message_widget,&local_c,1);
  }
  else {
    *(undefined1 *)(param_1 + 2) = 1;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void viewFile(undefined4 param_1,undefined4 *param_2)

{
  int iVar1;
  size_t sVar2;
  undefined4 uVar3;
  stat sStack_8c;
  void *pvStack_4;
  
  build_path_string((int)curcontext + 0x84c,param_1);
  strcat(curcontext + 0x84c,(char *)*param_2);
  iVar1 = stat(curcontext + 0x84c,&sStack_8c);
  if (iVar1 < 0) {
    show_error_dialog("cannot stat",(int)curcontext + 0x84c);
  }
  else {
    pvStack_4 = (void *)XtMalloc(sStack_8c.st_blksize + 1);
    iVar1 = open(curcontext + 0x84c,0);
    if (iVar1 < 0) {
      show_error_dialog("cannot open",(int)curcontext + 0x84c);
    }
    else {
      sVar2 = read(iVar1,pvStack_4,sStack_8c.st_blksize);
      if (sVar2 == sStack_8c.st_blksize) {
        *(undefined1 *)((int)pvStack_4 + sStack_8c.st_blksize) = 0;
        close(iVar1);
        XmTextSetString(*(undefined4 *)(curcontextwindows + 0x14),pvStack_4);
        XtFree(pvStack_4);
        iVar1 = access(curcontext + 0x84c,2);
        if (iVar1 < 0) {
          XtSetSensitive(*(undefined4 *)(curcontextwindows + 0x18),0);
          XmTextSetEditable(*(undefined4 *)(curcontextwindows + 0x14),0);
        }
        else {
          XtSetSensitive(*(undefined4 *)(curcontextwindows + 0x18),1);
          XmTextSetEditable(*(undefined4 *)(curcontextwindows + 0x14),1);
        }
        XtManageChild(*(undefined4 *)(curcontextwindows + 0x10));
        uVar3 = XtWindow(*(undefined4 *)(curcontextwindows + 0x10));
        XRaiseWindow(display,uVar3);
      }
      else {
        show_error_dialog("cannot read",(int)curcontext + 0x84c);
        close(iVar1);
      }
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void activeWorkProc(void)

{
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void getword__FPcPl(undefined1 *param_1,undefined1 *param_2)

{
  *param_2 = *param_1;
  param_2[1] = param_1[1];
  param_2[2] = param_1[2];
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void restorePosition(undefined4 param_1)

{
  int iStack_1c;
  int iStack_18;
  undefined4 uStack_14;
  undefined4 uStack_10;
  undefined4 uStack_c;
  undefined4 uStack_8;
  short sStack_4;
  short sStack_2;
  
  FUN_0042dfb4(param_1,&sStack_2,&sStack_4,&uStack_8,&uStack_c,&uStack_10,&uStack_14,&iStack_18,
               &iStack_1c,(int)curcontext + 0xc50);
  if (sStack_2 != *(short *)(curcontext + 0xc)) {
    *(short *)(curcontext + 0xc) = sStack_2;
    init_view_transform();
  }
  if (sStack_4 != *(short *)(curcontext + 0xe)) {
    *(short *)(curcontext + 0xe) = sStack_4;
    init_camera_state();
  }
  *(undefined4 *)curcontext = uStack_8;
  *(undefined4 *)(curcontext + 4) = uStack_c;
  *(undefined4 *)(curcontext + 8) = uStack_10;
  *(undefined4 *)(curcontext + 0x3c) = uStack_14;
  if (iStack_18 != *(int *)(curcontext + 0x44)) {
    if (iStack_18 == 0) {
      clear_marked_state(0);
    }
    else {
      update_marked_item();
    }
  }
  if (iStack_1c != *(int *)(curcontext + 0x48)) {
    if (iStack_1c == 0) {
      clear_current_selection(0);
    }
    else {
      get_item_screen_coords();
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void rescanDatabase(void)

{
  int iVar1;
  char acStack_510 [1000];
  undefined4 local_128;
  statvfs asStack_124 [2];
  stat local_88;
  
  local_128 = set_status_message("rescanning file system",0);
  process_pending_events();
  iVar1 = statvfs((char *)*topdir,asStack_124);
  if (iVar1 < 0) {
    sprintf(acStack_510,"cannot statvfs %s, leaving display unchanged",*topdir);
    set_status_message(acStack_510,1000);
    deleteMessage(local_128);
  }
  else {
    strcpy(fstyp,(char *)&asStack_124[0].__f_unused);
    localFlag = asStack_124[0].__f_spare[1] & 0x80000000;
    iVar1 = lstat((char *)*topdir,&local_88);
    if (iVar1 < 0) {
      sprintf(acStack_510,"cannot stat %s, leaving display unchanged",*topdir);
      set_status_message(acStack_510,1000);
      deleteMessage(local_128);
    }
    else {
      current_device_id = local_88.st_dev._0_4_;
      FUN_00415598(topdir);
      deleteMessage(local_128);
      set_status_message("file system update complete",2000);
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void reset_eye(void)

{
  save_matrix_state();
  set_camera_lookat((double)view_init_x,(double)view_init_y);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cleanup_before_exit(void)

{
  int unaff_gp;
  
  if (**(char **)(unaff_gp + -0x75dc) == '\0') {
    (**(code **)(unaff_gp + -0x7818))(**(undefined4 **)(unaff_gp + -0x75f0));
    (**(code **)(unaff_gp + -0x78f0))();
    (*(code *)(*(int *)(unaff_gp + -0x7fe8) + 0x4da4))();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void fileDeleted(int param_1,char *param_2)

{
  int iVar1;
  byte bVar2;
  stat sStack_94;
  char *pcStack_c;
  
  if (-1 < *(int *)(param_1 + 0x74) << 0xd) {
    pcStack_c = (char *)build_path_string(0,param_1);
    strcat(pcStack_c,param_2);
    iVar1 = lstat(pcStack_c,&sStack_94);
    if (iVar1 < 0) {
      bVar2 = *(byte *)(param_1 + 0x75);
      *(byte *)(param_1 + 0x75) = bVar2 & 0x7f;
      *(byte *)(param_1 + 0x74) = *(byte *)(param_1 + 0x74) & 0xfe;
      *(byte *)(param_1 + 0x75) = bVar2 & 0x3f;
      iVar1 = validate_directory_access(param_1,param_2);
      if (iVar1 == 0) {
        iVar1 = find_directory_by_path(param_1,param_2);
        if (iVar1 != 0) {
          bVar2 = *(byte *)(iVar1 + 0x74) & 0xfd;
          *(byte *)(iVar1 + 0x74) = bVar2;
          *(byte *)(iVar1 + 0x74) = bVar2 | 4;
          *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) & 0x7f | 0x80;
        }
      }
      else {
        *(byte *)(iVar1 + 0x29) = *(byte *)(iVar1 + 0x29) & 0x7f;
        *(byte *)(iVar1 + 0x28) = *(byte *)(iVar1 + 0x28) & 0xfe | 1;
        *(byte *)(param_1 + 0x74) = *(byte *)(param_1 + 0x74) | 1;
      }
      if (((*(byte *)(param_1 + 0x74) & 1) != 0) || (*(char *)(param_1 + 0x75) < '\0')) {
        process_child_directory(param_1);
      }
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void writePosition(undefined2 *param_1,FILE *param_2)

{
  char *pcVar1;
  size_t sVar2;
  void *pvVar3;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  undefined4 uStack_28;
  undefined4 uStack_24;
  undefined4 uStack_20;
  undefined4 uStack_1c;
  undefined4 uStack_18;
  undefined4 uStack_14;
  undefined4 uStack_10;
  undefined2 uStack_c;
  undefined2 uStack_a;
  undefined2 uStack_8;
  undefined2 uStack_6;
  undefined2 uStack_4;
  undefined1 uStack_2;
  
  uStack_30 = *(undefined4 *)(param_1 + 4);
  uStack_2c = *(undefined4 *)(param_1 + 6);
  uStack_28 = *(undefined4 *)(param_1 + 8);
  uStack_24 = *(undefined4 *)(param_1 + 0xc);
  uStack_20 = *(undefined4 *)(param_1 + 0xe);
  uStack_1c = *(undefined4 *)(param_1 + 0x10);
  uStack_18 = *(undefined4 *)(param_1 + 0x14);
  uStack_14 = *(undefined4 *)(param_1 + 0x16);
  uStack_10 = *(undefined4 *)(param_1 + 0x18);
  uStack_c = *param_1;
  uStack_a = param_1[1];
  uStack_2 = *(undefined1 *)(param_1 + 0x1a);
  if (*(int *)(param_1 + 2) == 0) {
    uStack_8 = 0;
  }
  else {
    pcVar1 = (char *)build_path_string(0,*(int *)(param_1 + 2));
    sVar2 = strlen(pcVar1);
    uStack_8 = (short)sVar2;
  }
  if (*(int *)(param_1 + 10) == 0) {
    uStack_6 = 0;
  }
  else {
    pcVar1 = (char *)build_path_string(0);
    sVar2 = strlen(pcVar1);
    uStack_6 = (short)sVar2;
  }
  if (*(undefined4 **)(param_1 + 0x12) == (undefined4 *)0x0) {
    uStack_4 = 0;
  }
  else {
    sVar2 = strlen((char *)**(undefined4 **)(param_1 + 0x12));
    uStack_4 = (short)sVar2;
  }
  fwrite(&uStack_30,0x30,1,param_2);
  if (*(int *)(param_1 + 2) != 0) {
    pvVar3 = (void *)build_path_string(0,*(int *)(param_1 + 2));
    fwrite(pvVar3,1,(size_t)uStack_8,param_2);
  }
  if (*(int *)(param_1 + 10) != 0) {
    pvVar3 = (void *)build_path_string(0);
    fwrite(pvVar3,1,(size_t)uStack_6,param_2);
  }
  if (*(undefined4 **)(param_1 + 0x12) != (undefined4 *)0x0) {
    fwrite((void *)**(undefined4 **)(param_1 + 0x12),1,(size_t)uStack_4,param_2);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void handleEvents(void)

{
  int iVar1;
  undefined1 auStack_60 [96];
  
  iVar1 = XtAppPending(app_context);
  if (iVar1 == 0) {
    iVar1 = FUN_0040f1f0();
    if (iVar1 == 0) goto LAB_00411a50;
  }
  do {
    do {
      XtAppNextEvent(app_context,auStack_60);
      XtDispatchEvent(auStack_60);
      iVar1 = XtAppPending(app_context);
    } while (iVar1 != 0);
    iVar1 = FUN_0040f1f0();
  } while (iVar1 != 0);
LAB_00411a50:
  FUN_0040cf50();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void initialize_db(char *param_1)

{
  bool bVar1;
  bool bVar2;
  size_t sVar3;
  char *pcVar4;
  size_t sVar5;
  uint __c;
  int iVar6;
  char *__s;
  statvfs asStack_128 [2];
  stat sStack_8c;
  undefined4 uStack_4;
  
  bVar2 = false;
  time(&last_operation_time);
  if (db_filepath == (char *)0x0) {
    if (home_directory == (char *)0x0) {
      if (relative_path_flag == '\0') {
        home_directory = getenv("HOME");
        if (home_directory == (char *)0x0) {
          home_directory = ".";
        }
      }
      else {
        home_directory = ".";
      }
    }
    sVar5 = strlen(home_directory);
    sVar3 = strlen(param_1);
    db_filepath = (char *)malloc(sVar3 + sVar5 + 7);
    strcpy(db_filepath,home_directory);
    strcat(db_filepath,"/.FSN_");
    sVar5 = strlen(db_filepath);
    __s = db_filepath + sVar5;
    strcat(db_filepath,param_1);
    pcVar4 = strchr(__s,0x2f);
    while (pcVar4 != (char *)0x0) {
      *pcVar4 = '_';
      pcVar4 = strchr(__s,0x2f);
    }
  }
  else {
    if (*db_filepath == '/') {
      home_directory = strdup(db_filepath);
    }
    else {
      pcVar4 = getcwd((char *)0x0,0x400);
      sVar5 = strlen(pcVar4);
      sVar3 = strlen(db_filepath);
      home_directory = (char *)malloc(sVar3 + sVar5 + 2);
      strcpy(home_directory,pcVar4);
      strcat(home_directory,"/");
      strcat(home_directory,db_filepath);
      db_filepath = strdup(home_directory);
      free(pcVar4);
    }
    pcVar4 = strrchr(home_directory,0x2f);
    *pcVar4 = '\0';
  }
  sVar5 = strlen(db_filepath);
  pcVar4 = (char *)malloc(sVar5 + 0x12);
  sprintf(pcVar4,"zcat 2>/dev/null<%s",db_filepath);
  current_file = popen(pcVar4,"r");
  bVar1 = false;
  if (current_file != (FILE *)0x0) {
    if (_DAT_0fb51f00 == 0) {
      current_file->_flags = current_file->_flags + -1;
      if (current_file->_flags < 0) {
        __c = __filbuf();
      }
      else {
        __c = (uint)(byte)*current_file->_IO_read_ptr;
        current_file->_IO_read_ptr = current_file->_IO_read_ptr + 1;
      }
    }
    else {
      __c = __semgetc();
    }
    if (__c == 0xffffffff) {
      pclose(current_file);
      bVar1 = false;
    }
    else {
      ungetc(__c,current_file);
      bVar2 = true;
      bVar1 = true;
    }
  }
  if ((bVar1) || (current_file = fopen(db_filepath,"r"), current_file != (FILE *)0x0)) {
    FUN_0042afd4();
    uStack_4 = set_status_message("reading file system database",0);
    FUN_004172d4();
    *(byte *)(topdir + 0x1d) = *(byte *)(topdir + 0x1d) | 2;
    if (bVar2) {
      pclose(current_file);
    }
    else {
      fclose(current_file);
    }
    deleteMessage(uStack_4);
    iVar6 = statvfs((char *)*topdir,asStack_128);
    if (iVar6 < 0) {
      fprintf((FILE *)0xfb52904,"Could not statvfs %s, exiting\n",*topdir);
                    // WARNING: Subroutine does not return
      exit(1);
    }
    strcpy(fstyp,(char *)&asStack_128[0].__f_unused);
    localFlag = asStack_128[0].__f_spare[1] & 0x80000000;
    iVar6 = lstat((char *)*topdir,&sStack_8c);
    if (iVar6 < 0) {
      fprintf((FILE *)0xfb52904,"Could not stat %s, exiting\n",*topdir);
                    // WARNING: Subroutine does not return
      exit(1);
    }
    current_device_id = sStack_8c.st_dev._0_4_;
  }
  else {
    FUN_0042b030();
    topdir = (undefined4 *)FUN_004158d4(param_1);
    free(pcVar4);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void layout_db(undefined4 param_1,undefined4 param_2)

{
  float fVar1;
  uint in_register_00001010;
  double dVar2;
  undefined4 uVar3;
  double in_f6;
  undefined4 in_f11;
  
  FUN_0042df08();
  time(&last_operation_time);
  miny = 0.0;
  maxy = 0.0;
  minx = 0.0;
  maxx = 0.0;
  if (displayHeight == 0) {
    in_f6 = (double)CONCAT44((int)((ulonglong)in_f6 >> 0x20),0x3f800000);
    horizontal_scale_factor = 1.0;
  }
  else {
    fVar1 = (float)process_directory_data(window_width);
    horizontal_scale_factor = DAT_100174f8 / fVar1;
  }
  *(undefined4 *)(topdir + 0x2c) = 0;
  *(undefined4 *)(topdir + 0x30) = 0;
  FUN_00412604(topdir);
  uVar3 = (undefined4)((ulonglong)in_f6 >> 0x20);
  if (displayHeight == 0) {
    horizontal_scale_factor = 1.0;
  }
  else if (displayDirectoryHeight == 0) {
    vertical_scale_factor = 1.0;
  }
  else if ((displayDirectoryHeight == 1) || (displayDirectoryHeight != 2)) {
    fVar1 = (float)process_directory_data(window_height);
    in_f6 = (double)CONCAT44(uVar3,reference_dimension);
    vertical_scale_factor = reference_dimension / fVar1;
  }
  else {
    fVar1 = (float)process_directory_data(*(undefined4 *)(topdir + 0x20));
    in_f6 = (double)reference_dimension;
    vertical_scale_factor = (float)(in_f6 / (double)fVar1);
  }
  dVar2 = (double)*(float *)(topdir + 0x3c);
  fVar1 = powf(zoom_base_factor,
               (float)((dVar2 / (double)((ulonglong)in_f6 & 0xffffffff00000000)) /
                      (double)zoom_reference_height));
  FUN_00412994(topdir,param_2,0,0,in_f11,
               SUB84((double)((ulonglong)dVar2 & 0xffffffff00000000) / (double)fVar1,0));
  FUN_00412bc0(topdir,param_2,0,0);
  maxShrinkage = powf(zoom_base_factor,maxy / zoom_reference_height);
  maxx = (float)((double)maxx + (double)((ulonglong)in_register_00001010 << 0x20));
  minx = (float)((double)minx - (double)((ulonglong)in_register_00001010 << 0x20));
  dVar2 = (double)maxy;
  maxy = (float)(dVar2 + (double)((ulonglong)in_register_00001010 << 0x20));
  miny = (float)((double)-*(float *)(topdir + 0x3c) /
                 (double)((ulonglong)dVar2 & 0xffffffff00000000) -
                (double)((ulonglong)in_register_00001010 << 0x20));
  FUN_0042e5c4();
  FUN_00421780();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void ReadFromServer__6ClientFiPcT1(int *param_1,int param_2,undefined1 *param_3,int param_4)

{
  int iVar1;
  int iVar2;
  undefined1 *puVar3;
  int *piVar4;
  int iStack_14;
  int aiStack_10 [4];
  
  for (piVar4 = (int *)*param_1; (piVar4 != (int *)0x0 && (param_2 != *piVar4));
      piVar4 = (int *)piVar4[1]) {
  }
  if (piVar4 == (int *)0x0) {
    _DAT_0fb52720 = 2;
  }
  else {
    if (piVar4[3] == 0) {
      FUN_0043b3b8(param_1,piVar4);
    }
    if ((uint)(piVar4[6] - piVar4[5]) < 4) {
      iStack_14 = 0;
      iVar2 = piVar4[5];
    }
    else {
      getword__FPcPl(piVar4[5],&iStack_14);
      iVar2 = piVar4[5];
    }
    if ((uint)(piVar4[6] - iVar2) < iStack_14 + 4U) {
      _DAT_0fb52720 = 0x43;
    }
    else {
      iVar1 = 0;
      if (iStack_14 < param_4) {
        param_4 = iStack_14;
      }
      piVar4[5] = iVar2 + 4;
      if (0 < param_4) {
        do {
          puVar3 = (undefined1 *)(piVar4[5] + iVar1);
          iVar1 = iVar1 + 1;
          *param_3 = *puVar3;
          param_3 = param_3 + 1;
        } while (iVar1 < param_4);
      }
      iVar2 = piVar4[5] + iStack_14;
      piVar4[5] = iVar2;
      if ((uint)(piVar4[6] - iVar2) < 4) {
        piVar4[3] = 0;
      }
      else {
        getword__FPcPl(iVar2,aiStack_10);
        if ((uint)(piVar4[6] - piVar4[5]) < aiStack_10[0] + 4U) {
          piVar4[3] = 0;
        }
        else {
          piVar4[3] = 1;
        }
      }
      piVar4[4] = 0;
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void SG_getNormalArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  
  uVar1 = FUN_004314e0(param_1,param_2,&temp_data_buffer,2);
  iVar2 = read_bytecode_value(param_1,param_2,uVar1,&temp_data_buffer,2);
  if (-1 < iVar2) {
    uVar3 = eval_bytecode_instruction(param_1,param_2);
    *(undefined4 *)(param_3 + *param_4 * 8) = 0xf6615ba;
    *(undefined4 *)(param_3 + *param_4 * 8 + 4) = uVar3;
    iVar4 = *param_4;
    *param_4 = iVar4 + 1;
    *(undefined4 *)(param_3 + (iVar4 + 1) * 8) = 0xf6615c3;
    *(undefined4 *)(param_3 + *param_4 * 8 + 4) = uVar1;
    iVar4 = *param_4;
    *param_4 = iVar4 + 1;
    *(undefined4 *)(param_3 + (iVar4 + 1) * 8) = 0xf661fe4;
    *(int *)(param_3 + *param_4 * 8 + 4) = iVar2;
    *param_4 = *param_4 + 1;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void fileChanged(int param_1,char *param_2)

{
  int iVar1;
  int iVar2;
  undefined4 uVar3;
  stat sStack_90;
  char *pcStack_8;
  
  iVar1 = validate_directory_access();
  if (iVar1 != 0) {
    pcStack_8 = (char *)build_path_string(0,param_1);
    strcat(pcStack_8,param_2);
    iVar2 = lstat(pcStack_8,&sStack_90);
    if (-1 < iVar2) {
      if (((sStack_90.st_nlink != *(__nlink_t *)(iVar1 + 8)) ||
          (sStack_90.st_blksize != *(int *)(iVar1 + 0xc))) ||
         (sStack_90.st_mtim.tv_sec != *(int *)(iVar1 + 0x10))) {
        *(int *)(param_1 + 0x1c) =
             (*(int *)(param_1 + 0x1c) + sStack_90.st_blksize) - *(int *)(iVar1 + 0xc);
        uVar3 = calculate_layout_position(param_1);
        *(undefined4 *)(param_1 + 0x24) = uVar3;
        *(__nlink_t *)(iVar1 + 8) = sStack_90.st_nlink;
        *(__blksize_t *)(iVar1 + 0xc) = sStack_90.st_blksize;
        *(__time_t *)(iVar1 + 0x10) = sStack_90.st_mtim.tv_sec;
        uVar3 = FUN_00433b44(pcStack_8);
        *(undefined4 *)(iVar1 + 0x20) = uVar3;
        if (window_width < *(int *)(iVar1 + 0xc)) {
          window_width = *(int *)(iVar1 + 0xc);
        }
        if (window_height < *(int *)(param_1 + 0x1c)) {
          window_height = *(int *)(param_1 + 0x1c);
        }
        update_directory_bounds(iVar1);
        FUN_00412234(param_1);
                    // WARNING: Bad instruction - Truncating control flow here
        halt_baddata();
      }
      *(byte *)(iVar1 + 0x29) = *(byte *)(iVar1 + 0x29) | 0x80;
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void parse_typed_value(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  int unaff_gp;
  
  (**(code **)(unaff_gp + -0x7b38))(param_1,param_2,0);
  (**(code **)(unaff_gp + -0x7e14))(param_1,param_3,param_4);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void FAMOpen2(int *param_1,int param_2)

{
  int iVar1;
  __uid_t _Var2;
  __gid_t _Var3;
  size_t sVar4;
  char acStack_cc [200];
  int iStack_4;
  
  FUN_0043ace4();
  iStack_4 = FUN_0043b178(0);
  param_1[1] = iStack_4;
  iVar1 = FUN_0043b1c8(iStack_4,0x7f000001,0x5f75a,1);
  *param_1 = iVar1;
  if ((-1 < iVar1) && (param_2 != 0)) {
    _Var2 = getuid();
    _Var3 = getgid();
    sprintf(acStack_cc,s_dN0__d__d__s_10009e47 + 1,_Var2,_Var3,param_2);
    sVar4 = strlen(acStack_cc);
    write_data_buffer(iStack_4,*param_1,acStack_cc,sVar4 + 1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void readMark(FILE *param_1)

{
  size_t sVar1;
  undefined1 auStack_43c [56];
  short local_404 [2];
  undefined1 auStack_400 [1024];
  
  sVar1 = fread(local_404,2,1,param_1);
  if (sVar1 != 1) {
    fprintf((FILE *)0xfb52904,"syntax error in reading mark from database\n");
                    // WARNING: Subroutine does not return
    exit(1);
  }
  sVar1 = fread(auStack_400,1,(int)local_404[0],param_1);
  if (sVar1 != (int)local_404[0]) {
    fprintf((FILE *)0xfb52904,"syntax error in reading mark name from database\n");
                    // WARNING: Subroutine does not return
    exit(1);
  }
  auStack_400[local_404[0]] = 0;
  FUN_0042ec00(auStack_43c,param_1);
  FUN_0042ef04(auStack_400,auStack_43c);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void readPosition(undefined2 *param_1,FILE *param_2)

{
  size_t sVar1;
  undefined4 uVar2;
  undefined1 auStack_430 [1024];
  undefined4 uStack_30;
  undefined4 uStack_2c;
  undefined4 uStack_28;
  undefined4 uStack_24;
  undefined4 uStack_20;
  undefined4 uStack_1c;
  undefined4 uStack_18;
  undefined4 uStack_14;
  undefined4 uStack_10;
  undefined2 uStack_c;
  undefined2 uStack_a;
  ushort uStack_8;
  ushort uStack_6;
  ushort uStack_4;
  undefined1 uStack_2;
  
  sVar1 = fread(&uStack_30,0x30,1,param_2);
  if (sVar1 != 1) {
    fprintf((FILE *)0xfb52904,"syntax error in reading position from database\n");
                    // WARNING: Subroutine does not return
    exit(1);
  }
  *(undefined4 *)(param_1 + 4) = uStack_30;
  *(undefined4 *)(param_1 + 6) = uStack_2c;
  *(undefined4 *)(param_1 + 8) = uStack_28;
  *(undefined4 *)(param_1 + 0xc) = uStack_24;
  *(undefined4 *)(param_1 + 0xe) = uStack_20;
  *(undefined4 *)(param_1 + 0x10) = uStack_1c;
  *(undefined4 *)(param_1 + 0x14) = uStack_18;
  *(undefined4 *)(param_1 + 0x16) = uStack_14;
  *(undefined4 *)(param_1 + 0x18) = uStack_10;
  *param_1 = uStack_c;
  *(undefined1 *)(param_1 + 0x1a) = 0;
  param_1[1] = uStack_a;
  *(undefined1 *)(param_1 + 0x1a) = uStack_2;
  if (uStack_8 == 0) {
    *(undefined4 *)(param_1 + 2) = 0;
  }
  else {
    sVar1 = fread(auStack_430,1,(uint)uStack_8,param_2);
    if (sVar1 != uStack_8) {
      fprintf((FILE *)0xfb52904,"syntax error in reading position warpdp from database\n");
                    // WARNING: Subroutine does not return
      exit(1);
    }
    uVar2 = get_path_entry(auStack_430);
    *(undefined4 *)(param_1 + 2) = uVar2;
    auStack_430[uStack_8] = 0;
  }
  if (uStack_6 == 0) {
    *(undefined4 *)(param_1 + 10) = 0;
  }
  else {
    sVar1 = fread(auStack_430,1,(uint)uStack_6,param_2);
    if (sVar1 != uStack_6) {
      fprintf((FILE *)0xfb52904,"syntax error in reading position selecteddp from database\n");
                    // WARNING: Subroutine does not return
      exit(1);
    }
    auStack_430[uStack_6] = 0;
    uVar2 = get_path_entry();
    *(undefined4 *)(param_1 + 10) = uVar2;
  }
  if (uStack_4 == 0) {
    *(undefined4 *)(param_1 + 0x12) = 0;
  }
  else {
    sVar1 = fread(auStack_430,1,(uint)uStack_4,param_2);
    if (sVar1 != uStack_4) {
      fprintf((FILE *)0xfb52904,"syntax error in reading position selectedfp from database\n");
                    // WARNING: Subroutine does not return
      exit(1);
    }
    auStack_430[uStack_4] = 0;
    if (*(int *)(param_1 + 10) == 0) {
      *(undefined4 *)(param_1 + 0x12) = 0;
    }
    else {
      uVar2 = validate_directory_access(*(int *)(param_1 + 10),auStack_430);
      *(undefined4 *)(param_1 + 0x12) = uVar2;
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void scanDatabase(int param_1)

{
  size_t sVar1;
  int iVar2;
  undefined4 uVar3;
  char acStack_400 [1024];
  
  acStack_400[0] = '\0';
  if (*(int *)(param_1 + 0x28) != 0) {
    build_path_string(acStack_400);
  }
  sVar1 = strlen(acStack_400);
  iVar2 = check_directory_flags(param_1,acStack_400,acStack_400 + sVar1,1);
  if (iVar2 != 0) {
    uVar3 = set_status_message("relaying out file system...please wait",0);
    process_pending_events();
    process_child_directory(param_1);
    deleteMessage(uVar3);
    update_display();
  }
  FUN_0041dba0();
  redraw_gl_scene();
  glx_swap_buffers_wrapper();
  refresh_after_change();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setcontext(int param_1,undefined1 param_2)

{
  if ((param_1 == *(int *)(altcontextwindows + 8)) || (param_1 == *(int *)(altcontextwindows + 0xc))
     ) {
    gl_swap_buffers(param_2);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void cIsSuper(int param_1,char *param_2)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = *(undefined4 **)(*(int *)(param_1 + 0x14) + 0x30);
  while ((puVar2 != (undefined4 *)0x0 && (iVar1 = strcmp((char *)*puVar2,param_2), iVar1 != 0))) {
    puVar2 = (undefined4 *)puVar2[1];
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void putword__FPcPl(undefined1 *param_1,undefined1 *param_2)

{
  *param_1 = *param_2;
  param_1[1] = param_2[1];
  param_1[2] = param_2[2];
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void SG_getDefaultDepth(int param_1,undefined4 param_2,int *param_3,int param_4)

{
  int iVar1;
  int iVar2;
  
  if (((param_1 != 0) &&
      (((iVar1 = get_bytecode_context(), param_3 != (int *)0x0 &&
        (iVar2 = *(int *)(iVar1 + 0x24), *param_3 != *(int *)(iVar1 + iVar2 * 4 + 0x3c))) ||
       ((param_4 != 0 && (iVar2 = *(int *)(iVar1 + 0x24), param_4 != iVar2)))))) &&
     ((((param_3 != (int *)0x0 || (*(int *)(iVar1 + iVar2 * 4 + 0x3c) != 3)) &&
       ((param_3 == (int *)0x0 || (*param_3 != 3)))) ||
      ((((param_4 != 0 || (iVar2 != 2)) && (param_4 != 2)) ||
       ((*(int *)(iVar1 + iVar2 * 4 + 0x3c) != 3 || (iVar2 != 2)))))))) {
    FUN_00431a18();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void savePosition(undefined2 *param_1)

{
  *param_1 = *(undefined2 *)(curcontext + 0xc);
  param_1[1] = *(undefined2 *)(curcontext + 0xe);
  *(undefined4 *)(param_1 + 4) = *(undefined4 *)curcontext;
  *(undefined4 *)(param_1 + 6) = *(undefined4 *)(curcontext + 4);
  *(undefined4 *)(param_1 + 8) = *(undefined4 *)(curcontext + 8);
  *(undefined4 *)(param_1 + 2) = *(undefined4 *)(curcontext + 0x3c);
  *(undefined4 *)(param_1 + 10) = *(undefined4 *)(curcontext + 0x44);
  *(undefined4 *)(param_1 + 0x12) = *(undefined4 *)(curcontext + 0x48);
  *(undefined1 *)(param_1 + 0x1a) = curcontext[0xc50];
  if (*(int *)(curcontext + 0x44) != 0) {
    if (*(int *)(curcontext + 0x3c) == 0) {
      *(float *)(param_1 + 0xc) =
           *(float *)curcontext - *(float *)(*(int *)(curcontext + 0x44) + 0x34);
      *(float *)(param_1 + 0xe) =
           *(float *)(curcontext + 4) - *(float *)(*(int *)(curcontext + 0x44) + 0x38);
      *(float *)(param_1 + 0x10) =
           *(float *)(curcontext + 8) - *(float *)(*(int *)(curcontext + 0x44) + 0x24);
      if (*(int *)(curcontext + 0x48) != 0) {
        *(float *)(param_1 + 0x14) =
             *(float *)curcontext -
             (*(float *)(*(int *)(curcontext + 0x44) + 0x34) +
             *(float *)(*(int *)(curcontext + 0x48) + 0x14) *
             *(float *)(*(int *)(curcontext + 0x44) + 0x58));
        *(float *)(param_1 + 0x16) =
             *(float *)(curcontext + 4) -
             (*(float *)(*(int *)(curcontext + 0x44) + 0x38) +
             *(float *)(*(int *)(curcontext + 0x48) + 0x18));
        *(float *)(param_1 + 0x18) =
             *(float *)(curcontext + 8) -
             (*(float *)(*(int *)(curcontext + 0x44) + 0x24) +
             *(float *)(*(int *)(curcontext + 0x48) + 0x1c));
      }
    }
    else if (*(int *)(curcontext + 0x48) != 0) {
      *(float *)(param_1 + 0x14) =
           *(float *)curcontext - *(float *)(*(int *)(curcontext + 0x48) + 0x14);
      *(float *)(param_1 + 0x16) =
           *(float *)(curcontext + 4) - *(float *)(*(int *)(curcontext + 0x48) + 0x18);
                    // WARNING: Bad instruction - Truncating control flow here
      halt_baddata();
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void SG_getUnderlayArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 uVar3;
  int iVar4;
  
  uVar1 = FUN_004314e0(param_1,param_2,&temp_data_buffer,1);
  iVar2 = read_bytecode_value(param_1,param_2,uVar1,&temp_data_buffer,1);
  if (iVar2 < 0) {
    FUN_00431b34(param_1,param_2,param_3,param_4);
  }
  else {
    uVar3 = eval_bytecode_instruction(param_1,param_2);
    *(undefined4 *)(param_3 + *param_4 * 8) = 0xf6615ba;
    *(undefined4 *)(param_3 + *param_4 * 8 + 4) = uVar3;
    iVar4 = *param_4;
    *param_4 = iVar4 + 1;
    *(undefined4 *)(param_3 + (iVar4 + 1) * 8) = 0xf6615c3;
    *(undefined4 *)(param_3 + *param_4 * 8 + 4) = uVar1;
    iVar4 = *param_4;
    *param_4 = iVar4 + 1;
    *(undefined4 *)(param_3 + (iVar4 + 1) * 8) = 0xf661fe4;
    *(int *)(param_3 + *param_4 * 8 + 4) = iVar2;
    *param_4 = *param_4 + 1;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void findDirByFullName(char *param_1)

{
  char cVar1;
  size_t sVar2;
  int iVar3;
  char *pcVar4;
  undefined4 *puVar5;
  
  sVar2 = strlen(param_1);
  if (((uint)topdir[1] < sVar2) &&
     (iVar3 = strncmp(param_1,(char *)*topdir,topdir[1]), puVar5 = topdir, iVar3 == 0)) {
    param_1 = param_1 + topdir[1];
    cVar1 = *param_1;
    while (cVar1 == '/') {
      pcVar4 = param_1 + 1;
      param_1 = param_1 + 1;
      cVar1 = *pcVar4;
    }
    pcVar4 = strchr(param_1,0x2f);
    while (pcVar4 != (char *)0x0) {
      *pcVar4 = '\0';
      puVar5 = (undefined4 *)find_directory_by_path(puVar5,param_1);
      if (puVar5 == (undefined4 *)0x0) {
        *pcVar4 = '/';
        halt_baddata();
      }
      cVar1 = pcVar4[1];
      while (param_1 = pcVar4 + 1, cVar1 == '/') {
        cVar1 = pcVar4[2];
        pcVar4 = param_1;
      }
      pcVar4 = strchr(param_1,0x2f);
    }
    if (*param_1 != '\0') {
      find_directory_by_path(puVar5,param_1);
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dumpMarks(FILE *param_1)

{
  size_t sVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  short asStack_8 [4];
  
  iVar3 = 0;
  if (0 < selection_count) {
    iVar2 = 0;
    do {
      if (_DAT_0fb51f00 == 0) {
        iVar4 = param_1->_flags + -1;
        param_1->_flags = iVar4;
        if (iVar4 < 0) {
          __flsbuf(7,param_1);
        }
        else {
          *param_1->_IO_read_ptr = '\a';
          param_1->_IO_read_ptr = param_1->_IO_read_ptr + 1;
        }
      }
      else {
        __semputc(7,param_1);
      }
      sVar1 = strlen(*(char **)(selection_buffer + iVar2 + 0x38));
      asStack_8[0] = (short)sVar1;
      fwrite(asStack_8,2,1,param_1);
      fwrite(*(void **)(selection_buffer + iVar2 + 0x38),1,(int)asStack_8[0],param_1);
      FUN_0042e9b4(iVar3 * 0x40 + selection_buffer,param_1);
      iVar3 = iVar3 + 1;
      iVar2 = iVar2 + 0x40;
    } while (iVar3 < selection_count);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void init_display_mode(void)

{
  int iVar1;
  int unaff_gp;
  
  if (*(char *)(*(int *)(unaff_gp + -0x7f98) + 0x6f04) == '\0') {
    iVar1 = (**(code **)(unaff_gp + -0x7cbc))(0x11);
    if (iVar1 < 2) {
      *(undefined1 *)(*(int *)(unaff_gp + -0x7f98) + 0x6f00) = 1;
    }
    *(undefined1 *)(*(int *)(unaff_gp + -0x7f98) + 0x6f04) = 1;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void initnames(void)

{
  undefined4 in_a3;
  int unaff_gp;
  int iStackX_0;
  undefined1 auStackX_4 [4];
  undefined1 auStackX_8 [8];
  undefined1 *puVar1;
  undefined4 uVar2;
  
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  __Argv = auStackX_4;
  _DAT_0fb52740 = auStackX_8 + iStackX_0 * 4;
  __Argc = iStackX_0;
  puVar1 = &_mips_gp0_value;
  uVar2 = 0;
  __istart();
  (**(code **)(puVar1 + -0x7c5c))();
  uVar2 = (**(code **)(puVar1 + -0x7ae8))
                    (**(undefined4 **)(puVar1 + -0x760c),**(undefined4 **)(puVar1 + -0x7608),
                     **(undefined4 **)(puVar1 + -0x7f48),in_a3,puVar1,uVar2);
  (**(code **)(puVar1 + -0x7c60))(uVar2);
  return;
}

void main(int param_1,undefined4 *param_2)

{
  undefined4 uVar1;
  undefined4 uVar2;
  int iVar3;
  int iStackX_0;
  undefined4 *puStackX_4;
  undefined1 auStack_124 [100];
  char *pcStack_c0;
  char *pcStack_bc;
  undefined4 uStack_b8;
  undefined4 uStack_ac;
  undefined4 uStack_a8;
  undefined4 uStack_a0;
  undefined4 uStack_9c;
  undefined4 uStack_98;
  undefined4 uStack_94;
  undefined4 uStack_90;
  undefined4 uStack_8c;
  undefined4 uStack_88;
  undefined4 uStack_84;
  undefined4 uStack_80;
  undefined4 uStack_7c;
  undefined4 uStack_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 uStack_68;
  undefined4 uStack_64;
  
  uStack_a0 = 0xf662094;
  uStack_9c = 1;
  iStackX_0 = param_1;
  puStackX_4 = param_2;
  toplevel = XtAppInitialize(&app_context,&app_class_name,&PTR_s__landscape_100000e0,5,&iStackX_0,
                             param_2,&fallback_resources,&uStack_a0,1);
  display = XtDisplay(toplevel);
  FUN_0042b844(toplevel);
  if (iStackX_0 < 2) {
    if (relative_path_flag == '\0') {
      pcStack_bc = getcwd((char *)0x0,0x400);
    }
    else {
      pcStack_bc = ".";
    }
  }
  else if ((2 < iStackX_0) || (pcStack_bc = (char *)puStackX_4[1], *pcStack_bc == '-')) {
    fprintf((FILE *)0xfb52904,
            "usage:  %s [-landscape <landscapeName>] [-relative] \n\t[-db <filename>|-dbdir <directory>] [-noscan] [dirname]\n\n\tKnown landscapes are grass, ocean, desert, space,\nand indigo (similar to grass, but looks better on indigo)\n\t-relative uses relative instead of absolute pathnames\n\t-db or -dbdir control where the database is stored\n\t-noscan avoids rescanning directories when visited\n"
            ,*puStackX_4);
                    // WARNING: Subroutine does not return
    exit(1);
  }
  FUN_0040ae2c();
  FUN_00411674();
  FUN_0040a704();
  glwidget_translations = XtParseTranslationTable(glwidget_translations);
  blankXmString = XmStringCreate(&blank_string_literal,&default_charset);
  emptyXmString = XmStringCreate(&DAT_1000a300,&default_charset);
  uVar1 = XtDisplay(toplevel);
  uVar1 = XmInternAtom(uVar1,"WM_PROTOCOLS",0);
  uVar2 = XmInternAtom(display,"WM_DELETE_WINDOW",0);
  XmAddProtocolCallback(toplevel,uVar1,uVar2,quit_application,0);
  XtAppAddActions(app_context,&xt_actions_table,0x10);
  uStack_a8 = XtCreateManagedWidget("mainw",_DAT_0e3d4f98,toplevel,&uStack_a0,0);
  install_help_callback(uStack_a8,&topHelp);
  uStack_ac = FUN_0040dff8(uStack_a8);
  panel_widget = XtCreateManagedWidget("panel",_DAT_0e3d331c,uStack_a8,&uStack_a0,0);
  uStack_a0 = 0xe3f40cb;
  uStack_98 = 0xe3f4b1d;
  uStack_9c = 1;
  uStack_94 = 1;
  uStack_84 = FUN_0040d3cc(panel_widget,&uStack_a0,2);
  uStack_88 = 0xe3f40f2;
  uStack_a0 = 0xe3f4b1d;
  uStack_98 = 0xe3f3701;
  uStack_90 = 0xe3f40cb;
  uStack_9c = 1;
  uStack_94 = 1;
  uStack_8c = 3;
  copy_button_widget = uStack_84;
  panel_vsep_widget = XtCreateManagedWidget("panelvsep",_DAT_0e3d8f04,panel_widget,&uStack_a0,4);
  init_panel_layout();
  iVar3 = init_display_mode();
  if (iVar3 != 0) {
    display_mode_flags = 0x3000;
  }
  uStack_8c = panel_vsep_widget;
  uStack_a0 = 0xe3f4b1d;
  uStack_98 = 0xe3f40cb;
  uStack_90 = 0xe3f40f2;
  uStack_9c = 1;
  uStack_94 = 3;
  uStack_b8 = XmCreateLabel(panel_widget,"messageHeader",&uStack_a0,3);
  XtManageChild(uStack_b8);
  uStack_a0 = 0xe3f4b1d;
  uStack_98 = 0xe3f40cb;
  uStack_90 = 0xe3f40f2;
  uStack_88 = 0xe3f46dd;
  uStack_9c = 1;
  uStack_94 = 3;
  uStack_84 = 1;
  uStack_8c = uStack_b8;
  message_widget = XmCreateLabel(panel_widget,"message",&uStack_a0,4);
  XtManageChild(message_widget);
  install_help_callback(message_widget,&messageHelp);
  set_status_message("a 3D File System Navigator",0);
  uStack_98 = 0xe3f4ba9;
  uStack_94 = message_widget;
  uStack_a0 = 0xe3f4b1d;
  uStack_70 = 0xe3f469e;
  uStack_7c = panel_vsep_widget;
  uStack_9c = 3;
  uStack_90 = 0xe3f3701;
  uStack_88 = 0xe3f40cb;
  uStack_80 = 0xe3f40f2;
  uStack_78 = 0xe3f46dd;
  uStack_68 = 0xe3f46c4;
  uStack_8c = 1;
  uStack_84 = 3;
  uStack_74 = 1;
  uStack_6c = 0;
  uStack_64 = 0;
  pane_form_widget = XmCreateForm(panel_widget,"paneForm",&uStack_a0,8);
  XtManageChild(pane_form_widget);
  uStack_a0 = 0xe3f4b1d;
  uStack_98 = 0xe3f3701;
  uStack_90 = 0xe3f40cb;
  uStack_88 = 0xe3f46dd;
  uStack_9c = 1;
  uStack_94 = 1;
  uStack_8c = 1;
  uStack_84 = 1;
  context_top_widget = XtCreateManagedWidget(&DAT_1000a384,_DAT_0e3d616c,pane_form_widget,&uStack_a0,4);
  setup_context_widgets();
  XtManageChild(*(undefined4 *)(curcontextwindows + 0xc));
  XmMainWindowSetAreas(uStack_a8,uStack_ac,0,0,0,panel_widget);
  XtRealizeWidget(toplevel);
  XSetErrorHandler(0);
  post_realize_setup(toplevel);
  XtSetSensitive(copy_button_widget,0);
  XtSetSensitive(uStack_ac,0);
  XtSetSensitive(*(undefined4 *)(curcontextwindows + 8),0);
  XtSetSensitive(*(undefined4 *)(curcontextwindows + 0xc),0);
  set_main_gl_window();
  uStack_a0 = 0xe3f4b1d;
  uStack_98 = 0xe3f4ba9;
  uStack_9c = 4;
  uStack_94 = *(undefined4 *)(curcontextwindows + 0x2c);
  uStack_90 = 0xe3f3701;
  uStack_88 = 0xe3f3753;
  uStack_8c = 4;
  uStack_84 = *(undefined4 *)(curcontextwindows + 8);
  uStack_80 = 0xe3f40cb;
  uStack_78 = 0xe3f40f2;
  uStack_7c = 4;
  uStack_74 = *(undefined4 *)(curcontextwindows + 8);
  uStack_70 = 0xe3f46dd;
  uStack_68 = 0xe3f4707;
  uStack_6c = 4;
  uStack_64 = *(undefined4 *)(curcontextwindows + 8);
  FUN_0042aed4(*(undefined4 *)(curcontextwindows + 0xc),&uStack_a0,8);
  load_filetype_rules_wrapper("/usr/lib/filetype/workspace.ctr");
  FUN_00427d54();
  FUN_00433f74();
  FUN_00428b6c();
  if ((*pcStack_bc != '/') && (relative_path_flag == '\0')) {
    pcStack_c0 = getcwd((char *)0x0,0x400);
    strcat(pcStack_c0,"/");
    strcat(pcStack_c0,pcStack_bc);
    pcStack_bc = pcStack_c0;
  }
  FUN_004174d0(pcStack_bc);
  update_display();
  if (initialOverview != '\0') {
    showOverview();
  }
  if ((curcontext[0xc51] == '\0') || (altcontext[0xc51] == '\0')) {
    if (curcontext[0xc51] == '\0') {
      curcontext[0xc51] = 1;
    }
  }
  else {
    FUN_00411230();
  }
  if (initialLegend != '\0') {
    toggle_legend();
  }
  if (initialControls != '\0') {
    show_controls();
  }
  FUN_0040ed40();
  XtSetSensitive(copy_button_widget,1);
  XtSetSensitive(uStack_ac,1);
  XtSetSensitive(*(undefined4 *)(curcontextwindows + 8),1);
  XtSetSensitive(*(undefined4 *)(curcontextwindows + 0xc),1);
  FUN_0042b08c();
  init_database_display();
  setup_fam_monitoring();
  FUN_0042fd50(toplevel);
  do {
    if ((redraw_flag != '\0') && (iVar3 = XtAppPending(app_context), iVar3 == 0)) {
      redraw_gl_scene();
      redraw_flag = '\0';
    }
    XtAppNextEvent(app_context,auStack_124);
    XtDispatchEvent(auStack_124);
  } while( true );
}

void LoadIntlResources(undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  undefined **ppuVar1;
  undefined4 *__ptr;
  undefined4 *puVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  undefined **ppuVar7;
  undefined *puVar8;
  
  __ptr = (undefined4 *)malloc(0xcb0);
  iVar3 = 0;
  ppuVar7 = &PTR_s__SGI_MMX_mwm_nogrmem_10009670;
  iVar5 = 4;
  iVar6 = 8;
  iVar4 = 0xc;
  puVar2 = __ptr;
  do {
    puVar2[1] = 0;
    puVar2[2] = 0xf661c25;
    puVar2[3] = 4;
    puVar2[5] = 0xf661c25;
    puVar2[4] = iVar3;
    iVar3 = iVar3 + 0x10;
    *puVar2 = *ppuVar7;
    puVar8 = ppuVar7[1];
    puVar2[0xb] = iVar5;
    puVar2[0xc] = 0xf661c25;
    puVar2[10] = 4;
    puVar2[9] = 0xf661c25;
    puVar2[8] = 0;
    puVar2[6] = puVar8;
    iVar5 = iVar5 + 0x10;
    puVar2[7] = ppuVar7[2];
    puVar8 = ppuVar7[3];
    puVar2[0x12] = iVar6;
    puVar2[0x13] = 0xf661c25;
    puVar2[0x11] = 4;
    puVar2[0x10] = 0xf661c25;
    puVar2[0xf] = 0;
    puVar2[0xd] = puVar8;
    iVar6 = iVar6 + 0x10;
    puVar2[0xe] = ppuVar7[4];
    puVar8 = ppuVar7[5];
    puVar2[0x19] = iVar4;
    puVar2[0x1a] = 0xf661c25;
    puVar2[0x18] = 4;
    puVar2[0x17] = 0xf661c25;
    puVar2[0x16] = 0;
    puVar2[0x14] = puVar8;
    iVar4 = iVar4 + 0x10;
    puVar2[0x15] = ppuVar7[6];
    ppuVar1 = ppuVar7 + 7;
    ppuVar7 = ppuVar7 + 8;
    puVar2[0x1b] = *ppuVar1;
    puVar2 = puVar2 + 0x1c;
  } while (iVar4 != 0x1dc);
  XtGetSubresources(param_1,_imsgs,param_2,param_3,__ptr,0x74,0,0);
  free(__ptr);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void SG_getMatchingVisual(int param_1,int param_2,int param_3,int *param_4,int param_5,int param_6)

{
  int iVar1;
  int iVar2;
  
  if (param_1 != 0) {
    if (param_2 == 0) {
      param_2 = *(int *)(param_1 + 0x84);
    }
    iVar1 = get_bytecode_context(param_1,param_2);
    iVar2 = 0;
    if (0 < *(int *)(iVar1 + 0x18)) {
      do {
        if ((((param_3 == 0) || (param_3 == *(int *)(*(int *)(iVar1 + 0x14) + iVar2 * 0x28 + 4))) &&
            ((param_4 == (int *)0x0 ||
             (*(int *)(*(int *)(iVar1 + 0x14) + iVar2 * 0x28 + 0x10) == *param_4)))) &&
           ((param_6 == 0 || (param_6 == *(int *)(*(int *)(iVar1 + 0x14) + iVar2 * 0x28 + 0xc))))) {
          if (param_5 == 0) {
            halt_baddata();
          }
          if (param_5 == *(int *)(*(int *)(iVar1 + 0x20) + iVar2 * 4)) {
            halt_baddata();
          }
        }
        iVar2 = iVar2 + 1;
      } while (iVar2 < *(int *)(iVar1 + 0x18));
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void newcontext(uint param_1,char param_2)

{
  int iVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  
  if (param_1 != curcontextid) {
    iVar1 = *(int *)(curcontext + 0x44);
    if (iVar1 != 0) {
      *(byte *)(iVar1 + 0x74) = *(byte *)(iVar1 + 0x74) & 0xdf;
    }
    iVar1 = *(int *)(curcontext + 0x48);
    if (iVar1 != 0) {
      *(byte *)(iVar1 + 0x28) = *(byte *)(iVar1 + 0x28) & 0xef;
    }
    curcontext = context + param_1 * 0xc54;
    curcontextwindows = contextwindows + param_1 * 0x38;
    altcontext = context + (1 - param_1) * 0xc54;
    altcontextwindows = contextwindows + (1 - param_1) * 0x38;
    curcontextflag = 1 << (param_1 & 0x1f);
    iVar1 = *(int *)(context + param_1 * 0xc54 + 0x44);
    curcontextid = param_1;
    if (iVar1 != 0) {
      *(byte *)(iVar1 + 0x74) = *(byte *)(iVar1 + 0x74) | 0x20;
    }
    iVar1 = *(int *)(curcontext + 0x48);
    if (iVar1 != 0) {
      *(byte *)(iVar1 + 0x28) = *(byte *)(iVar1 + 0x28) | 0x10;
    }
    if (param_2 == '\0') {
      uVar2 = XtDisplay(*(undefined4 *)(altcontextwindows + 0x28));
      uVar3 = XtWindow(*(undefined4 *)(altcontextwindows + 0x28));
      XMapWindow(uVar2,uVar3);
      uVar2 = XtDisplay(*(undefined4 *)(curcontextwindows + 0x28));
      uVar3 = XtWindow(*(undefined4 *)(curcontextwindows + 0x28));
      XUnmapWindow(uVar2,uVar3);
      update_widget_state();
      refresh_display();
      curcontext[0xc53] = 0;
      altcontext[0xc53] = 1;
      ui_layout_setup_wrapper();
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void doIt(char param_1)

{
  undefined4 uVar1;
  
  if (*(int *)(curcontext + 0x48) == 0) {
    if ((*(int *)(curcontext + 0x44) != 0) &&
       (*(int *)(curcontext + 0x3c) != *(int *)(curcontext + 0x44))) {
      do_warp();
    }
  }
  else {
    uVar1 = 4;
    if (param_1 != '\0') {
      uVar1 = 5;
    }
    FUN_0041e260(*(undefined4 *)(curcontext + 0x44),*(int *)(curcontext + 0x48),uVar1,
                 param_1 == '\0',&DAT_1000b4a0,"opening");
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void usystem(undefined4 param_1)

{
  __pid_t _Var1;
  int iVar2;
  itimerval iStack_2c;
  itimerval iStack_1c;
  undefined1 auStack_4 [4];
  
  _Var1 = fork();
  if (_Var1 != 0) {
    if (-1 < _Var1) {
      iVar2 = wait(auStack_4);
      while ((iVar2 != _Var1 && ((iVar2 != -1 || (_DAT_0fb52720 == 4))))) {
        iVar2 = wait(auStack_4);
      }
    }
                    // WARNING: Bad instruction - Truncating control flow here
    halt_baddata();
  }
  setpgrp();
  iVar2 = 3;
  do {
    close(iVar2);
    iVar2 = iVar2 + 1;
  } while (iVar2 != 100);
  close(0);
  iVar2 = open("/dev/null",2);
  dup2(iVar2,0);
  if (2 < iVar2) {
    close(iVar2);
  }
  ioctl(0,0x5471,0);
  iStack_1c.it_interval.tv_sec = 0;
  iStack_1c.it_interval.tv_usec = 0;
  iStack_1c.it_value.tv_sec = 0;
  iStack_1c.it_value.tv_usec = 0;
  setitimer(ITIMER_REAL,&iStack_1c,&iStack_2c);
  alarm(0);
  execl(s__bin_sh_10009640,&DAT_10009648,&DAT_1000964c,param_1,0);
                    // WARNING: Subroutine does not return
  _exit(0x7f);
}

void SG_getMaxDepth(int param_1,int param_2,int *param_3,int param_4)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  
  if (param_1 != 0) {
    if (param_2 == 0) {
      param_2 = *(int *)(param_1 + 0x84);
    }
    iVar1 = get_bytecode_context(param_1,param_2);
    iVar4 = 0;
    if (param_4 == 0) {
      param_4 = *(int *)(iVar1 + 0x24);
    }
    iVar2 = 0;
    if (0 < *(int *)(iVar1 + 0x18)) {
      do {
        if ((((param_3 == (int *)0x0) ||
             (*(int *)(*(int *)(iVar1 + 0x14) + iVar2 * 0x28 + 0x10) == *param_3)) &&
            (param_4 == *(int *)(*(int *)(iVar1 + 0x20) + iVar2 * 4))) &&
           (iVar3 = *(int *)(*(int *)(iVar1 + 0x14) + iVar2 * 0x28 + 0xc), iVar4 < iVar3)) {
          iVar4 = iVar3;
        }
        iVar2 = iVar2 + 1;
      } while (iVar2 < *(int *)(iVar1 + 0x18));
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void message(undefined4 param_1,int param_2)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  undefined4 uStack_54;
  undefined4 uStack_50;
  
  puVar1 = (undefined4 *)XtMalloc(0xc);
  uVar2 = XmStringCreateSimple(param_1);
  *puVar1 = uVar2;
  *(undefined1 *)(puVar1 + 2) = 0;
  puVar1[1] = current_directory_node;
  uStack_54 = 0xe3f40b5;
  uStack_50 = *puVar1;
  current_directory_node = puVar1;
  XtSetValues(message_widget,&uStack_54,1);
  if (param_2 != 0) {
    XtAppAddTimeOut(app_context,param_2,deleteMessage,puVar1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void third_traversal(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  undefined4 uVar1;
  undefined4 unaff_000010a0;
  
  uVar1 = calculate_layout_position();
  *(undefined4 *)(param_1 + 0x24) = uVar1;
  *(float *)(param_1 + 0x34) = (float)(double)CONCAT44(unaff_000010a0,param_4);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void calculate_file_view(int param_1)

{
  undefined4 uVar1;
  
  uVar1 = FUN_00411804();
  *(undefined4 *)(param_1 + 0x1c) = uVar1;
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void WriteToServer__6ClientFiPcT1(undefined4 param_1,int param_2,void *param_3,size_t param_4)

{
  ssize_t sVar1;
  size_t sStackX_c;
  undefined1 auStack_4 [4];
  
  sStackX_c = param_4;
  putword__FPcPl(auStack_4,&sStackX_c);
  sVar1 = write(param_2,auStack_4,4);
  if (sVar1 == 4) {
    write(param_2,param_3,sStackX_c);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void initResources(undefined4 param_1)

{
  int iVar1;
  undefined4 uVar2;
  
  XtAppAddConverter(app_context,0xf661c25,"CpColor",FUN_0042b6f8,0,0);
  XtGetApplicationResources(param_1,&landscape_name,&PTR_s_landscape_10008918,1,0,0);
  if (landscape_name == (char *)0x0) {
    iVar1 = getgdesc(9);
    if (iVar1 < 4) {
      landscape_name = "indigo";
    }
    else {
      landscape_name = "grass";
    }
  }
  if (landscape_name == (char *)0x0) {
    XtGetApplicationResources(param_1,&fsn_resources,&PTR_s_noscan_10007c30,0x76,0,0);
  }
  else {
    uVar2 = XtCreateWidget(landscape_name,_DAT_0f6d07d4,param_1,0,0);
    XtGetApplicationResources(uVar2,&fsn_resources,&PTR_s_noscan_10007c30,0x76,0,0);
    XtDestroyWidget(uVar2);
  }
  FUN_00433904(param_1,&DAT_10012c44,&DAT_10012c4c);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void preExit(void)

{
  if (fsn_resources == '\0') {
    post_realize_setup(toplevel);
    FUN_00427de0();
    refresh_after_change();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void error(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uStack_54;
  undefined4 uStack_50;
  undefined4 uStack_4;
  
  uStack_50 = XmStringCreate(param_1,&default_charset);
  uStack_54 = 0xe3f42e0;
  uStack_4 = uStack_50;
  uVar1 = XmCreateErrorDialog(toplevel,"error",&uStack_54,1);
  uVar2 = XmMessageBoxGetChild(uVar1,2);
  XtUnmanageChild(uVar2);
  uVar2 = XmMessageBoxGetChild(uVar1,7);
  XtUnmanageChild(uVar2);
  XtAddCallback(uVar1,0xf6615c9,FUN_00410f30,0);
  XtManageChild(uVar1);
  XmStringFree(uStack_4);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void set_camera_lookat(double param_1,double param_2)

{
  int iVar1;
  int *piVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int unaff_gp;
  undefined4 in_register_00001040;
  undefined4 in_register_00001080;
  undefined4 in_stack_00000014;
  short in_stack_0000001a;
  short in_stack_0000001e;
  int in_stack_00000020;
  undefined4 in_stack_00000024;
  undefined4 in_stack_00000028;
  
  (*(code *)(*(int *)(unaff_gp + -0x7fe8) + -0xeb0))(0,0);
  (**(code **)(unaff_gp + -0x7ae4))();
  piVar2 = *(int **)(unaff_gp + -0x7684);
  iVar1 = *piVar2;
  if (in_stack_00000020 == *(int *)(iVar1 + 0x3c)) {
    *(float *)(*(int *)(unaff_gp + -0x7f94) + 0x65f0) = (float)param_1;
    *(float *)(*(int *)(unaff_gp + -0x7f94) + 0x65f4) = (float)param_2;
    *(float *)(*(int *)(unaff_gp + -0x7f94) + 0x65f8) =
         (float)(double)CONCAT44(in_register_00001080,in_stack_00000014);
    *(short *)(*(int *)(unaff_gp + -0x7f94) + 0x6608) = in_stack_0000001a;
    *(short *)(*(int *)(unaff_gp + -0x7f94) + 0x660a) = in_stack_0000001e;
    *(bool *)(*(int *)(unaff_gp + -0x7f94) + 0x660c) = in_stack_0000001a != *(short *)(iVar1 + 0xc);
    *(bool *)(*(int *)(unaff_gp + -0x7f94) + 0x660d) = in_stack_0000001e != *(short *)(iVar1 + 0xe);
    if (in_stack_00000020 == 0) {
                    // WARNING: Bad instruction - Truncating control flow here
      halt_baddata();
    }
    *(undefined1 *)(*(int *)(unaff_gp + -0x7f94) + 0x660e) = 0;
    (**(code **)(unaff_gp + -0x7b2c))(*(int *)(unaff_gp + -0x7f94) + 0x6610,0);
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x661c) = in_stack_00000024;
    iVar4 = *(int *)(unaff_gp + -0x75dc);
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6620) = in_stack_00000028;
    iVar5 = *(int *)(unaff_gp + -0x7fe8);
    iVar1 = *(int *)(unaff_gp + -0x7fe8);
    iVar3 = *(int *)(unaff_gp + -0x7f94);
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6618) = *(undefined4 *)(iVar4 + 0x58);
    (*(code *)(iVar5 + -0xeb0))(iVar1 + -0x450,iVar3 + 0x65f0);
  }
  else {
    if (*(char *)(*(int *)(unaff_gp + -0x75dc) + 2) != '\0') {
      (**(code **)(unaff_gp + -0x7aac))();
      piVar2 = *(int **)(unaff_gp + -0x7684);
      iVar1 = *piVar2;
    }
    *(int *)(iVar1 + 0x3c) = in_stack_00000020;
    if (in_stack_00000020 != 0) {
      (**(code **)(unaff_gp + -0x79c4))();
      piVar2 = *(int **)(unaff_gp + -0x7684);
    }
    *(float *)*piVar2 = (float)param_1;
    *(float *)(*piVar2 + 4) = (float)param_2;
    *(float *)(*piVar2 + 8) = (float)(double)CONCAT44(in_register_00001040,in_stack_00000014);
    *(short *)(*piVar2 + 0xc) = in_stack_0000001a;
    (**(code **)(unaff_gp + -0x7ad8))();
    *(short *)(**(int **)(unaff_gp + -0x7684) + 0xe) = in_stack_0000001e;
    (**(code **)(unaff_gp + -0x7ad4))();
    (**(code **)(unaff_gp + -0x7acc))();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void rescaleOverview(void)

{
  float fVar1;
  byte in_fcsr;
  undefined4 uStack_50;
  int iStack_4c;
  undefined4 uStack_48;
  int iStack_44;
  
  if (overviewActive != '\0') {
    uStack_48 = 0xf66160a;
    fVar1 = (maxx - minx) * window_scale_x;
    uStack_50 = 0xf661888;
    if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
      fVar1 = ROUND(fVar1);
    }
    else {
      fVar1 = FLOOR(fVar1);
    }
    iStack_4c = (int)fVar1;
    fVar1 = (maxy - miny) * window_scale_y;
    if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
      fVar1 = ROUND(fVar1);
    }
    else {
      fVar1 = FLOOR(fVar1);
    }
    iStack_44 = (int)fVar1;
    XtSetValues(overview_gl_widget,&uStack_50,2);
    glx_switch_context_wrapper();
    ortho2(minx,maxx);
    refresh_display();
    begin_overview_render();
    ortho2(minx,maxx);
    draw_overview_content();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void makePatterns(void)

{
  int iVar1;
  undefined *puVar2;
  
  defpattern(1,0x10,&DAT_10007908);
  iVar1 = 0;
  puVar2 = &DAT_10007928;
  do {
    defpattern((iVar1 + 2) * 0x10000 >> 0x10,0x10,puVar2);
    iVar1 = iVar1 + 1;
    puVar2 = puVar2 + 0x20;
  } while (iVar1 != 3);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void DoClientIn__6ClientFP11ServerEntry(undefined4 param_1,int *param_2)

{
  ssize_t sVar1;
  int *piVar2;
  int *piVar3;
  int *piVar4;
  int iVar5;
  int iStack_4;
  
  if (param_2[4] == 0) {
    piVar2 = (int *)param_2[5];
    piVar4 = param_2 + 7;
    if (piVar4 != piVar2) {
      piVar3 = piVar4;
      if (piVar2 < (int *)param_2[6]) {
        do {
          *(undefined1 *)piVar3 = *(undefined1 *)piVar2;
          piVar2 = (int *)((int)piVar2 + 1);
          piVar3 = (int *)((int)piVar3 + 1);
        } while (piVar2 < (int *)param_2[6]);
      }
      param_2[5] = (int)piVar4;
      param_2[6] = (int)piVar3;
    }
    sVar1 = read(*param_2,(void *)param_2[6],(int)param_2 + (0xbd4 - param_2[6]));
    if (sVar1 != -1) {
      if (sVar1 == 0) {
        param_2[0x5e7] = 1;
      }
      else {
        iVar5 = param_2[6];
        param_2[6] = iVar5 + sVar1;
        if (((iVar5 + sVar1) - (int)param_2) + -0x1c < 3000) {
          param_2[4] = 0;
        }
        else {
          param_2[4] = 1;
        }
        if ((uint)(param_2[6] - param_2[5]) < 4) {
          param_2[3] = 0;
        }
        else {
          getword__FPcPl(param_2[5],&iStack_4);
          if ((uint)(param_2[6] - param_2[5]) < iStack_4 + 4U) {
            param_2[3] = 0;
          }
          else {
            param_2[3] = 1;
          }
        }
      }
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void checkValidSelections(void)

{
  if ((*(int *)(curcontext + 0x48) != 0) && (-1 < *(int *)(*(int *)(curcontext + 0x48) + 0x28) << 5)
     ) {
    clear_current_selection();
  }
  if ((*(int *)(curcontext + 0x44) != 0) && (-1 < *(int *)(*(int *)(curcontext + 0x44) + 0x74) << 3)
     ) {
    clear_marked_state();
  }
  if ((*(int *)(curcontext + 0x3c) != 0) && (-1 < *(int *)(*(int *)(curcontext + 0x3c) + 0x74) << 3)
     ) {
    reset_eye();
  }
  if (altcontext[0xc51] != '\0') {
    gl_swap_buffers(1);
    if ((*(int *)(curcontext + 0x48) != 0) &&
       (-1 < *(int *)(*(int *)(curcontext + 0x48) + 0x28) << 5)) {
      clear_current_selection();
    }
    if ((*(int *)(curcontext + 0x44) != 0) &&
       (-1 < *(int *)(*(int *)(curcontext + 0x44) + 0x74) << 3)) {
      clear_marked_state();
    }
    if ((*(int *)(curcontext + 0x3c) != 0) &&
       (-1 < *(int *)(*(int *)(curcontext + 0x3c) + 0x74) << 3)) {
      reset_eye();
    }
    gl_swap_buffers(1);
  }
  update_widget_state();
  FUN_0041c3e4();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
