// navigation.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/navigation.h"

void landscapeZoomToFile(int param_1,int param_2)

{
  double dVar1;
  ulonglong in_f4;
  float fVar2;
  
  if (param_1 != 0) {
    if (param_2 == 0) {
      dVar1 = (double)*(float *)(param_1 + 0x3c) / (double)(in_f4 & 0xffffffff00000000) +
              (double)DAT_10017518;
      set_camera_lookat((double)*(float *)(param_1 + 0x34) -
                   (double)*(float *)(curcontext + 0x14) * dVar1,
                   (double)*(float *)(param_1 + 0x38) -
                   (double)*(float *)(curcontext + 0x18) * dVar1);
    }
    else {
      if (DAT_10017495 == '\0') {
        fVar2 = *(float *)(param_2 + 0x14);
      }
      else {
        fVar2 = *(float *)(param_2 + 0x14);
      }
      set_camera_lookat(((double)*(float *)(param_1 + 0x34) +
                   (double)fVar2 * (double)*(float *)(param_1 + 0x58)) -
                   (double)*(float *)(curcontext + 0x14) * (double)DAT_10017524,
                   ((double)*(float *)(param_1 + 0x38) + (double)*(float *)(param_2 + 0x18)) -
                   (double)*(float *)(curcontext + 0x18) * (double)DAT_10017524);
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void zoomPosition(undefined4 param_1)

{
  int iVar1;
  char cStack_1d;
  int iStack_1c;
  int iStack_18;
  undefined1 auStack_14 [4];
  undefined1 auStack_10 [4];
  float fStack_c;
  float fStack_8;
  undefined1 auStack_4 [2];
  undefined1 auStack_2 [2];
  
  iVar1 = FUN_0042dfb4(param_1,auStack_2,auStack_4,&fStack_8,&fStack_c,auStack_10,auStack_14,
                       &iStack_18,&iStack_1c,&cStack_1d);
  if (iVar1 != 0) {
    if (iStack_18 != *(int *)(curcontext + 0x44)) {
      if (iStack_18 == 0) {
        FUN_0041d54c(0);
      }
      else {
        FUN_0041d69c();
      }
    }
    if (iStack_1c != *(int *)(curcontext + 0x48)) {
      if (iStack_1c == 0) {
        FUN_0041d920(0);
      }
      else {
        FUN_0041da44();
      }
    }
    if (cStack_1d == '\0') {
      curcontext[0xc50] = 0;
      set_camera_lookat((double)fStack_8,(double)fStack_c);
    }
    else {
      set_camera_lookat((double)fStack_8,(double)fStack_c);
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void zoomToSelection(void)

{
  if (*(int *)(curcontext + 0x3c) == 0) {
    FUN_00427870(*(undefined4 *)(curcontext + 0x44),*(undefined4 *)(curcontext + 0x48));
  }
  else {
    FUN_0041aeec(*(undefined4 *)(curcontext + 0x44),*(undefined4 *)(curcontext + 0x48));
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void findbestfile(char *param_1,int *param_2,undefined4 *param_3)

{
  char cVar1;
  size_t sVar2;
  int iVar3;
  char *pcVar4;
  undefined4 *puVar5;
  undefined4 *puVar6;
  undefined4 *puVar7;
  undefined4 *puStack_110;
  int *piStack_10c;
  char *apcStack_108 [30];
  char **ppcStack_90;
  char *apcStack_8c [30];
  char **appcStack_14 [5];
  
  *param_2 = 0;
  *param_3 = 0;
  sVar2 = strlen(param_1);
  if (sVar2 <= (uint)topdir[1]) {
    sVar2 = strlen(param_1);
    iVar3 = strncmp(param_1,(char *)*topdir,sVar2);
    if (iVar3 != 0) {
      halt_baddata();
    }
    *param_2 = (int)topdir;
    halt_baddata();
  }
  iVar3 = strncmp(param_1,(char *)*topdir,topdir[1]);
  puVar5 = topdir;
  if (iVar3 != 0) {
    halt_baddata();
  }
  param_1 = param_1 + topdir[1];
  cVar1 = *param_1;
  while (cVar1 == '/') {
    pcVar4 = param_1 + 1;
    param_1 = param_1 + 1;
    cVar1 = *pcVar4;
  }
  pcVar4 = strchr(param_1,0x2f);
  while (pcVar4 != (char *)0x0) {
    *pcVar4 = '\0';
    puVar5 = (undefined4 *)FUN_00413610(puVar5,param_1);
    if (puVar5 == (undefined4 *)0x0) {
      *pcVar4 = '/';
      halt_baddata();
    }
    cVar1 = pcVar4[1];
    while (param_1 = pcVar4 + 1, cVar1 == '/') {
      cVar1 = pcVar4[2];
      pcVar4 = param_1;
    }
    pcVar4 = strchr(param_1,0x2f);
  }
  if (*param_1 == '\0') {
    *param_2 = (int)puVar5;
    halt_baddata();
  }
  if (puVar5[3] != 0) {
    ppcStack_90 = apcStack_108;
    apcStack_108[0] = param_1;
    iVar3 = FUN_0042a9b4(&ppcStack_90,puVar5[4],puVar5[3],4,compare_files,&puStack_110);
    if (iVar3 != 0) {
      *param_2 = (int)puVar5;
      *param_3 = *puStack_110;
      halt_baddata();
    }
    if (puStack_110 != (undefined4 *)0x0) {
      puVar7 = (undefined4 *)*puStack_110;
      iVar3 = puVar5[5];
      goto LAB_0042ad4c;
    }
  }
  puVar7 = (undefined4 *)0x0;
  iVar3 = puVar5[5];
LAB_0042ad4c:
  if (iVar3 == 0) {
    puVar6 = (undefined4 *)0x0;
  }
  else {
    apcStack_8c[0] = param_1;
    appcStack_14[0] = apcStack_8c;
    iVar3 = FUN_0042a9b4(appcStack_14,puVar5[6],puVar5[5],4,compare_dirs,&piStack_10c);
    if (iVar3 != 0) {
      *param_2 = *piStack_10c;
      halt_baddata();
    }
    puVar6 = (undefined4 *)0x0;
    if (piStack_10c != (int *)0x0) {
      puVar6 = (undefined4 *)*piStack_10c;
    }
  }
  if ((puVar6 != (undefined4 *)0x0) && (puVar7 != (undefined4 *)0x0)) {
    iVar3 = strcmp((char *)*puVar7,(char *)*puVar6);
    if (iVar3 < 0) {
      puVar6 = (undefined4 *)0x0;
    }
    else {
      puVar7 = (undefined4 *)0x0;
    }
  }
  if (puVar7 == (undefined4 *)0x0) {
    if (puVar6 != (undefined4 *)0x0) {
      sVar2 = strlen(param_1);
      iVar3 = strncmp((char *)*puVar6,param_1,sVar2);
      if (iVar3 == 0) {
        *param_2 = (int)puVar6;
      }
    }
  }
  else {
    sVar2 = strlen(param_1);
    iVar3 = strncmp((char *)*puVar7,param_1,sVar2);
    if (iVar3 == 0) {
      *param_2 = (int)puVar5;
      *param_3 = puVar7;
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void findzoom(void)

{
  if (*(int *)(curcontext + 0x3c) == 0) {
    FUN_004268e0();
  }
  else {
    FUN_0041a648();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void do_warp(int param_1)

{
  undefined1 local_c [4];
  float local_8;
  float local_4;
  
  set_main_gl_window();
  save_matrix_state();
  if (param_1 == 0) {
    if (*(int *)(curcontext + 0x3c) == 0) {
      set_camera_lookat((double)view_init_x,(double)view_init_y,0,&local_4);
    }
    else {
      FUN_00426e34(*(int *)(curcontext + 0x3c),&local_4,&local_8,local_c);
      set_camera_lookat((double)local_4,(double)local_8);
    }
  }
  else {
    set_camera_lookat((double)DAT_100174bc,(double)DAT_100174c0);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void pushzoom(void)

{
  undefined4 *puVar1;
  int iVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  undefined4 *puVar5;
  undefined4 auStack_38 [12];
  undefined4 auStack_8 [2];
  
  FUN_0042dc64(auStack_38);
  iVar2 = equalPositions(auStack_38,
                         *(int *)(curcontextwindows + 0x34) + *(int *)(curcontext + 0x40) * 0x38);
  if (iVar2 == 0) {
    *(int *)(curcontext + 0x40) = *(int *)(curcontext + 0x40) + 1;
    iVar2 = *(int *)(curcontext + 0x40);
    if (9 < iVar2) {
      *(undefined4 *)(curcontext + 0x40) = 0;
      iVar2 = *(int *)(curcontext + 0x40);
    }
    puVar1 = (undefined4 *)(*(int *)(curcontextwindows + 0x34) + iVar2 * 0x38);
    puVar5 = auStack_38;
    do {
      puVar4 = puVar5;
      puVar3 = puVar1;
      puVar5 = puVar4 + 3;
      *puVar3 = *puVar4;
      puVar3[1] = puVar4[1];
      puVar3[2] = puVar4[2];
      puVar1 = puVar3 + 3;
    } while (puVar5 != auStack_8);
    puVar3[3] = *puVar5;
    puVar3[4] = puVar4[4];
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void popzoom(void)

{
  int iVar1;
  int iVar2;
  
  iVar2 = 0;
  iVar1 = FUN_0042e670(*(int *)(curcontextwindows + 0x34) + *(int *)(curcontext + 0x40) * 0x38);
  if (iVar1 == 0) {
    do {
      *(int *)(curcontext + 0x40) = *(int *)(curcontext + 0x40) + -1;
      iVar1 = *(int *)(curcontext + 0x40);
      if (iVar1 < 0) {
        *(undefined4 *)(curcontext + 0x40) = 9;
        iVar1 = *(int *)(curcontext + 0x40);
      }
      iVar2 = iVar2 + 1;
      iVar1 = FUN_0042e670(*(int *)(curcontextwindows + 0x34) + iVar1 * 0x38);
    } while ((iVar1 == 0) && (iVar2 != 10));
  }
  *(int *)(curcontext + 0x40) = *(int *)(curcontext + 0x40) + -1;
  if (*(int *)(curcontext + 0x40) < 0) {
    *(undefined4 *)(curcontext + 0x40) = 9;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void get_warp_entry(int param_1,float *param_2,float *param_3)

{
  uint in_register_00001000;
  
  *param_2 = (float)((double)*(float *)(param_1 + 0x34) -
                    (double)*(float *)(curcontext + 0x14) *
                    ((double)*(float *)(param_1 + 0x3c) /
                     (double)((ulonglong)in_register_00001000 << 0x20) + (double)DAT_10017518));
  *param_3 = (float)((double)*(float *)(param_1 + 0x38) -
                    (double)*(float *)(curcontext + 0x18) *
                    ((double)*(float *)(param_1 + 0x3c) /
                     (double)((ulonglong)in_register_00001000 << 0x20) + (double)DAT_10017518));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void zoomto(double param_1,double param_2)

{
  undefined4 in_register_00001040;
  undefined4 in_register_00001080;
  undefined4 in_stack_00000014;
  short in_stack_0000001a;
  short in_stack_0000001e;
  int in_stack_00000020;
  undefined4 in_stack_00000024;
  undefined4 in_stack_00000028;
  
  FUN_0040f150(0,0);
  set_main_gl_window();
  if (in_stack_00000020 == *(int *)(curcontext + 0x3c)) {
    zoom_stack_pointer = (float)param_1;
    zoom_stack_size = (float)param_2;
    zoom_stack_capacity = (float)(double)CONCAT44(in_register_00001080,in_stack_00000014);
    camera_position_x = in_stack_0000001a;
    camera_position_y = in_stack_0000001e;
    camera_position_z = in_stack_0000001a != *(short *)(curcontext + 0xc);
    DAT_1001660d = in_stack_0000001e != *(short *)(curcontext + 0xe);
    if (in_stack_00000020 == 0) {
                    // WARNING: Bad instruction - Truncating control flow here
      halt_baddata();
    }
    DAT_1001660e = 0;
    gettimeofday((timeval *)&DAT_10016610,(__timezone_ptr_t)0x0);
    DAT_1001661c = in_stack_00000024;
    DAT_10016620 = in_stack_00000028;
    DAT_10016618 = DAT_100174e8;
    FUN_0040f150(FUN_0040fbb0,&zoom_stack_pointer);
  }
  else {
    if (DAT_10017492 != '\0') {
      FUN_004101e4();
    }
    *(int *)(curcontext + 0x3c) = in_stack_00000020;
    if (in_stack_00000020 != 0) {
      FUN_0041d69c();
    }
    *(float *)curcontext = (float)param_1;
    *(float *)(curcontext + 4) = (float)param_2;
    *(float *)(curcontext + 8) = (float)(double)CONCAT44(in_register_00001040,in_stack_00000014);
    *(short *)(curcontext + 0xc) = in_stack_0000001a;
    FUN_0040bfec();
    *(short *)(curcontext + 0xe) = in_stack_0000001e;
    FUN_0040c0cc();
    redraw_gl_scene();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
