// rendering.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/rendering.h"

void draw_scene(void)

{
  timeval tStack_8;
  
  redraw_flag = 0;
  gettimeofday(&tStack_8,(__timezone_ptr_t)0x0);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_positioned_item(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  int unaff_gp;
  undefined8 in_f4;
  undefined8 in_f6;
  float fVar1;
  uint in_register_00001080;
  
  (**(code **)(unaff_gp + -0x7b60))
            ((float)(double)CONCAT44((int)((ulonglong)in_f4 >> 0x20),param_1),
             (float)(double)CONCAT44((int)((ulonglong)in_f6 >> 0x20),param_2),param_3,param_4,0);
  (**(code **)(unaff_gp + -0x7b68))((int)-*(short *)(**(int **)(unaff_gp + -0x7684) + 0xe),0x78);
  (**(code **)(unaff_gp + -0x7b60))(0,*(undefined4 *)(*(int *)(unaff_gp + -0x75dc) + 0xe8));
  fVar1 = (float)((double)-*(float *)(*(int *)(unaff_gp + -0x75dc) + 0xe4) /
                 (double)((ulonglong)in_register_00001080 << 0x20));
  (**(code **)(unaff_gp + -0x7df0))(fVar1,fVar1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_warp(void)

{
  cpack(cpack_color);
  clear();
  swapbuffers();
  gflush();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void display_scan_status(undefined4 param_1,char *param_2,undefined4 param_3)

{
  char *pcVar1;
  char cVar2;
  int unaff_gp;
  undefined1 auStack_434 [1076];
  
  if (*param_2 == '/') {
    cVar2 = param_2[1];
    while (cVar2 == '/') {
      pcVar1 = param_2 + 2;
      param_2 = param_2 + 1;
      cVar2 = *pcVar1;
    }
  }
  (**(code **)(unaff_gp + -0x7ecc))(auStack_434,param_1);
  (**(code **)(unaff_gp + -0x7ce4))(auStack_434,*(int *)(unaff_gp + -0x7fa4) + -0x5938);
  (**(code **)(unaff_gp + -0x7ce4))(auStack_434,param_2);
  (**(code **)(unaff_gp + -0x7a98))(auStack_434,param_3);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_mark_overlay(void)

{
  int iVar1;
  undefined4 uVar2;
  int unaff_gp;
  
  iVar1 = **(int **)(unaff_gp + -0x7684);
  if ((*(char *)(iVar1 + 0xc51) != '\0') && (*(char *)(iVar1 + 0xc52) != '\0')) {
    *(undefined1 *)(*(int *)(unaff_gp + -0x7f98) + 0x6e24) = 0;
    if (*(int *)(iVar1 + 0x48) == 0) {
      if (*(int *)(iVar1 + 0x44) == 0) {
        (**(code **)(unaff_gp + -0x7dec))
                  (*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 0x1c),
                   *(int *)(unaff_gp + -0x7fa4) + -0x4cc4);
      }
      else {
        (**(code **)(unaff_gp + -0x7dec))
                  (*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 0x1c),iVar1 + 0x4c);
        uVar2 = (**(code **)(unaff_gp + -0x7c20))(**(int **)(unaff_gp + -0x7684) + 0x4c);
        (**(code **)(unaff_gp + -0x7dcc))
                  (*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 0x1c),uVar2);
        uVar2 = (**(code **)(unaff_gp + -0x7c20))(**(int **)(unaff_gp + -0x7684) + 0x4c);
        (**(code **)(unaff_gp + -0x7db8))
                  (*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 0x1c),uVar2);
      }
    }
    else {
      (**(code **)(unaff_gp + -0x7dec))
                (*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 0x1c),iVar1 + 0x44c);
      uVar2 = (**(code **)(unaff_gp + -0x7c20))(**(int **)(unaff_gp + -0x7684) + 0x44c);
      (**(code **)(unaff_gp + -0x7dcc))
                (*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 0x1c),uVar2);
      uVar2 = (**(code **)(unaff_gp + -0x7c20))(**(int **)(unaff_gp + -0x7684) + 0x44c);
      (**(code **)(unaff_gp + -0x7db8))
                (*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 0x1c),uVar2);
    }
    (*(code *)(*(int *)(unaff_gp + -0x7fe4) + -0x3c1c))();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void render_overview_frame(void)

{
  float fVar1;
  int iVar2;
  undefined4 uVar3;
  int *piVar4;
  code *pcVar5;
  int unaff_gp;
  double dVar6;
  uint uVar7;
  undefined8 in_f18;
  uint in_fcsr;
  int local_b8;
  undefined4 local_b4 [3];
  undefined4 local_a8;
  int local_a4;
  int local_a0;
  undefined4 *local_9c;
  int local_98;
  int *local_94;
  int local_90;
  undefined4 local_8c;
  int local_88;
  undefined4 local_84;
  int local_80;
  int local_7c;
  int local_78;
  undefined4 local_74;
  int local_70;
  int local_6c;
  int local_68;
  int local_64;
  
  uVar7 = (uint)((ulonglong)in_f18 >> 0x20);
  if (*(char *)(*(int *)(unaff_gp + -0x7f98) + 0x6ebc) == '\0') {
    (**(code **)(unaff_gp + -0x7c3c))
              (**(undefined4 **)(unaff_gp + -0x7600),*(int *)(unaff_gp + -0x7f98) + 0x6e94,4);
    *(undefined1 *)(*(int *)(unaff_gp + -0x7f98) + 0x6ebc) = 1;
  }
  local_9c = local_b4;
  local_a0 = *(int *)(unaff_gp + -0x7f5c) + 0x9a;
  iVar2 = (**(code **)(unaff_gp + -0x7960))();
  local_94 = &local_b8;
  if (iVar2 == 0) {
    local_98 = *(int *)(unaff_gp + -0x7fa4) + -0x469c;
  }
  else {
    local_98 = *(int *)(unaff_gp + -0x7fa4) + -0x46ac;
  }
  (**(code **)(unaff_gp + -0x7c9c))(*(undefined4 *)(**(int **)(unaff_gp + -0x767c) + 8),&local_a0,2)
  ;
  local_a0 = *(int *)(unaff_gp + -0x7f80) + 0x118;
  local_9c = (undefined4 *)0x1;
  uVar3 = (**(code **)(unaff_gp + -0x7df4))
                    (*(int *)(unaff_gp + -0x7fa4) + -0x468c,**(undefined4 **)(unaff_gp + -0x7f74),
                     **(undefined4 **)(unaff_gp + -0x75f0),&local_a0,1);
  iVar2 = *(int *)(unaff_gp + -0x7f5c);
  *(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x6eb4) = uVar3;
  (**(code **)(unaff_gp + -0x7c54))(uVar3,iVar2 + 0xa9,*(int *)(unaff_gp + -0x7fe4) + 0x1180,0);
  local_a8 = (**(code **)(unaff_gp + -0x7c84))
                       (*(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x6eb4),
                        *(int *)(unaff_gp + -0x7fa4) + -0x4680,&local_a0,0);
  (**(code **)(unaff_gp + -0x7c78))(local_a8);
  (**(code **)(unaff_gp + -0x785c))(local_a8,*(undefined4 *)(unaff_gp + -0x76c0));
  iVar2 = (**(code **)(unaff_gp + -0x7960))();
  if (iVar2 != 0) {
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x6e64) = 0x3000;
  }
  local_9c = (undefined4 *)0x1;
  local_a0 = *(int *)(unaff_gp + -0x7f60) + 0x27b5;
  local_98 = *(int *)(unaff_gp + -0x7f60) + 0x1d63;
  local_90 = *(int *)(unaff_gp + -0x7f60) + 0x2375;
  local_88 = *(int *)(unaff_gp + -0x7f60) + 0x1399;
  local_80 = *(int *)(unaff_gp + -0x7fa4) + -0x4670;
  local_7c = *(int *)(unaff_gp + -0x7f98) + 0x6e64;
  local_94 = (int *)0x1;
  local_8c = 1;
  local_84 = 1;
  iVar2 = (**(code **)(unaff_gp + -0x7960))();
  if (iVar2 == 0) {
    local_78 = *(int *)(unaff_gp + -0x7fa4) + -0x4658;
  }
  else {
    local_78 = *(int *)(unaff_gp + -0x7fa4) + -0x4664;
  }
  local_74 = 1;
  local_70 = *(int *)(unaff_gp + -0x7f5c) + 0x368;
  dVar6 = ((double)**(float **)(unaff_gp + -0x75d0) - (double)**(float **)(unaff_gp + -0x75d4)) *
          (double)((ulonglong)uVar7 << 0x20);
  local_68 = *(int *)(unaff_gp + -0x7f5c) + 0xea;
  if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
    dVar6 = ROUND(dVar6);
  }
  else {
    dVar6 = FLOOR(dVar6);
  }
  local_6c = (int)dVar6;
  fVar1 = **(float **)(unaff_gp + -0x75c8) - **(float **)(unaff_gp + -0x75cc);
  if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
    fVar1 = ROUND(fVar1);
  }
  else {
    fVar1 = FLOOR(fVar1);
  }
  local_64 = (int)fVar1;
  local_a4 = 8;
  iVar2 = (**(code **)(unaff_gp + -0x7960))();
  if (iVar2 == 0) {
    piVar4 = &local_a0 + local_a4 * 2;
    *piVar4 = *(int *)(unaff_gp + -0x7fa4) + -0x463c;
  }
  else {
    piVar4 = &local_a0 + local_a4 * 2;
    *piVar4 = *(int *)(unaff_gp + -0x7fa4) + -0x464c;
  }
  iVar2 = *(int *)(unaff_gp + -0x7fa4);
  pcVar5 = *(code **)(unaff_gp + -0x7e04);
  piVar4[1] = local_b8;
  uVar3 = (*pcVar5)(local_a8,iVar2 + -0x462c,&local_a0,local_a4 + 1);
  iVar2 = *(int *)(unaff_gp + -0x7fa4);
  *(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c0c) = uVar3;
  (**(code **)(unaff_gp + -0x7c54))(uVar3,iVar2 + -0x4620,*(int *)(unaff_gp + -0x7fe4) + 0xbfc,0);
  iVar2 = (**(code **)(unaff_gp + -0x7960))();
  if (iVar2 == 0) {
    iVar2 = *(int *)(unaff_gp + -0x7fa4) + -0x45fc;
  }
  else {
    iVar2 = *(int *)(unaff_gp + -0x7fa4) + -0x4610;
  }
  (**(code **)(unaff_gp + -0x7c54))
            (*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c0c),iVar2,
             *(int *)(unaff_gp + -0x7fe4) + 0xc50,0);
  (**(code **)(unaff_gp + -0x7c54))
            (*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c0c),
             *(int *)(unaff_gp + -0x7fa4) + -0x45e8,*(int *)(unaff_gp + -0x7fe4) + 0xca4,0);
  (**(code **)(unaff_gp + -0x7c54))
            (*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c0c),
             *(int *)(unaff_gp + -0x7fa4) + -0x45d8,*(int *)(unaff_gp + -0x7fe4) + 0xe74,0);
  (**(code **)(unaff_gp + -0x7c78))(*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c0c));
  iVar2 = *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6e60);
  if (iVar2 == 0) {
    uVar3 = (**(code **)(unaff_gp + -0x7c10))(*(undefined4 *)(unaff_gp + -0x76ac));
    iVar2 = *(int *)(unaff_gp + -0x7f98);
    *(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x6e60) = uVar3;
    iVar2 = *(int *)(iVar2 + 0x6e60);
  }
  (**(code **)(unaff_gp + -0x7c58))(*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c0c),iVar2);
  local_a0 = *(int *)(unaff_gp + -0x7f5c) + 0x9a;
  local_9c = (undefined4 *)local_b4[0];
  (**(code **)(unaff_gp + -0x7cc0))
            (*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6c0c),&local_a0,1);
  (**(code **)(unaff_gp + -0x7c78))(*(undefined4 *)(*(int *)(unaff_gp + -0x7f98) + 0x6eb4));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_legend_color_box(undefined4 *param_1,int param_2,uint param_3)

{
  bool bVar1;
  int iVar2;
  int *piVar3;
  int iVar4;
  int unaff_gp;
  
  if (param_2 == 4) {
    if (param_1 != (undefined4 *)0x0) {
      (**(code **)(unaff_gp + -0x7b9c))(*param_1);
    }
    (**(code **)(unaff_gp + -0x7d54))();
    iVar2 = *(int *)(unaff_gp + -0x7f98);
    iVar4 = *(int *)(unaff_gp + -0x7f98) + 0x6f40;
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x7010) * 0xc);
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x7014) * 0xc);
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x701c) * 0xc);
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x7018) * 0xc);
    (**(code **)(unaff_gp + -0x7d3c))();
  }
  else if (param_2 == 3) {
    if (param_1 != (undefined4 *)0x0) {
      (**(code **)(unaff_gp + -0x7b9c))(*param_1);
    }
    (**(code **)(unaff_gp + -0x7b7c))();
    (**(code **)(unaff_gp + -0x7dc0))(*(int *)(unaff_gp + -0x7f98) + 0x7020);
    (**(code **)(unaff_gp + -0x7dc0))(*(int *)(unaff_gp + -0x7f98) + 0x702c);
    (**(code **)(unaff_gp + -0x7b94))();
  }
  else if (param_2 == 2) {
    if (param_1 != (undefined4 *)0x0) {
      (**(code **)(unaff_gp + -0x7b9c))(*param_1);
    }
    (**(code **)(unaff_gp + -0x7d54))();
    iVar2 = *(int *)(unaff_gp + -0x7f98);
    iVar4 = *(int *)(unaff_gp + -0x7f98) + 0x6f40;
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x7000) * 0xc);
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x7004) * 0xc);
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x700c) * 0xc);
    (**(code **)(unaff_gp + -0x7dc0))(iVar4 + *(int *)(iVar2 + 0x7008) * 0xc);
    (**(code **)(unaff_gp + -0x7d3c))();
  }
  else {
    bVar1 = param_2 != 1 && param_1 != (undefined4 *)0x0;
    if ((param_2 == 1) && (param_1 != (undefined4 *)0x0)) {
      (**(code **)(unaff_gp + -0x7b9c))(param_1[1]);
    }
    if ((param_3 & 1) != 0) {
      if (bVar1) {
        (**(code **)(unaff_gp + -0x7b9c))(param_1[1]);
      }
      if (param_2 == 1) {
        (**(code **)(unaff_gp + -0x7d24))();
        iVar2 = *(int *)(unaff_gp + -0x7f98);
        piVar3 = (int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fa0);
        do {
          (**(code **)(unaff_gp + -0x7dc0))(iVar2 + 0x6f40 + *piVar3 * 0xc);
          piVar3 = piVar3 + 1;
        } while (piVar3 != (int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fb0));
        (**(code **)(unaff_gp + -0x7d20))();
      }
      else {
        (**(code **)(unaff_gp + -0x7d54))();
        iVar2 = *(int *)(unaff_gp + -0x7f98) + 0x6f40;
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fa0) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fa4) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fac) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fa8) * 0xc);
        (**(code **)(unaff_gp + -0x7d3c))();
      }
    }
    iVar2 = *(int *)(unaff_gp + -0x7f98) + 0x6f40;
    if (bVar1) {
      (**(code **)(unaff_gp + -0x7b9c))(param_1[3]);
    }
    if ((param_3 & 2) != 0) {
      if (param_2 == 1) {
        (**(code **)(unaff_gp + -0x7d24))();
        iVar4 = *(int *)(unaff_gp + -0x7f98) + 0x6fa0;
        do {
          (**(code **)(unaff_gp + -0x7dc0))(iVar2 + *(int *)(iVar4 + 0x10) * 0xc);
          iVar4 = iVar4 + 4;
        } while (iVar4 != *(int *)(unaff_gp + -0x7f98) + 0x6fb0);
        (**(code **)(unaff_gp + -0x7d20))();
      }
      else {
        (**(code **)(unaff_gp + -0x7d54))();
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fb0) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fb4) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fbc) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fb8) * 0xc);
        (**(code **)(unaff_gp + -0x7d3c))();
      }
    }
    if ((param_3 & 4) != 0) {
      if (param_2 == 1) {
        (**(code **)(unaff_gp + -0x7d24))();
        iVar4 = *(int *)(unaff_gp + -0x7f98) + 0x6fa0;
        do {
          (**(code **)(unaff_gp + -0x7dc0))(iVar2 + *(int *)(iVar4 + 0x20) * 0xc);
          iVar4 = iVar4 + 4;
        } while (iVar4 != *(int *)(unaff_gp + -0x7f98) + 0x6fb0);
        (**(code **)(unaff_gp + -0x7d20))();
      }
      else {
        (**(code **)(unaff_gp + -0x7d54))();
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fc0) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fc4) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fcc) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fc8) * 0xc);
        (**(code **)(unaff_gp + -0x7d3c))();
      }
    }
    if ((param_3 & 8) != 0) {
      if (bVar1) {
        (**(code **)(unaff_gp + -0x7b9c))(param_1[2]);
      }
      if (param_2 == 1) {
        (**(code **)(unaff_gp + -0x7d24))();
        iVar4 = *(int *)(unaff_gp + -0x7f98) + 0x6fa0;
        do {
          (**(code **)(unaff_gp + -0x7dc0))(iVar2 + *(int *)(iVar4 + 0x30) * 0xc);
          iVar4 = iVar4 + 4;
        } while (iVar4 != *(int *)(unaff_gp + -0x7f98) + 0x6fb0);
        (**(code **)(unaff_gp + -0x7d20))();
      }
      else {
        (**(code **)(unaff_gp + -0x7d54))();
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fd0) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fd4) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fdc) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fd8) * 0xc);
        (**(code **)(unaff_gp + -0x7d3c))();
      }
    }
    if ((param_3 & 0x10) != 0) {
      if (bVar1) {
        (**(code **)(unaff_gp + -0x7b9c))(*param_1);
      }
      if (param_2 == 1) {
        (**(code **)(unaff_gp + -0x7d24))();
        iVar4 = *(int *)(unaff_gp + -0x7f98) + 0x6fa0;
        do {
          (**(code **)(unaff_gp + -0x7dc0))(iVar2 + *(int *)(iVar4 + 0x40) * 0xc);
          iVar4 = iVar4 + 4;
        } while (iVar4 != *(int *)(unaff_gp + -0x7f98) + 0x6fb0);
        (**(code **)(unaff_gp + -0x7d20))();
      }
      else {
        (**(code **)(unaff_gp + -0x7d54))();
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fe0) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fe4) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fec) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6fe8) * 0xc);
        (**(code **)(unaff_gp + -0x7d3c))();
      }
    }
    if ((param_3 & 0x20) != 0) {
      if (param_2 == 1) {
        (**(code **)(unaff_gp + -0x7d24))();
        iVar4 = *(int *)(unaff_gp + -0x7f98) + 0x6fa0;
        do {
          (**(code **)(unaff_gp + -0x7dc0))(iVar2 + *(int *)(iVar4 + 0x50) * 0xc);
          iVar4 = iVar4 + 4;
        } while (iVar4 != *(int *)(unaff_gp + -0x7f98) + 0x6fb0);
        (**(code **)(unaff_gp + -0x7d20))();
      }
      else {
        (**(code **)(unaff_gp + -0x7d54))();
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6ff0) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6ff4) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6ffc) * 0xc);
        (**(code **)(unaff_gp + -0x7dc0))
                  (iVar2 + *(int *)(*(int *)(unaff_gp + -0x7f98) + 0x6ff8) * 0xc);
        (**(code **)(unaff_gp + -0x7d3c))();
      }
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_item_recursive(undefined8 param_1,undefined8 param_2,int param_3)

{
  int iVar1;
  int *piVar2;
  int iVar3;
  int iVar4;
  int unaff_gp;
  float fVar5;
  uint uVar6;
  undefined4 uVar7;
  undefined4 uVar9;
  uint in_register_00001090;
  undefined8 uVar8;
  
  uVar9 = (undefined4)((ulonglong)param_2 >> 0x20);
  uVar6 = (uint)((ulonglong)param_1 >> 0x20);
  if (param_3 != *(int *)(**(int **)(unaff_gp + -0x7684) + 0x3c)) {
    (**(code **)(unaff_gp + -0x7b48))();
    iVar4 = *(int *)(**(int **)(unaff_gp + -0x7684) + 0x3c);
    if (param_3 == *(int *)(iVar4 + 0x28)) {
      (**(code **)(unaff_gp + -0x79f0))
                ((ulonglong)uVar6 << 0x20,
                 (double)*(float *)(iVar4 + 0x3c) +
                 (double)*(float *)(*(int *)(unaff_gp + -0x75dc) + 0xdc));
    }
    else if (param_3 == *(int *)(iVar4 + 0x2c)) {
      (**(code **)(unaff_gp + -0x79f0))
                ((double)-*(float *)(*(int *)(unaff_gp + -0x75dc) + 0xe0),
                 (double)*(float *)(iVar4 + 0x3c) +
                 (double)*(float *)(*(int *)(unaff_gp + -0x75dc) + 0xdc));
    }
    else if (param_3 == *(int *)(iVar4 + 0x30)) {
      (**(code **)(unaff_gp + -0x79f0))
                ((double)*(float *)(*(int *)(unaff_gp + -0x75dc) + 0xe0),
                 (double)*(float *)(iVar4 + 0x3c) +
                 (double)*(float *)(*(int *)(unaff_gp + -0x75dc) + 0xdc));
    }
    else {
      iVar3 = *(int *)(iVar4 + 0x14);
      iVar1 = 0;
      if (0 < iVar3) {
        piVar2 = *(int **)(iVar4 + 0x18);
        do {
          if (param_3 == *piVar2) {
            fVar5 = *(float *)(*(int *)(unaff_gp + -0x75dc) + 0xd0);
            uVar8 = CONCAT44(uVar6,(float)((double)-fVar5 *
                                           (double)((ulonglong)in_register_00001090 << 0x20) *
                                           (double)(iVar3 + -1) + (double)fVar5 * (double)iVar1));
            (**(code **)(unaff_gp + -0x7b60))(uVar8,iVar3,iVar4,0);
            uVar7 = (undefined4)((ulonglong)uVar8 >> 0x20);
            (**(code **)(unaff_gp + -0x7b68))(0xfffffc7c,0x7a);
            (**(code **)(unaff_gp + -0x7b60))
                      (CONCAT44(uVar7,*(undefined4 *)(*(int *)(unaff_gp + -0x7fa4) + -0x50a4)),
                       CONCAT44(uVar9,*(undefined4 *)(*(int *)(unaff_gp + -0x7fa4) + -0x50a0)));
            uVar9 = *(undefined4 *)(*(int *)(unaff_gp + -0x7fa4) + -0x509c);
            (**(code **)(unaff_gp + -0x7df0))(uVar9,uVar9);
            break;
          }
          iVar1 = iVar1 + 1;
          piVar2 = piVar2 + 1;
        } while (iVar1 < iVar3);
      }
    }
    (**(code **)(unaff_gp + -0x7b28))();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_warp_directory(undefined8 param_1,undefined8 param_2,undefined4 *param_3,char param_4)

{
  undefined1 uVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  longlong lVar6;
  undefined8 uVar7;
  undefined4 uVar9;
  uint uVar10;
  undefined4 uVar11;
  longlong lVar12;
  undefined8 uVar13;
  undefined4 uVar14;
  double dVar15;
  double unaff_f20;
  double dVar16;
  uint unaff_000010b0;
  float fStack_28;
  float fStack_24;
  float fStack_20;
  float fStack_18;
  float fVar8;
  
  uVar9 = (undefined4)((ulonglong)param_2 >> 0x20);
  uVar5 = (uint)((ulonglong)param_1 >> 0x20);
  if (param_4 == '\0') {
    fVar8 = icon_size_multiplier * *(float *)(curcontext + 0x34);
    if (grid_display_flag == '\0') {
      cpack(highlight_packed_color);
      bgnpolygon();
      unaff_f20 = (double)fVar8;
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = (float)((double)*(float *)(curcontext + 8) +
                         (double)((ulonglong)unaff_000010b0 << 0x20));
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = (float)((double)*(float *)(curcontext + 8) +
                         (double)((ulonglong)unaff_000010b0 << 0x20));
      v3f(&fStack_28);
      endpolygon();
    }
    else {
      shademodel(1);
      bgnpolygon();
      cpack(graphics_state_mode);
      unaff_f20 = (double)fVar8;
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      cpack(current_packed_color);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = *(float *)(curcontext + 8) + view_offset_z;
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = *(float *)(curcontext + 8) + view_offset_z;
      v3f(&fStack_28);
      endpolygon();
      shademodel(0);
      bgnpolygon();
      cpack(current_packed_color);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = *(float *)(curcontext + 8) + view_offset_z;
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = (float)((double)*(float *)(curcontext + 8) +
                         (double)((ulonglong)unaff_000010b0 << 0x20));
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = (float)((double)*(float *)(curcontext + 8) +
                         (double)((ulonglong)unaff_000010b0 << 0x20));
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = *(float *)(curcontext + 8) + view_offset_z;
      v3f(&fStack_28);
      endpolygon();
      shademodel(1);
      bgnpolygon();
      cpack(graphics_render_flags);
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) - base_y_offset;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) - base_y_offset;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      cpack(highlight_color);
      fStack_28 = (float)((double)*(float *)curcontext + unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      fStack_28 = (float)((double)*(float *)curcontext - unaff_f20);
      fStack_24 = *(float *)(curcontext + 4) + view_offset_y;
      fStack_20 = -0.5;
      v3f(&fStack_28);
      endpolygon();
      shademodel(0);
    }
  }
  fStack_18 = *(float *)(curcontext + 4) -
              *(float *)(curcontext + 0x18) * *(float *)(curcontext + 0x20) *
              *(float *)(curcontext + 8);
  loadname((int)*(short *)((int)param_3 + 0x5e));
  pushmatrix();
  dVar16 = (double)((ulonglong)unaff_f20 & 0xffffffff00000000);
  lVar6 = (ulonglong)uVar5 << 0x20;
  uVar7 = CONCAT44(uVar9,(float)((double)(float)param_3[0xf] / dVar16));
  translate(lVar6,uVar7);
  uVar10 = (uint)((ulonglong)uVar7 >> 0x20);
  uVar5 = (uint)((ulonglong)lVar6 >> 0x20);
  if ((int)(param_3[0x1d] << 0xb) < 0) {
    pushmatrix();
    cpack(monitor_label_color);
    lVar6 = (ulonglong)uVar5 << 0x20;
    lVar12 = (ulonglong)uVar10 << 0x20;
    translate(lVar6,lVar12);
    fVar8 = (float)((double)-(float)param_3[0xf] / dVar16 - (double)layout_z_offset);
    uVar7 = CONCAT44((int)((ulonglong)lVar6 >> 0x20),fVar8);
    uVar13 = CONCAT44((int)((ulonglong)lVar12 >> 0x20),fVar8);
    rectf(uVar7,uVar13);
    uVar10 = (uint)((ulonglong)uVar13 >> 0x20);
    uVar5 = (uint)((ulonglong)uVar7 >> 0x20);
    popmatrix();
  }
  cpack(*(undefined4 *)(boxDir + 0x10));
  if ((int)(param_3[0x1d] << 0xd) < 0) {
    dVar15 = (double)-(float)param_3[0xf] / dVar16;
    uVar7 = CONCAT44(uVar5,(float)dVar15);
    uVar13 = CONCAT44(uVar10,(float)dVar15);
    rect(uVar7,uVar13);
    uVar11 = (undefined4)((ulonglong)uVar13 >> 0x20);
    uVar9 = (undefined4)((ulonglong)uVar7 >> 0x20);
    uVar14 = (undefined4)((ulonglong)dVar15 >> 0x20);
  }
  else {
    dVar15 = (double)-(float)param_3[0xf] / dVar16;
    uVar7 = CONCAT44(uVar5,(float)dVar15);
    uVar13 = CONCAT44(uVar10,(float)dVar15);
    rectf(uVar7,uVar13);
    uVar11 = (undefined4)((ulonglong)uVar13 >> 0x20);
    uVar9 = (undefined4)((ulonglong)uVar7 >> 0x20);
    uVar14 = (undefined4)((ulonglong)dVar15 >> 0x20);
  }
  pushmatrix();
  dVar15 = (double)(int)param_3[1] * (double)CONCAT44(uVar14,0x70a3d70a);
  uVar7 = CONCAT44(uVar9,(float)dVar15);
  uVar13 = CONCAT44(uVar11,(float)((double)-(float)param_3[0xf] / dVar16 -
                                  (double)CONCAT44((int)((ulonglong)dVar15 >> 0x20),0x9999999a)));
  translate(uVar7,uVar13);
  uVar11 = (undefined4)((ulonglong)uVar13 >> 0x20);
  uVar9 = (undefined4)((ulonglong)uVar7 >> 0x20);
  rotate((int)-*(short *)(curcontext + 0xe),0x78);
  lVar6 = CONCAT44(uVar9,0x3cf5c28f);
  dVar15 = (double)CONCAT44(uVar11,0x3cf5c28f);
  scale(lVar6,dVar15);
  draw_file_icon(*param_3);
  popmatrix();
  iVar3 = 0;
  if (0 < (int)param_3[3]) {
    iVar4 = 0;
    do {
      iVar2 = *(int *)(param_3[4] + iVar4);
      pushname((int)(short)iVar3);
      if (param_4 == '\0') {
                    // WARNING: Bad instruction - Truncating control flow here
        halt_baddata();
      }
      if (param_4 == '\0') {
        uVar1 = *(int *)(iVar2 + 0x28) << 9 < 0;
      }
      else {
        uVar1 = 4;
      }
      render_file_icon(param_3,iVar2,0,param_4 == '\0',uVar1,0x1f);
      uVar9 = (undefined4)((ulonglong)dVar15 >> 0x20);
      uVar5 = (uint)((ulonglong)lVar6 >> 0x20);
      if (*(int *)(iVar2 + 0x28) << 3 < 0) {
        pushmatrix();
        translate((ulonglong)uVar5 << 0x20,
                  CONCAT44(uVar9,(float)((double)-(float)param_3[0xf] / dVar16)));
        dVar15 = (double)(float)param_3[0xf] * dVar16;
        lVar6 = (ulonglong)unaff_000010b0 << 0x20;
        draw_scaled_element(lVar6,dVar15);
        popmatrix();
        if (0 < iVar3) {
                    // WARNING: Bad instruction - Truncating control flow here
          halt_baddata();
        }
        if (iVar3 < param_3[3] + -1) {
                    // WARNING: Bad instruction - Truncating control flow here
          halt_baddata();
        }
      }
      iVar3 = iVar3 + 1;
      popname();
      iVar4 = iVar4 + 4;
    } while (iVar3 < (int)param_3[3]);
  }
  process_pick_item(param_3,param_4);
  popmatrix();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void redraw_gl_scene(void)

{
  code *pcVar1;
  int unaff_gp;
  undefined1 auStack_8 [8];
  
  pcVar1 = *(code **)(unaff_gp + -0x7b2c);
  *(undefined1 *)(*(int *)(unaff_gp + -0x7f94) + 0x6688) = 0;
  (*pcVar1)(auStack_8,0);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_overview_content(void)

{
  int unaff_gp;
  
  if (**(char **)(unaff_gp + -0x76c4) != '\0') {
    (**(code **)(unaff_gp + -0x799c))();
    (**(code **)(unaff_gp + -0x7cfc))(0);
    (**(code **)(unaff_gp + -0x7cf8))();
    (*(code *)(*(int *)(unaff_gp + -0x7fe4) + 0xacc))();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_file_icon(byte *param_1)

{
  int iVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  int iVar5;
  int unaff_gp;
  
  uVar3 = (uint)*param_1;
  if (uVar3 != 0) {
    iVar5 = *(int *)(unaff_gp + -0x76cc);
    do {
      iVar1 = *(int *)(iVar5 + uVar3 * 0xd8);
      if ((iVar1 != 0) && (iVar1 != 0)) {
        iVar4 = 0;
        do {
          if (iVar1 == 1) {
            iVar1 = iVar5 + uVar3 * 0xd8 + iVar4;
            (**(code **)(unaff_gp + -0x7b60))((float)*(int *)(iVar1 + 4),(float)*(int *)(iVar1 + 8))
            ;
            uVar3 = (uint)*param_1;
            iVar1 = iVar5 + uVar3 * 0xd8 + iVar4;
LAB_00418bcc:
            iVar1 = *(int *)(iVar1 + 0xc);
          }
          else {
            if (iVar1 == 2) {
              (**(code **)(unaff_gp + -0x7b7c))();
              (**(code **)(unaff_gp + -0x7c68))(iVar5 + (uint)*param_1 * 0xd8 + iVar4 + 4);
              uVar3 = (uint)*param_1;
              iVar1 = iVar5 + uVar3 * 0xd8 + iVar4;
              goto LAB_00418bcc;
            }
            iVar2 = iVar5 + uVar3 * 0xd8 + iVar4;
            if (iVar1 == 3) {
              (**(code **)(unaff_gp + -0x7c68))(iVar2 + 4);
              uVar3 = (uint)*param_1;
              iVar1 = iVar5 + uVar3 * 0xd8 + iVar4;
              goto LAB_00418bcc;
            }
            if (iVar1 == 4) {
              (**(code **)(unaff_gp + -0x7c68))(iVar2 + 4);
              (**(code **)(unaff_gp + -0x7b94))();
              uVar3 = (uint)*param_1;
              iVar1 = iVar5 + uVar3 * 0xd8 + iVar4;
              goto LAB_00418bcc;
            }
            iVar1 = *(int *)(iVar2 + 0xc);
          }
          iVar4 = iVar4 + 0xc;
        } while (iVar1 != 0);
      }
      uVar3 = (uint)param_1[1];
      param_1 = param_1 + 1;
    } while (uVar3 != 0);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void display_status_message(char *param_1)

{
  bool bVar1;
  bool bVar2;
  size_t sVar3;
  char *pcVar4;
  size_t sVar5;
  uint __c;
  int iVar6;
  char *__s;
  statvfs asStack_128 [2];
  stat local_8c;
  undefined4 local_4;
  
  bVar2 = false;
  time(&last_operation_time);
  if (db_filepath == (char *)0x0) {
    if (home_directory == (char *)0x0) {
      if (relative_path_flag == '\0') {
        home_directory = getenv("HOME");
        if (home_directory == (char *)0x0) {
          home_directory = ".";
        }
      }
      else {
        home_directory = ".";
      }
    }
    sVar5 = strlen(home_directory);
    sVar3 = strlen(param_1);
    db_filepath = (char *)malloc(sVar3 + sVar5 + 7);
    strcpy(db_filepath,home_directory);
    strcat(db_filepath,"/.FSN_");
    sVar5 = strlen(db_filepath);
    __s = db_filepath + sVar5;
    strcat(db_filepath,param_1);
    pcVar4 = strchr(__s,0x2f);
    while (pcVar4 != (char *)0x0) {
      *pcVar4 = '_';
      pcVar4 = strchr(__s,0x2f);
    }
  }
  else {
    if (*db_filepath == '/') {
      home_directory = strdup(db_filepath);
    }
    else {
      pcVar4 = getcwd((char *)0x0,0x400);
      sVar5 = strlen(pcVar4);
      sVar3 = strlen(db_filepath);
      home_directory = (char *)malloc(sVar3 + sVar5 + 2);
      strcpy(home_directory,pcVar4);
      strcat(home_directory,"/");
      strcat(home_directory,db_filepath);
      db_filepath = strdup(home_directory);
      free(pcVar4);
    }
    pcVar4 = strrchr(home_directory,0x2f);
    *pcVar4 = '\0';
  }
  sVar5 = strlen(db_filepath);
  pcVar4 = (char *)malloc(sVar5 + 0x12);
  sprintf(pcVar4,"zcat 2>/dev/null<%s",db_filepath);
  current_file = popen(pcVar4,"r");
  bVar1 = false;
  if (current_file != (FILE *)0x0) {
    if (__iob_func_result == 0) {
      current_file->_flags = current_file->_flags + -1;
      if (current_file->_flags < 0) {
        __c = __filbuf();
      }
      else {
        __c = (uint)(byte)*current_file->_IO_read_ptr;
        current_file->_IO_read_ptr = current_file->_IO_read_ptr + 1;
      }
    }
    else {
      __c = __semgetc();
    }
    if (__c == 0xffffffff) {
      pclose(current_file);
      bVar1 = false;
    }
    else {
      ungetc(__c,current_file);
      bVar2 = true;
      bVar1 = true;
    }
  }
  if ((bVar1) || (current_file = fopen(db_filepath,"r"), current_file != (FILE *)0x0)) {
    apply_pending_updates();
    local_4 = set_status_message("reading file system database",0);
    reset_display_state();
    *(byte *)(topdir + 0x1d) = *(byte *)(topdir + 0x1d) | 2;
    if (bVar2) {
      pclose(current_file);
    }
    else {
      fclose(current_file);
    }
    deleteMessage(local_4);
    iVar6 = statvfs((char *)*topdir,asStack_128);
    if (iVar6 < 0) {
      fprintf((FILE *)0xfb52904,"Could not statvfs %s, exiting\n",*topdir);
                    // WARNING: Subroutine does not return
      exit(1);
    }
    strcpy(fstyp,(char *)&asStack_128[0].__f_unused);
    localFlag = asStack_128[0].__f_spare[1] & 0x80000000;
    iVar6 = lstat((char *)*topdir,&local_8c);
    if (iVar6 < 0) {
      fprintf((FILE *)0xfb52904,"Could not stat %s, exiting\n",*topdir);
                    // WARNING: Subroutine does not return
      exit(1);
    }
    current_device_id = local_8c.st_dev._0_4_;
  }
  else {
    finalize_update();
    topdir = (undefined4 *)create_root_directory(param_1);
    free(pcVar4);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void draw_box(undefined4 *param_1,int param_2,uint param_3)

{
  bool bVar1;
  int *piVar2;
  undefined4 *puVar3;
  
  if (param_2 == 4) {
    if (param_1 != (undefined4 *)0x0) {
      cpack(*param_1);
    }
    bgnqstrip();
    v3f(vertex_idx_4 * 0xc + 0x10006f40);
    v3f(vertex_idx_5 * 0xc + 0x10006f40);
    v3f(vertex_idx_7 * 0xc + 0x10006f40);
    v3f(vertex_idx_6 * 0xc + 0x10006f40);
    endqstrip();
  }
  else if (param_2 == 3) {
    if (param_1 != (undefined4 *)0x0) {
      cpack(*param_1);
    }
    bgnline();
    v3f(&vertex_8_ptr);
    v3f(&vertex_9_ptr);
    endline();
  }
  else if (param_2 == 2) {
    if (param_1 != (undefined4 *)0x0) {
      cpack(*param_1);
    }
    bgnqstrip();
    v3f(vertex_idx_0 * 0xc + 0x10006f40);
    v3f(vertex_idx_1 * 0xc + 0x10006f40);
    v3f(vertex_idx_3 * 0xc + 0x10006f40);
    v3f(vertex_idx_2 * 0xc + 0x10006f40);
    endqstrip();
  }
  else {
    bVar1 = param_2 != 1 && param_1 != (undefined4 *)0x0;
    if ((param_2 == 1) && (param_1 != (undefined4 *)0x0)) {
      cpack(param_1[1]);
    }
    if ((param_3 & 1) != 0) {
      if (bVar1) {
        cpack(param_1[1]);
      }
      if (param_2 == 1) {
        bgnclosedline();
        piVar2 = &vertex_array_start_idx;
        do {
          v3f(*piVar2 * 0xc + 0x10006f40);
          piVar2 = piVar2 + 1;
        } while (piVar2 != &vertex_array_end_idx);
        endclosedline();
      }
      else {
        bgnqstrip();
        v3f(vertex_array_start_idx * 0xc + 0x10006f40);
        v3f(face_vtx_0 * 0xc + 0x10006f40);
        v3f(face_vtx_2 * 0xc + 0x10006f40);
        v3f(face_vtx_1 * 0xc + 0x10006f40);
        endqstrip();
      }
    }
    if (bVar1) {
      cpack(param_1[3]);
    }
    if ((param_3 & 2) != 0) {
      if (param_2 == 1) {
        bgnclosedline();
        puVar3 = &vertex_array_start_idx;
        do {
          v3f(puVar3[4] * 0xc + 0x10006f40);
          puVar3 = puVar3 + 1;
        } while (puVar3 != &vertex_array_end_idx);
        endclosedline();
      }
      else {
        bgnqstrip();
        v3f(vertex_array_end_idx * 0xc + 0x10006f40);
        v3f(face_vtx_4 * 0xc + 0x10006f40);
        v3f(face_vtx_6 * 0xc + 0x10006f40);
        v3f(face_vtx_5 * 0xc + 0x10006f40);
        endqstrip();
      }
    }
    if ((param_3 & 4) != 0) {
      if (param_2 == 1) {
        bgnclosedline();
        puVar3 = &vertex_array_start_idx;
        do {
          v3f(puVar3[8] * 0xc + 0x10006f40);
          puVar3 = puVar3 + 1;
        } while (puVar3 != &vertex_array_end_idx);
        endclosedline();
      }
      else {
        bgnqstrip();
        v3f(face_vtx_7 * 0xc + 0x10006f40);
        v3f(face_vtx_8 * 0xc + 0x10006f40);
        v3f(face_vtx_10 * 0xc + 0x10006f40);
        v3f(face_vtx_9 * 0xc + 0x10006f40);
        endqstrip();
      }
    }
    if ((param_3 & 8) != 0) {
      if (bVar1) {
        cpack(param_1[2]);
      }
      if (param_2 == 1) {
        bgnclosedline();
        puVar3 = &vertex_array_start_idx;
        do {
          v3f(puVar3[0xc] * 0xc + 0x10006f40);
          puVar3 = puVar3 + 1;
        } while (puVar3 != &vertex_array_end_idx);
        endclosedline();
      }
      else {
        bgnqstrip();
        v3f(face_vtx_11 * 0xc + 0x10006f40);
        v3f(face_vtx_12 * 0xc + 0x10006f40);
        v3f(face_vtx_14 * 0xc + 0x10006f40);
        v3f(face_vtx_13 * 0xc + 0x10006f40);
        endqstrip();
      }
    }
    if ((param_3 & 0x10) != 0) {
      if (bVar1) {
        cpack(*param_1);
      }
      if (param_2 == 1) {
        bgnclosedline();
        puVar3 = &vertex_array_start_idx;
        do {
          v3f(puVar3[0x10] * 0xc + 0x10006f40);
          puVar3 = puVar3 + 1;
        } while (puVar3 != &vertex_array_end_idx);
        endclosedline();
      }
      else {
        bgnqstrip();
        v3f(face_vtx_15 * 0xc + 0x10006f40);
        v3f(face_vtx_16 * 0xc + 0x10006f40);
        v3f(face_vtx_18 * 0xc + 0x10006f40);
        v3f(face_vtx_17 * 0xc + 0x10006f40);
        endqstrip();
      }
    }
    if ((param_3 & 0x20) != 0) {
      if (param_2 == 1) {
        bgnclosedline();
        puVar3 = &vertex_array_start_idx;
        do {
          v3f(puVar3[0x14] * 0xc + 0x10006f40);
          puVar3 = puVar3 + 1;
        } while (puVar3 != &vertex_array_end_idx);
        endclosedline();
      }
      else {
        bgnqstrip();
        v3f(face_vtx_19 * 0xc + 0x10006f40);
        v3f(face_vtx_20 * 0xc + 0x10006f40);
        v3f(face_vtx_22 * 0xc + 0x10006f40);
        v3f(face_vtx_21 * 0xc + 0x10006f40);
        endqstrip();
      }
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
