// ui_motif.c - Extracted from fsn.c
// Generated by extract_module.py

#include "../include/fsn.h"
#include "../include/ui_motif.h"

void hideOverview(void)

{
  if (overview_popup_shell != 0) {
    overviewActive = 0;
    XtUnmanageChild();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setScales(void)

{
  undefined4 uStack_50;
  int iStack_4c;
  
  if ((controlsShowing != '\0') && (curcontext[0xc53] == '\0')) {
    if (DAT_10000148 != *(short *)(curcontext + 0xc)) {
      uStack_50 = 0xf66187b;
      iStack_4c = (int)*(short *)(curcontext + 0xc);
      DAT_10000148 = *(short *)(curcontext + 0xc);
      XtSetValues(DAT_1001663c,&uStack_50,1);
    }
    if (DAT_1000014c != *(short *)(curcontext + 0xe)) {
      uStack_50 = 0xf66187b;
      iStack_4c = (int)*(short *)(curcontext + 0xe);
      DAT_1000014c = *(short *)(curcontext + 0xe);
      XtSetValues(vertical_scale_widget,&uStack_50,1);
    }
                    // WARNING: Bad instruction - Truncating control flow here
    halt_baddata();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void show_error_dialog(undefined4 param_1,undefined4 param_2)

{
  int unaff_gp;
  undefined1 auStack_434 [1076];
  
  (**(code **)(unaff_gp + -0x7ecc))(auStack_434,param_1);
  (**(code **)(unaff_gp + -0x7ce4))(auStack_434,*(int *)(unaff_gp + -0x7fa4) + -0x592c);
  (**(code **)(unaff_gp + -0x7ce4))(auStack_434,param_2);
  (**(code **)(unaff_gp + -0x7a90))(auStack_434);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void showPreferencePanel(void)

{
  float fVar1;
  undefined **ppuVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  char *__src;
  undefined *puVar5;
  float fVar6;
  uint in_fcsr;
  char acStack_4b0 [1048];
  undefined4 local_98;
  undefined4 local_94;
  undefined4 local_90;
  uint local_8c;
  undefined4 local_88;
  undefined *local_84;
  undefined4 local_80;
  undefined *local_7c;
  undefined4 local_78;
  undefined *local_74;
  undefined4 local_70;
  undefined4 local_6c;
  undefined4 local_40;
  undefined4 local_38;
  undefined4 local_34;
  undefined4 local_8;
  undefined4 local_4;
  
  if (preference_panel_shell == 0) {
    local_98 = 0xf662094;
    local_94 = 1;
    preference_panel_shell = XtCreatePopupShell("preferencePanel",_DAT_0f6d16fc,toplevel,&local_98,1);
    XtAddCallback(preference_panel_shell,0xf6615c9,FUN_0042cc30,0);
    local_4 = XmCreatePanedWindow(preference_panel_shell,"preferencePane",&local_98,0);
    XtManageChild(local_4);
    install_help_callback(local_4,&prefPanelHelp);
    local_8 = XmCreateRowColumn(local_4,"preferenceHeader",&local_98,0);
    XtManageChild(local_8);
    uVar3 = XmCreateLabel(local_8,"preferenceHeaderLabel",&local_98,0);
    XtManageChild(uVar3);
    uVar3 = XmCreateRowColumn(local_8,"preferenceHeaderButtons",&local_98,0);
    XtManageChild(uVar3);
    uVar4 = XmCreatePushButton(uVar3,"preferenceQuit",&local_98,0);
    XtAddCallback(uVar4,0xe3f35b3,hidePreferencePanel,0);
    XtManageChild(uVar4);
    uVar4 = XmCreatePushButton(uVar3,"preferenceUndo",&local_98,0);
    XtAddCallback(uVar4,0xe3f35b3,FUN_0042ccac,0);
    XtManageChild(uVar4);
    uVar4 = XmCreatePushButton(uVar3,"preferenceSaveChanges",&local_98,0);
    XtAddCallback(uVar4,0xe3f35b3,FUN_0042cf60,0);
    XtManageChild(uVar4);
    uVar3 = XmCreatePushButton(uVar3,"preferenceSaveAll",&local_98,0);
    XtAddCallback(uVar3,0xe3f35b3,FUN_0042cf60,1);
    XtManageChild(uVar3);
    uVar3 = XmCreateRowColumn(local_8,"preferenceHeaderButtons2",&local_98,0);
    XtManageChild(uVar3);
    uVar4 = XmCreatePushButton(uVar3,"preferenceSelect",&local_98,0);
    XtAddCallback(uVar4,0xe3f35b3,FUN_0042d338,0);
    XtManageChild(uVar4);
    DAT_10016e48 = XmCreateTextField(uVar3,"preferenceFileName",&local_98,0);
    __src = getenv("HOME");
    if (__src != (char *)0x0) {
      strcpy(acStack_4b0,__src);
      strcat(acStack_4b0,"/.Xdefaults");
      XmTextFieldSetString(DAT_10016e48,acStack_4b0);
    }
    XtManageChild(DAT_10016e48);
    uVar3 = XmCreateRowColumn(local_4,"preferenceBooleans",&local_98,0);
    XtManageChild(uVar3);
    ppuVar2 = &PTR_s_shrinkOnZoom_10008950;
    puVar5 = PTR_s_shrinkOnZoom_10008950;
    while (puVar5 != (undefined *)0x0) {
      uVar4 = XmStringCreateSimple(puVar5);
      local_98 = 0xe3f40b5;
      local_90 = 0xe3f48f1;
      local_8c = (uint)(byte)*ppuVar2[1];
      local_94 = uVar4;
      puVar5 = (undefined *)XmCreateToggleButton(uVar3,"preferenceBoolean",&local_98,2);
      ppuVar2[4] = puVar5;
      XtAddCallback(puVar5,0xe3f4ca5,FUN_0042caa0,ppuVar2);
      XtManageChild(ppuVar2[4]);
      XmStringFree(uVar4);
      puVar5 = ppuVar2[5];
      *(undefined *)(ppuVar2 + 3) = *ppuVar2[1];
      ppuVar2 = ppuVar2 + 5;
    }
    uVar3 = XmCreateScrolledWindow(local_4,"preferenceScaleScroll",&local_98,0);
    XtManageChild(uVar3);
    local_34 = XmCreateRowColumn(uVar3,"preferenceScales",&local_98,0);
    XtManageChild(local_34);
    ppuVar2 = &PTR_s_monitorTimeout_100089f0;
    puVar5 = PTR_s_monitorTimeout_100089f0;
    while (puVar5 != (undefined *)0x0) {
      uVar4 = 4;
      uVar3 = XmStringCreateSimple(puVar5);
      local_98 = 0xe3f4adf;
      local_90 = 0xf66187b;
      local_8c = *(uint *)ppuVar2[1];
      local_88 = 0xe3f430c;
      local_84 = ppuVar2[3];
      local_80 = 0xe3f4274;
      local_7c = ppuVar2[4];
      if (((uint)ppuVar2[2] & 8) != 0) {
        local_74 = (undefined *)0x2;
        local_78 = 0xe3f45e5;
        uVar4 = 5;
      }
      local_94 = uVar3;
      puVar5 = (undefined *)XmCreateScale(local_34,"preferenceScale",&local_98,uVar4);
      ppuVar2[6] = puVar5;
      XtAddCallback(puVar5,0xe3f4ca5,FUN_0042caec,ppuVar2);
      XtManageChild(ppuVar2[6]);
      XmStringFree(uVar3);
      puVar5 = ppuVar2[7];
      ppuVar2[5] = *(undefined **)ppuVar2[1];
      ppuVar2 = ppuVar2 + 7;
    }
    ppuVar2 = &PTR_s_mouseSpeed_10008b5c;
    puVar5 = PTR_s_mouseSpeed_10008b5c;
    while (puVar5 != (undefined *)0x0) {
      fVar6 = *(float *)(&DAT_100094f0 + (int)ppuVar2[5] * 4);
      uVar4 = 5;
      uVar3 = XmStringCreateSimple(puVar5);
      local_98 = 0xe3f4adf;
      local_90 = 0xf66187b;
      local_88 = 0xe3f430c;
      local_80 = 0xe3f4274;
      if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
        fVar1 = ROUND(*(float *)ppuVar2[1] * fVar6);
      }
      else {
        fVar1 = FLOOR(*(float *)ppuVar2[1] * fVar6);
      }
      local_8c = (uint)fVar1;
      local_78 = 0xe3f3995;
      if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
        fVar1 = ROUND((float)(int)ppuVar2[3] * fVar6);
      }
      else {
        fVar1 = FLOOR((float)(int)ppuVar2[3] * fVar6);
      }
      local_84 = (undefined *)(int)fVar1;
      if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
        fVar6 = ROUND((float)(int)ppuVar2[4] * fVar6);
      }
      else {
        fVar6 = FLOOR((float)(int)ppuVar2[4] * fVar6);
      }
      local_7c = (undefined *)(int)fVar6;
      local_74 = ppuVar2[5];
      if (((uint)ppuVar2[2] & 8) != 0) {
        local_6c = 2;
        local_70 = 0xe3f45e5;
        uVar4 = 6;
      }
      local_94 = uVar3;
      puVar5 = (undefined *)XmCreateScale(local_34,"preferenceScale",&local_98,uVar4);
      ppuVar2[7] = puVar5;
      XtAddCallback(puVar5,0xe3f4ca5,FUN_0042cb38,ppuVar2);
      XtManageChild(ppuVar2[7]);
      XmStringFree(uVar3);
      puVar5 = ppuVar2[8];
      ppuVar2[6] = *(undefined **)ppuVar2[1];
      ppuVar2 = ppuVar2 + 8;
    }
    local_38 = XmCreateForm(local_4,"preferenceColorForm",&local_98,0);
    XtManageChild(local_38);
    local_98 = 0xe3f40cb;
    local_90 = 0xe3f46dd;
    local_88 = 0xe3f3701;
    local_94 = 1;
    local_8c = 1;
    local_84 = (undefined *)0x1;
    uVar3 = XmCreateRowColumn(local_38,"preferenceColorScales",&local_98,3);
    XtManageChild(uVar3);
    pref_red_scale = XmCreateScale(uVar3,"preferenceRedScale",&local_98,0);
    XtManageChild(pref_red_scale);
    XtAddCallback(pref_red_scale,0xe3f4ca5,rgb_scale_callback,0);
    pref_hue_scale = XmCreateScale(uVar3,"preferenceHueScale",&local_98,0);
    XtManageChild(pref_hue_scale);
    XtAddCallback(pref_hue_scale,0xe3f4ca5,hsv_scale_callback,0);
    pref_green_scale = XmCreateScale(uVar3,"preferenceGreenScale",&local_98,0);
    XtManageChild(pref_green_scale);
    XtAddCallback(pref_green_scale,0xe3f4ca5,rgb_scale_callback,0);
    pref_sat_scale = XmCreateScale(uVar3,"preferenceSatScale",&local_98,0);
    XtManageChild(pref_sat_scale);
    XtAddCallback(pref_sat_scale,0xe3f4ca5,hsv_scale_callback,0);
    pref_blue_scale = XmCreateScale(uVar3,"preferenceBlueScale",&local_98,0);
    XtManageChild(pref_blue_scale);
    XtAddCallback(pref_blue_scale,0xe3f4ca5,rgb_scale_callback,0);
    pref_val_scale = XmCreateScale(uVar3,"preferenceValScale",&local_98,0);
    XtManageChild(pref_val_scale);
    XtAddCallback(pref_val_scale,0xe3f4ca5,hsv_scale_callback,0);
    FUN_0042d618();
    FUN_0042d6f0();
    local_88 = 0xe3f46dd;
    local_98 = 0xe3f4b1d;
    local_90 = 0xe3f40cb;
    local_80 = 0xe3f3701;
    local_78 = 0xe3f3753;
    local_94 = 1;
    local_8c = 1;
    local_84 = (undefined *)0x1;
    local_7c = (undefined *)0x3;
    local_74 = (undefined *)uVar3;
    uVar3 = XmCreateScrolledWindow(local_38,"preferenceColorScroll",&local_98,5);
    XtManageChild(uVar3);
    local_40 = XmCreateRadioBox(uVar3,"preferenceColors",&local_98,0);
    XtManageChild(local_40);
    ppuVar2 = &PTR_s_groundColor_1000935c;
    puVar5 = PTR_s_groundColor_1000935c;
    while (puVar5 != (undefined *)0x0) {
      uVar4 = 1;
      uVar3 = XmStringCreateSimple(puVar5);
      local_98 = 0xe3f40b5;
      if (ppuVar2 == (undefined **)PTR_PTR_100094ec) {
        local_90 = 0xe3f48f1;
        local_8c = 1;
        uVar4 = 2;
      }
      local_94 = uVar3;
      puVar5 = (undefined *)XmCreateToggleButton(local_40,"preferenceColor",&local_98,uVar4);
      ppuVar2[3] = puVar5;
      XtAddCallback(puVar5,0xe3f4ca5,FUN_0042cbb8,ppuVar2);
      XtManageChild(ppuVar2[3]);
      XmStringFree(uVar3);
      puVar5 = ppuVar2[4];
      ppuVar2[2] = *(undefined **)ppuVar2[1];
      ppuVar2 = ppuVar2 + 4;
    }
    XtManageChild(preference_panel_shell);
  }
  else {
    XtManageChild();
    uVar3 = XtDisplay(preference_panel_shell);
    uVar4 = XtWindow(preference_panel_shell);
    XMapWindow(uVar3,uVar4);
    uVar3 = XtWindow(preference_panel_shell);
    XRaiseWindow(display,uVar3);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createCopyright(undefined4 param_1,int param_2,int param_3)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  
  puVar1 = (undefined4 *)(param_2 + param_3 * 8);
  *puVar1 = 0xe3f3d1b;
  puVar1[1] = 0;
  puVar1 = (undefined4 *)(param_2 + (param_3 + 1) * 8);
  *puVar1 = 0xe3f3d12;
  puVar1[1] = 0;
  puVar1 = (undefined4 *)(param_2 + (param_3 + 2) * 8);
  puVar1[1] = s_FSN_the_3D_File_System_Navigator_100079c4;
  *puVar1 = 0xf66187b;
  active_file_list = XmCreateText(param_1,"copyright",param_2,param_3 + 3);
  XtManageChild(active_file_list);
  uVar2 = XtWindow(active_file_list);
  XRaiseWindow(display,uVar2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createMarkControls(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 uStack_54;
  undefined4 uStack_50;
  
  uStack_54 = 0xf6617e7;
  uStack_50 = 0;
  mark_selector_dialog = XmCreateSelectionBox(param_1,"markSelector",&uStack_54,1);
  uVar1 = XmSelectionBoxGetChild(mark_selector_dialog,7);
  XtUnmanageChild(uVar1);
  uVar1 = XmSelectionBoxGetChild(mark_selector_dialog,0xd);
  XtUnmanageChild(uVar1);
  uVar1 = XmSelectionBoxGetChild(mark_selector_dialog,0xb);
  XtUnmanageChild(uVar1);
  uVar1 = XmSelectionBoxGetChild(mark_selector_dialog,0xe);
  XtUnmanageChild(uVar1);
  mark_selector_list = XmSelectionBoxGetChild(mark_selector_dialog,8);
  XtAddCallback(mark_selector_dialog,0xe3f44b6,FUN_0042f4d8,0);
  XtAddCallback(mark_selector_dialog,0xe3f380d,FUN_0042f5d0,0);
  XtManageChild(mark_selector_dialog);
  install_help_callback(mark_selector_dialog,&markHelp);
  uVar1 = XmCreatePushButton(param_1,&DAT_10013c40,&uStack_54,0);
  XtAddCallback(uVar1,0xe3f35b3,FUN_0042f73c,0);
  XtManageChild(uVar1);
  install_help_callback(uVar1,&markHelp);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createSelectedInfo(undefined4 param_1,undefined4 *param_2,undefined4 param_3)

{
  undefined4 uVar1;
  undefined4 uVar2;
  
  move_file_xmstring = XmStringCreate("Move file",&default_charset);
  DAT_10016b34 = XmStringCreate("Move file out",&default_charset);
  DAT_10016b38 = XmStringCreate("Move file in",&default_charset);
  copy_file_xmstring = XmStringCreate("Copy file",&default_charset);
  DAT_10016b40 = XmStringCreate("Copy file out",&default_charset);
  DAT_10016b44 = XmStringCreate("Copy file in",&default_charset);
  link_file_xmstring = XmStringCreate("Link file",&default_charset);
  DAT_10016b4c = XmStringCreate("Link file out",&default_charset);
  DAT_10016b50 = XmStringCreate("Link file in",&default_charset);
  uVar1 = XmCreateForm(param_1,"selectedInfo",param_2,param_3);
  XtManageChild(uVar1);
  *param_2 = 0xe3f4b1d;
  param_2[1] = 1;
  param_2[2] = 0xe3f40cb;
  param_2[3] = 1;
  param_2[4] = 0xe3f46dd;
  param_2[5] = 1;
  uVar2 = XmCreateTextField(uVar1,"fileName",param_2,3);
  *(undefined4 *)(curcontextwindows + 0x1c) = uVar2;
  XtAddCallback(*(undefined4 *)(curcontextwindows + 0x1c),0xe3f4ca5,FUN_0041fb20,
                *(undefined4 *)(curcontextwindows + 0xc));
  XtAddCallback(*(undefined4 *)(curcontextwindows + 0x1c),0xe3f35b3,FUN_0041fcc0,
                *(undefined4 *)(curcontextwindows + 0xc));
  XtAddEventHandler(*(undefined4 *)(curcontextwindows + 0x1c),0x10,0,FUN_0041fa18,
                    *(undefined4 *)(curcontextwindows + 0xc));
  XtAddEventHandler(*(undefined4 *)(curcontextwindows + 0x1c),0x20,0,FUN_0041fadc,0);
  XtAddEventHandler(*(undefined4 *)(curcontextwindows + 0x1c),4,0,myContext,
                    *(undefined4 *)(curcontextwindows + 0xc));
  XtManageChild(*(undefined4 *)(curcontextwindows + 0x1c));
  *param_2 = 0xe3f4b1d;
  param_2[1] = 3;
  param_2[2] = 0xe3f4ba9;
  uVar2 = *(undefined4 *)(curcontextwindows + 0x1c);
  param_2[4] = 0xe3f40cb;
  param_2[5] = 1;
  param_2[6] = 0xe3f46dd;
  param_2[7] = 1;
  param_2[8] = 0xe3f40b5;
  param_2[3] = uVar2;
  param_2[9] = blankXmString;
  uVar1 = XmCreateLabel(uVar1,"fileInfo",param_2,5);
  *(undefined4 *)(curcontextwindows + 0x20) = uVar1;
  XtManageChild(*(undefined4 *)(curcontextwindows + 0x20));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createSearch(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  undefined4 uStack_28;
  undefined4 uStack_24;
  
  search_xmstring_1 = XmStringCreateSimple("Search");
  search_xmstring_2 = XmStringCreateSimple(&DAT_10013d2c);
  search_xmstring_3 = XmStringCreateSimple(&DAT_10013d30);
  uStack_28 = 0xe3f3afd;
  uStack_24 = 1;
  uVar1 = XmCreateSelectionBox(param_1,"search",&uStack_28,1);
  uVar2 = XmSelectionBoxGetChild(uVar1,7);
  XtUnmanageChild(uVar2);
  uVar2 = XmSelectionBoxGetChild(uVar1,0xe);
  XtUnmanageChild(uVar2);
  uVar2 = XmSelectionBoxGetChild(uVar1,0xb);
  XtUnmanageChild(uVar2);
  uVar2 = XmSelectionBoxGetChild(uVar1,0xd);
  XtUnmanageChild(uVar2);
  DAT_10016ef8 = XmSelectionBoxGetChild(uVar1,1);
  XtSetSensitive(DAT_10016ef8,0);
  XtManageChild(DAT_10016ef8);
  XtManageChild(uVar1);
  XtAddCallback(uVar1,0xe3f44b6,FUN_00430448,0);
  XtAddCallback(uVar1,0xe3f3641,FUN_004308ec,0);
  XtAddCallback(uVar1,0xe3f380d,FUN_004307bc,0);
  uStack_24 = 1;
  uStack_28 = 0xf661719;
  uVar2 = XmCreateRowColumn(uVar1,"search",&uStack_28,1);
  XtManageChild(uVar2);
  uStack_24 = search_xmstring_1;
  uStack_28 = 0xe3f40b5;
  search_count_label = XmCreateLabel(uVar2,"searchCount",&uStack_28,1);
  XtManageChild(search_count_label);
  uStack_28 = 0xf661719;
  uStack_24 = 2;
  uVar3 = XmCreateRowColumn(uVar2,"searchname",&uStack_28,1);
  XtManageChild(uVar3);
  uVar4 = XmCreateLabel(uVar3,&DAT_10013d5c,&uStack_28,0);
  XtManageChild(uVar4);
  search_name_field = XmCreateTextField(uVar3,"nametext",&uStack_28,0);
  XtManageChild(search_name_field);
  uStack_28 = 0xf661719;
  uStack_24 = 2;
  uVar3 = XmCreateRowColumn(uVar2,"searchsize",&uStack_28,1);
  XtManageChild(uVar3);
  uVar4 = XmCreateLabel(uVar3,&DAT_10013d7c,&uStack_28,0);
  XtManageChild(uVar4);
  uStack_24 = search_xmstring_3;
  uStack_28 = 0xe3f40b5;
  search_size_comp_button = XmCreatePushButton(uVar3,"searchSizeComp",&uStack_28,1);
  XtAddCallback(search_size_comp_button,0xe3f35b3,FUN_00430b70,0);
  XtManageChild(search_size_comp_button);
  DAT_10016f04 = 0;
  search_size_field = XmCreateTextField(uVar3,"sizetext",&uStack_28,0);
  XtManageChild(search_size_field);
  uStack_24 = 2;
  uStack_28 = 0xf661719;
  uVar2 = XmCreateRowColumn(uVar2,"searchage",&uStack_28,1);
  XtManageChild(uVar2);
  uVar3 = XmCreateLabel(uVar2,&DAT_10013dac,&uStack_28,0);
  XtManageChild(uVar3);
  uStack_24 = search_xmstring_3;
  uStack_28 = 0xe3f40b5;
  search_age_comp_button = XmCreatePushButton(uVar2,"searchAgeComp",&uStack_28,1);
  XtAddCallback(search_age_comp_button,0xe3f35b3,FUN_00430c0c,0);
  XtManageChild(search_age_comp_button);
  DAT_10016f05 = 0;
  search_age_field = XmCreateTextField(uVar2,"agetext",&uStack_28,0);
  XtManageChild(search_age_field);
  install_help_callback(uVar1,&searchHelp);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void CreateSelectionEntries(undefined4 param_1)

{
  undefined1 auStack_50 [80];
  
  menu_process_deletes = XmCreatePushButton(param_1,"menuProcessDeletes",auStack_50,0);
  XtAddCallback(menu_process_deletes,0xe3f35b3,menu_process_deletes_callback,0);
  XtSetSensitive(menu_process_deletes,0);
  XtManageChild(menu_process_deletes);
  menu_undo_deletes = XmCreatePushButton(param_1,"menuUndoDeletes",auStack_50,0);
  XtAddCallback(menu_undo_deletes,0xe3f35b3,menu_undo_deletes_callback,0);
  XtSetSensitive(menu_undo_deletes,0);
  XtManageChild(menu_undo_deletes);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setMoveAndCopyButtons(void)

{
  int iVar1;
  int iVar2;
  bool bVar3;
  undefined4 uStack_28;
  undefined4 uStack_24;
  
  XtSetSensitive(menu_directory_cascade,*(int *)(curcontext + 0x44) != 0);
  XtSetSensitive(menu_file_cascade,*(int *)(curcontext + 0x48) != 0);
  XtSetSensitive(popup_menu_widget,*(int *)(curcontext + 0x48) != 0);
  FUN_0041c928(1);
  if ((altcontext[0xc51] != '\0') && (iVar1 = *(int *)(curcontext + 0x44), iVar1 != 0)) {
    iVar2 = 0;
    if (altcontext[0xc51] != '\0') {
      iVar2 = *(int *)(altcontext + 0x44);
    }
    if (iVar2 != iVar1) {
      if (*(int *)(curcontext + 0x48) != 0) {
        uStack_28 = 0xe3f40b5;
        uStack_24 = DAT_10016b34;
        XtSetValues(menu_move_file_1,&uStack_28,1);
        XtSetValues(menu_move_file_2,&uStack_28,1);
        if (altcontext[0xc51] == '\0') {
          bVar3 = false;
        }
        else {
          bVar3 = *(int *)(altcontext + 0x44) != 0;
        }
        if (bVar3 != false) {
          if (altcontext[0xc51] == '\0') {
            bVar3 = true;
          }
          else {
            bVar3 = *(int *)(altcontext + 0x48) == 0;
          }
        }
        XtSetSensitive(menu_move_file_1,bVar3);
        if (altcontext[0xc51] == '\0') {
          bVar3 = false;
        }
        else {
          bVar3 = *(int *)(altcontext + 0x44) != 0;
        }
        if (bVar3 != false) {
          if (altcontext[0xc51] == '\0') {
            bVar3 = true;
          }
          else {
            bVar3 = *(int *)(altcontext + 0x48) == 0;
          }
        }
        XtSetSensitive(menu_move_file_2,bVar3);
        uStack_24 = DAT_10016b40;
        uStack_28 = 0xe3f40b5;
        XtSetValues(menu_copy_file_1,&uStack_28,1);
        XtSetValues(menu_copy_file_2,&uStack_28,1);
        if (altcontext[0xc51] == '\0') {
          bVar3 = false;
        }
        else {
          bVar3 = *(int *)(altcontext + 0x44) != 0;
        }
        if (bVar3 != false) {
          if (altcontext[0xc51] == '\0') {
            bVar3 = true;
          }
          else {
            bVar3 = *(int *)(altcontext + 0x48) == 0;
          }
        }
        XtSetSensitive(menu_copy_file_1,bVar3);
        if (altcontext[0xc51] == '\0') {
          bVar3 = false;
        }
        else {
          bVar3 = *(int *)(altcontext + 0x44) != 0;
        }
        if (bVar3 != false) {
          if (altcontext[0xc51] == '\0') {
            bVar3 = true;
          }
          else {
            bVar3 = *(int *)(altcontext + 0x48) == 0;
          }
        }
        XtSetSensitive(menu_copy_file_2,bVar3);
        uStack_24 = DAT_10016b4c;
        uStack_28 = 0xe3f40b5;
        XtSetValues(menu_link_file_1,&uStack_28,1);
        XtSetValues(menu_link_file_2,&uStack_28,1);
        if (altcontext[0xc51] == '\0') {
          bVar3 = false;
        }
        else {
          bVar3 = *(int *)(altcontext + 0x44) != 0;
        }
        if (bVar3 != false) {
          if (altcontext[0xc51] == '\0') {
            bVar3 = true;
          }
          else {
            bVar3 = *(int *)(altcontext + 0x48) == 0;
          }
        }
        XtSetSensitive(menu_link_file_1,bVar3);
        if (altcontext[0xc51] == '\0') {
          bVar3 = false;
        }
        else {
          bVar3 = *(int *)(altcontext + 0x44) != 0;
        }
        if (bVar3 != false) {
          if (altcontext[0xc51] == '\0') {
            bVar3 = true;
          }
          else {
            bVar3 = *(int *)(altcontext + 0x48) == 0;
          }
        }
        XtSetSensitive(menu_link_file_2,bVar3);
        halt_baddata();
      }
      if (iVar1 == 0) {
        halt_baddata();
      }
      uStack_24 = DAT_10016b38;
      uStack_28 = 0xe3f40b5;
      XtSetValues(menu_move_file_1,&uStack_28,1);
      XtSetValues(menu_move_file_2,&uStack_28,1);
      iVar1 = 0;
      if (altcontext[0xc51] != '\0') {
        iVar1 = *(int *)(altcontext + 0x48);
      }
      XtSetSensitive(menu_move_file_1,iVar1 != 0);
      iVar1 = 0;
      if (altcontext[0xc51] != '\0') {
        iVar1 = *(int *)(altcontext + 0x48);
      }
      XtSetSensitive(menu_move_file_2,iVar1 != 0);
      uStack_28 = 0xe3f40b5;
      uStack_24 = DAT_10016b44;
      XtSetValues(menu_copy_file_1,&uStack_28,1);
      XtSetValues(menu_copy_file_2,&uStack_28,1);
      iVar1 = 0;
      if (altcontext[0xc51] != '\0') {
        iVar1 = *(int *)(altcontext + 0x48);
      }
      XtSetSensitive(menu_copy_file_1,iVar1 != 0);
      iVar1 = 0;
      if (altcontext[0xc51] != '\0') {
        iVar1 = *(int *)(altcontext + 0x48);
      }
      XtSetSensitive(menu_copy_file_2,iVar1 != 0);
      uStack_24 = DAT_10016b50;
      uStack_28 = 0xe3f40b5;
      XtSetValues(menu_link_file_1,&uStack_28,1);
      XtSetValues(menu_link_file_2,&uStack_28,1);
      iVar1 = 0;
      if (altcontext[0xc51] != '\0') {
        iVar1 = *(int *)(altcontext + 0x48);
      }
      XtSetSensitive(menu_link_file_1,iVar1 != 0);
      iVar1 = 0;
      if (altcontext[0xc51] != '\0') {
        iVar1 = *(int *)(altcontext + 0x48);
      }
      XtSetSensitive(menu_link_file_2,iVar1 != 0);
      XtSetSensitive(menu_file_cascade,1);
      XtSetSensitive(popup_menu_widget,1);
      FUN_0041c928(0);
      halt_baddata();
    }
  }
  uStack_24 = move_file_xmstring;
  uStack_28 = 0xe3f40b5;
  XtSetValues(menu_move_file_1,&uStack_28,1);
  XtSetValues(menu_move_file_2,&uStack_28,1);
  XtSetSensitive(menu_move_file_1,0);
  XtSetSensitive(menu_move_file_2,0);
  uStack_24 = copy_file_xmstring;
  uStack_28 = 0xe3f40b5;
  XtSetValues(menu_copy_file_1,&uStack_28,1);
  XtSetValues(menu_copy_file_2,&uStack_28,1);
  XtSetSensitive(menu_copy_file_1,0);
  XtSetSensitive(menu_copy_file_2,0);
  uStack_24 = link_file_xmstring;
  uStack_28 = 0xe3f40b5;
  XtSetValues(menu_link_file_1,&uStack_28,1);
  XtSetValues(menu_link_file_2,&uStack_28,1);
  XtSetSensitive(menu_link_file_1,0);
  XtSetSensitive(menu_link_file_2,0);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void dumpDatabaseCB(void)

{
  FUN_00414da4();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void showOverview(void)

{
  undefined4 uVar1;
  undefined4 uVar2;
  
  if (overview_popup_shell == 0) {
    FUN_0041fdf0();
  }
  else {
    XtManageChild();
    uVar1 = XtDisplay(overview_popup_shell);
    uVar2 = XtWindow(overview_popup_shell);
    XMapWindow(uVar1,uVar2);
    XRaiseWindow(display,DAT_10016c08);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void undisplayHourglass(void)

{
  undefined4 uVar1;
  
  uVar1 = XtWindow();
  XUndefineCursor(display,uVar1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void redrawSelectionNames(void)

{
  size_t sVar1;
  
  if ((curcontext[0xc51] != '\0') && (curcontext[0xc52] != '\0')) {
    mark_menu_widget = 0;
    if (*(int *)(curcontext + 0x48) == 0) {
      if (*(int *)(curcontext + 0x44) == 0) {
        XmTextFieldSetString(*(undefined4 *)(curcontextwindows + 0x1c),"No file");
      }
      else {
        XmTextFieldSetString(*(undefined4 *)(curcontextwindows + 0x1c),(int)curcontext + 0x4c);
        sVar1 = strlen(curcontext + 0x4c);
        XmTextFieldShowPosition(*(undefined4 *)(curcontextwindows + 0x1c),sVar1);
        sVar1 = strlen(curcontext + 0x4c);
        XmTextFieldSetInsertionPosition(*(undefined4 *)(curcontextwindows + 0x1c),sVar1);
      }
    }
    else {
      XmTextFieldSetString(*(undefined4 *)(curcontextwindows + 0x1c),(int)curcontext + 0x44c);
      sVar1 = strlen(curcontext + 0x44c);
      XmTextFieldShowPosition(*(undefined4 *)(curcontextwindows + 0x1c),sVar1);
      sVar1 = strlen(curcontext + 0x44c);
      XmTextFieldSetInsertionPosition(*(undefined4 *)(curcontextwindows + 0x1c),sVar1);
    }
    FUN_0041c3e4();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createHelpMenu(undefined4 param_1)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uStack_2c;
  undefined4 uStack_28;
  undefined4 uStack_24;
  
  uStack_2c = 0;
  FUN_00432094(display,0,&uStack_28,&uStack_2c);
  uVar1 = XmCreatePulldownMenu(param_1,"help_menu",&uStack_28,uStack_2c);
  XtAddCallback(uVar1,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(uVar1,0xe3f4c38,overlayMenuUnmappedCB,0);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"window_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,FUN_0042b3f4,&topHelp);
  XtManageChild(uVar2);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"context_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,FUN_0042b5ac,0);
  XtManageChild(uVar2);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"mode_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,FUN_0042b3f4,&modeHelp);
  XtManageChild(uVar2);
  uStack_2c = 0;
  uVar2 = XmCreatePushButton(uVar1,"version_help",&uStack_28,0);
  XtAddCallback(uVar2,0xe3f35b3,FUN_0042b3f4,&versionHelp);
  XtManageChild(uVar2);
  uStack_28 = 0xe3f4a31;
  uStack_2c = 1;
  uStack_24 = uVar1;
  uVar1 = XmCreateCascadeButton(param_1,"helpButton",&uStack_28,1);
  XtManageChild(uVar1);
  uStack_2c = 1;
  uStack_28 = 0xe3f429f;
  uStack_24 = uVar1;
  XtSetValues(param_1,&uStack_28,1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void hidePreferencePanel(void)

{
  if (preference_panel_shell != 0) {
    XtUnmanageChild();
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void fileCreated(int param_1,char *param_2)

{
  size_t sVar1;
  int iVar2;
  undefined4 *puVar3;
  void *pvVar4;
  undefined4 uVar5;
  byte bVar6;
  bool bVar7;
  char *__dest;
  stat sStack_94;
  char *pcStack_c;
  
  if (-1 < *(int *)(param_1 + 0x74) << 0xd) {
    pcStack_c = (char *)build_path_string(0,param_1);
    sVar1 = strlen(pcStack_c);
    __dest = pcStack_c + sVar1;
    strcpy(__dest,param_2);
    iVar2 = lstat(pcStack_c,&sStack_94);
    if (-1 < iVar2) {
      bVar6 = *(byte *)(param_1 + 0x75);
      *(byte *)(param_1 + 0x75) = bVar6 & 0x7f;
      *(byte *)(param_1 + 0x74) = *(byte *)(param_1 + 0x74) & 0xfe;
      *(byte *)(param_1 + 0x75) = bVar6 & 0x3f;
      if ((sStack_94.st_nlink & 0xf000) == 0x4000) {
        iVar2 = FUN_00413610(param_1,param_2);
        if (iVar2 == 0) {
          puVar3 = (undefined4 *)FUN_00411c04();
          if (*(int *)(param_1 + 0x14) == 0) {
            pvVar4 = malloc(4);
            *(void **)(param_1 + 0x18) = pvVar4;
          }
          else {
            pvVar4 = realloc(*(void **)(param_1 + 0x18),*(int *)(param_1 + 0x14) * 4 + 4);
            *(void **)(param_1 + 0x18) = pvVar4;
          }
          *(undefined4 **)(*(int *)(param_1 + 0x18) + *(int *)(param_1 + 0x14) * 4) = puVar3;
          *(int *)(param_1 + 0x14) = *(int *)(param_1 + 0x14) + 1;
          bVar6 = *(byte *)(puVar3 + 0x1d);
          *(byte *)(puVar3 + 0x1d) = bVar6 | 8;
          *(byte *)(puVar3 + 0x1d) = bVar6 | 10;
          uVar5 = FUN_00411d68(param_2);
          *puVar3 = uVar5;
          sVar1 = strlen(param_2);
          puVar3[1] = sVar1;
          puVar3[3] = 0;
          puVar3[5] = 0;
          puVar3[10] = param_1;
          puVar3[2] = sStack_94.st_nlink;
          bVar7 = DAT_10017493 != '\0';
          if (bVar7) {
            bVar7 = *(int *)(param_1 + 0x74) << 0xb < 0;
          }
          *(byte *)((int)puVar3 + 0x75) = bVar7 << 4 | *(byte *)((int)puVar3 + 0x75) & 0xef;
          if ((int)(puVar3[0x1d] << 0xb) < 0) {
            FUN_00427e30(puVar3);
          }
          *(byte *)(param_1 + 0x75) = *(byte *)(param_1 + 0x75) | 0x80;
          bVar6 = FUN_004138e8(puVar3,pcStack_c,__dest,0);
          *(byte *)(param_1 + 0x75) = (bVar6 & 1) << 6 | *(byte *)(param_1 + 0x75) & 0xbf;
          if (((*(byte *)(param_1 + 0x74) & 1) != 0) || (*(char *)(param_1 + 0x75) < '\0')) {
            FUN_004144ec(param_1);
          }
        }
      }
      else {
        FUN_0042df08();
        iVar2 = FUN_00413580(param_1,param_2);
        if (iVar2 == 0) {
          puVar3 = (undefined4 *)FUN_00411b84();
          if (*(int *)(param_1 + 0xc) == 0) {
            pvVar4 = malloc(4);
            *(void **)(param_1 + 0x10) = pvVar4;
          }
          else {
            pvVar4 = realloc(*(void **)(param_1 + 0x10),*(int *)(param_1 + 0xc) * 4 + 4);
            *(void **)(param_1 + 0x10) = pvVar4;
          }
          *(undefined4 **)(*(int *)(param_1 + 0x10) + *(int *)(param_1 + 0xc) * 4) = puVar3;
          *(int *)(param_1 + 0xc) = *(int *)(param_1 + 0xc) + 1;
          *(byte *)(puVar3 + 10) = *(byte *)(puVar3 + 10) | 2;
          *(byte *)((int)puVar3 + 0x29) = *(byte *)((int)puVar3 + 0x29) | 0x80;
          uVar5 = FUN_00411d68(param_2);
          *puVar3 = uVar5;
          sVar1 = strlen(param_2);
          puVar3[1] = sVar1;
          puVar3[2] = sStack_94.st_nlink;
          uVar5 = FUN_00433b44(pcStack_c);
          puVar3[8] = uVar5;
          *(int *)(param_1 + 0x1c) = (*(int *)(param_1 + 0x1c) + sStack_94.st_blksize) - puVar3[3];
          uVar5 = FUN_004118b0(param_1);
          *(undefined4 *)(param_1 + 0x24) = uVar5;
          puVar3[3] = sStack_94.st_blksize;
          if (window_width < sStack_94.st_blksize) {
            window_width = sStack_94.st_blksize;
          }
          if (window_height < *(int *)(param_1 + 0x1c)) {
            window_height = *(int *)(param_1 + 0x1c);
          }
          puVar3[4] = sStack_94.st_mtim.tv_sec;
          FUN_00412400(puVar3);
                    // WARNING: Bad instruction - Truncating control flow here
          halt_baddata();
        }
        FUN_00417c2c(param_1,param_2);
      }
    }
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void newTopWindow(undefined4 param_1)

{
  (&DAT_10016c10)[numtop] = param_1;
  numtop = numtop + 1;
  FUN_00421c14();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void deleteTopWindow(int param_1)

{
  int iVar1;
  int iVar2;
  int *piVar3;
  int *piVar4;
  
  iVar1 = 0;
  if (0 < numtop) {
    piVar3 = &DAT_10016c10;
    do {
      if (param_1 == *piVar3) {
        iVar2 = numtop + -1;
        if (iVar1 < iVar2) {
          do {
            piVar4 = piVar3 + 1;
            *piVar3 = piVar3[1];
            piVar3 = piVar4;
          } while (piVar4 < &DAT_10016c10 + iVar2);
        }
                    // WARNING: Bad instruction - Truncating control flow here
        halt_baddata();
      }
      iVar1 = iVar1 + 1;
      piVar3 = piVar3 + 1;
    } while (iVar1 < numtop);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void deleteCmapWindow(int param_1)

{
  int *piVar1;
  int *piVar2;
  int iVar3;
  
  iVar3 = 0;
  if (0 < numcmap) {
    piVar1 = &current_colormap;
    do {
      if (param_1 == *piVar1) {
        numcmap = numcmap + -1;
        if (iVar3 < numcmap) {
          do {
            piVar2 = piVar1 + 1;
            *piVar1 = piVar1[1];
            piVar1 = piVar2;
          } while (piVar2 < &current_colormap + numcmap);
        }
        FUN_00421c14();
        halt_baddata();
      }
      iVar3 = iVar3 + 1;
      piVar1 = piVar1 + 1;
    } while (iVar3 < numcmap);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void newCmapWindow(undefined4 param_1)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  
  if (0 < numcmap) {
    puVar1 = &current_colormap + numcmap;
    do {
      puVar2 = puVar1 + -1;
      *puVar1 = puVar1[-1];
      puVar1 = puVar2;
    } while ((undefined4 *)((int)&current_colormap + 3) < puVar2);
  }
  numcmap = numcmap + 1;
  current_colormap = param_1;
  FUN_00421c14();
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void set_status_message(undefined4 param_1,int param_2)

{
  undefined4 *puVar1;
  undefined4 uVar2;
  int *piVar3;
  int iVar4;
  int unaff_gp;
  int local_54;
  undefined4 local_50;
  
  puVar1 = (undefined4 *)(**(code **)(unaff_gp + -0x7b40))(0xc);
  uVar2 = (**(code **)(unaff_gp + -0x7e90))(param_1);
  *puVar1 = uVar2;
  local_54 = *(int *)(unaff_gp + -0x7f60);
  piVar3 = (int *)(*(int *)(unaff_gp + -0x7f98) + 0x20);
  iVar4 = *piVar3;
  *(undefined1 *)(puVar1 + 2) = 0;
  puVar1[1] = iVar4;
  *piVar3 = (int)puVar1;
  local_54 = local_54 + 0x1d4d;
  local_50 = *puVar1;
  (**(code **)(unaff_gp + -0x7cc0))
            (*(undefined4 *)(*(int *)(unaff_gp + -0x7f94) + 0x6648),&local_54,1);
  if (param_2 != 0) {
    (**(code **)(unaff_gp + -0x7e94))
              (**(undefined4 **)(unaff_gp + -0x7600),param_2,*(undefined4 *)(unaff_gp + -0x7a9c),
               puVar1);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void setLabelColors(void)

{
  undefined4 *puVar1;
  undefined **ppuVar2;
  undefined4 *puVar3;
  undefined4 auStack_30 [2];
  undefined4 uStack_28;
  undefined4 *puStack_24;
  undefined4 uStack_20;
  undefined4 uStack_1c;
  
  puStack_24 = auStack_30;
  uStack_28 = 0xf6615ba;
  XtGetValues(toplevel,&uStack_28,1);
  puVar1 = &legendLabel;
  ppuVar2 = &dcolorBoxes;
  puVar3 = &labelColors;
  do {
    FUN_00428cc0(*(undefined4 *)(*ppuVar2 + 4),puVar3,*puVar1,auStack_30[0]);
    puVar1 = puVar1 + 1;
    ppuVar2 = ppuVar2 + 1;
    puVar3 = puVar3 + 4;
  } while (puVar1 != (undefined4 *)&legendShowing);
  if (grid_display_flag == '\0') {
    FUN_00428cc0(highlight_packed_color,&lhLabelColor,*(undefined4 *)(curcontextwindows + 0x2c),auStack_30[0])
    ;
  }
  else {
    FUN_00428cc0(current_packed_color,&lhLabelColor,*(undefined4 *)(curcontextwindows + 0x2c),auStack_30[0])
    ;
  }
  if (*(int *)(altcontextwindows + 0x2c) != 0) {
    puStack_24 = cached_context_ptr;
    uStack_1c = lhLabelColor;
    uStack_28 = 0xf6615f6;
    uStack_20 = 0xf661554;
    XtSetValues(*(undefined4 *)(altcontextwindows + 0x2c),&uStack_28,2);
  }
  FUN_00428cc0(DAT_10017604,&monitorLabelColor,monitorLabelWidget,auStack_30[0]);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createViewer(undefined4 param_1,undefined4 *param_2,undefined4 param_3)

{
  undefined4 uVar1;
  undefined4 uVar2;
  
  uVar1 = XmCreateForm(param_1,"viewer",param_2,param_3);
  *(undefined4 *)(curcontextwindows + 0x10) = uVar1;
  install_help_callback(*(undefined4 *)(curcontextwindows + 0x10),&viewerHelp);
  *param_2 = 0xe3f3701;
  param_2[1] = 1;
  param_2[2] = 0xe3f40cb;
  param_2[3] = 1;
  param_2[4] = 0xe3f46dd;
  param_2[5] = 1;
  uVar1 = XmCreateRowColumn(*(undefined4 *)(curcontextwindows + 0x10),"viewerButtons",param_2,3);
  XtManageChild(uVar1);
  XtAddEventHandler(uVar1,4,0,FUN_0042a440,*(undefined4 *)(curcontextwindows + 8));
  uVar2 = XmCreatePushButton(uVar1,&DAT_1000e928,param_2,0);
  XtManageChild(uVar2);
  XtAddCallback(uVar2,0xe3f35b3,FUN_00429f60,*(undefined4 *)(curcontextwindows + 8));
  uVar2 = XmCreatePushButton(uVar1,&DAT_1000e930,param_2,0);
  XtAddCallback(uVar2,0xe3f35b3,editCB,*(undefined4 *)(curcontextwindows + 8));
  XtManageChild(uVar2);
  uVar2 = XmCreatePushButton(uVar1,"saveFile",param_2,0);
  *(undefined4 *)(curcontextwindows + 0x18) = uVar2;
  XtManageChild(*(undefined4 *)(curcontextwindows + 0x18));
  XtAddCallback(*(undefined4 *)(curcontextwindows + 0x18),0xe3f35b3,FUN_0042a2d8,
                *(undefined4 *)(curcontextwindows + 8));
  *param_2 = 0xe3f4b1d;
  param_2[1] = 1;
  param_2[2] = 0xe3f40cb;
  param_2[3] = 1;
  param_2[4] = 0xe3f46dd;
  param_2[5] = 1;
  param_2[6] = 0xe3f3701;
  param_2[7] = 3;
  param_2[8] = 0xe3f3753;
  param_2[9] = uVar1;
  param_2[10] = 0xe3f3d12;
  param_2[0xb] = 0;
  uVar1 = XmCreateScrolledText(*(undefined4 *)(curcontextwindows + 0x10),"viewerText",param_2,6);
  *(undefined4 *)(curcontextwindows + 0x14) = uVar1;
  XtAddEventHandler(*(undefined4 *)(curcontextwindows + 0x14),4,0,myContext,
                    *(undefined4 *)(curcontextwindows + 8));
  XtManageChild(*(undefined4 *)(curcontextwindows + 0x14));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void widgetHelp(undefined4 param_1,undefined4 param_2)

{
  XtAddCallback(param_1,0xe3f3e9f,FUN_0042b3f4,param_2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void install_help_callback(undefined4 param_1,undefined4 param_2)

{
  int unaff_gp;
  
  (**(code **)(unaff_gp + -0x7c54))
            (param_1,*(int *)(unaff_gp + -0x7f60) + 0x1b37,*(int *)(unaff_gp + -0x7fe0) + -0x4c0c,
             param_2);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void editCB(void)

{
  char *pcVar1;
  size_t sVar2;
  char acStack_564 [1380];
  
  if (((*(int *)(curcontext + 0x48) != 0) && (*(int *)(curcontext + 0x44) != 0)) &&
     (pcVar1 = getenv("WINEDITOR"), pcVar1 != (char *)0x0)) {
    sprintf(acStack_564,"%s ",pcVar1);
    sVar2 = strlen(acStack_564);
    build_path_string(acStack_564 + sVar2,*(undefined4 *)(curcontext + 0x44));
    strcat(acStack_564,(char *)**(undefined4 **)(curcontext + 0x48));
    strcat(acStack_564,"&");
    system(acStack_564);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void GlxCreateMDraw(void)

{
  undefined4 in_a3;
  int unaff_gp;
  int iStackX_0;
  undefined1 auStackX_4 [4];
  undefined1 auStackX_8 [8];
  undefined1 *puVar1;
  undefined4 uVar2;
  
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  (**(code **)(unaff_gp + -0x7ff0))();
  __Argv = auStackX_4;
  _DAT_0fb52740 = auStackX_8 + iStackX_0 * 4;
  __Argc = iStackX_0;
  puVar1 = &_mips_gp0_value;
  uVar2 = 0;
  __istart();
  (**(code **)(puVar1 + -0x7c5c))();
  uVar2 = (**(code **)(puVar1 + -0x7ae8))
                    (**(undefined4 **)(puVar1 + -0x760c),**(undefined4 **)(puVar1 + -0x7608),
                     **(undefined4 **)(puVar1 + -0x7f48),in_a3,puVar1,uVar2);
  (**(code **)(puVar1 + -0x7c60))(uVar2);
  return;
}

void set_main_gl_window(void)

{
  int unaff_gp;
  
  (**(code **)(unaff_gp + -0x7d0c))
            (**(undefined4 **)(unaff_gp + -0x75fc),
             *(undefined4 *)**(undefined4 **)(unaff_gp + -0x767c));
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void displayHourglass(undefined4 param_1)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 auStack_20 [3];
  undefined4 auStack_14 [3];
  undefined4 uStack_8;
  undefined4 uStack_4;
  
  if (DAT_10009630 == 0) {
    uVar1 = XtWindow();
    uStack_4 = XCreateBitmapFromData(display,uVar1,&DAT_10009530,0x20,0x20);
    uVar1 = XtWindow(param_1);
    uStack_8 = XCreateBitmapFromData(display,uVar1,&DAT_100095b0,0x20,0x20);
    iVar2 = XtScreen(param_1);
    auStack_20[0] = *(undefined4 *)(iVar2 + 0x38);
    iVar2 = XtScreen(param_1);
    auStack_14[0] = *(undefined4 *)(iVar2 + 0x34);
    iVar2 = XtScreen(param_1);
    XQueryColors(display,*(undefined4 *)(iVar2 + 0x30),auStack_20,2);
    DAT_10009630 = XCreatePixmapCursor(display,uStack_4,uStack_8,auStack_20,auStack_14,0xf,0xf);
    XFreePixmap(display,uStack_4);
    XFreePixmap(display,uStack_8);
  }
  uVar1 = XtWindow(param_1);
  XDefineCursor(display,uVar1,DAT_10009630);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void overlayMenuUnmappedCB(void)

{
  undefined4 uVar1;
  
  uVar1 = XtWindow();
  FUN_00421e58(uVar1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void createOverview(void)

{
  float fVar1;
  int iVar2;
  char **ppcVar3;
  char *pcVar4;
  double dVar5;
  uint uVar6;
  undefined8 in_f18;
  uint in_fcsr;
  char *pcStack_b8;
  undefined4 auStack_b4 [3];
  undefined4 uStack_a8;
  int iStack_a4;
  char *apcStack_a0 [5];
  undefined4 uStack_8c;
  undefined4 uStack_88;
  undefined4 uStack_84;
  char *pcStack_80;
  undefined4 *puStack_7c;
  char *pcStack_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  int iStack_6c;
  undefined4 uStack_68;
  int iStack_64;
  
  uVar6 = (uint)((ulonglong)in_f18 >> 0x20);
  if (DAT_10006ebc == '\0') {
    XtAppAddActions(app_context,&DAT_10006e94,4);
    DAT_10006ebc = '\x01';
  }
  apcStack_a0[1] = (char *)auStack_b4;
  apcStack_a0[0] = (char *)0xf6615ba;
  iVar2 = init_display_mode();
  apcStack_a0[3] = (char *)&pcStack_b8;
  if (iVar2 == 0) {
    apcStack_a0[2] = "overlayColormap";
  }
  else {
    apcStack_a0[2] = "popupColormap";
  }
  XtGetValues(*(undefined4 *)(curcontextwindows + 8),apcStack_a0,2);
  apcStack_a0[0] = (char *)0xf662094;
  apcStack_a0[1] = (char *)0x1;
  overview_popup_shell = XtCreatePopupShell("overview",_DAT_0f6d16fc,toplevel,apcStack_a0,1);
  XtAddCallback(overview_popup_shell,0xf6615c9,FUN_00421180,0);
  uStack_a8 = XmCreateForm(overview_popup_shell,"overviewForm",apcStack_a0,0);
  XtManageChild(uStack_a8);
  install_help_callback(uStack_a8,&overviewHelp);
  iVar2 = init_display_mode();
  if (iVar2 != 0) {
    DAT_10006e64 = 0x3000;
  }
  apcStack_a0[1] = (char *)0x1;
  apcStack_a0[0] = (char *)0xe3f4b1d;
  apcStack_a0[2] = (char *)0xe3f40cb;
  apcStack_a0[4] = (char *)0xe3f46dd;
  uStack_88 = 0xe3f3701;
  pcStack_80 = "glxConfig";
  puStack_7c = &DAT_10006e64;
  apcStack_a0[3] = (char *)0x1;
  uStack_8c = 1;
  uStack_84 = 1;
  iVar2 = init_display_mode();
  if (iVar2 == 0) {
    pcStack_78 = "useOverlay";
  }
  else {
    pcStack_78 = "usePopup";
  }
  uStack_74 = 1;
  uStack_70 = 0xf661888;
  dVar5 = ((double)maxx - (double)minx) * (double)((ulonglong)uVar6 << 0x20);
  uStack_68 = 0xf66160a;
  if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
    dVar5 = ROUND(dVar5);
  }
  else {
    dVar5 = FLOOR(dVar5);
  }
  iStack_6c = (int)dVar5;
  if ((((in_fcsr | 3) ^ 2) & 3) == 0) {
    fVar1 = ROUND(maxy - miny);
  }
  else {
    fVar1 = FLOOR(maxy - miny);
  }
  iStack_64 = (int)fVar1;
  iStack_a4 = 8;
  iVar2 = init_display_mode();
  if (iVar2 == 0) {
    ppcVar3 = apcStack_a0 + iStack_a4 * 2;
    *ppcVar3 = "overlayColormap";
  }
  else {
    ppcVar3 = apcStack_a0 + iStack_a4 * 2;
    *ppcVar3 = "popupColormap";
  }
  ppcVar3[1] = pcStack_b8;
  overview_gl_widget = GlxCreateMDraw(uStack_a8,"overviewGlw",apcStack_a0,iStack_a4 + 1);
  XtAddCallback(overview_gl_widget,"exposeCallback",FUN_00420bfc,0);
  iVar2 = init_display_mode();
  if (iVar2 == 0) {
    pcVar4 = "overlayExposeWindow";
  }
  else {
    pcVar4 = "popupExposeWindow";
  }
  XtAddCallback(overview_gl_widget,pcVar4,FUN_00420c50,0);
  XtAddCallback(overview_gl_widget,"resizeCallback",FUN_00420ca4,0);
  XtAddCallback(overview_gl_widget,"ginitCallback",FUN_00420e74,0);
  XtManageChild(overview_gl_widget);
  if (DAT_10006e60 == 0) {
    DAT_10006e60 = XtParseTranslationTable(overviewGlw_translations);
  }
  XtOverrideTranslations(overview_gl_widget,DAT_10006e60);
  apcStack_a0[0] = (char *)0xf6615ba;
  apcStack_a0[1] = (char *)auStack_b4[0];
  XtSetValues(overview_gl_widget,apcStack_a0,1);
  XtManageChild(overview_popup_shell);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void postMenu(undefined4 param_1,undefined4 param_2,int param_3)

{
  undefined4 uVar1;
  
  if (*(int *)(param_3 + 0x34) == 3) {
    uVar1 = XtWindow(popup_menu_widget);
    FUN_00421dd0(uVar1);
    XmMenuPosition(popup_menu_widget,param_3);
    XtManageChild(popup_menu_widget);
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void overlayMenuMappedCB(void)

{
  undefined4 uVar1;
  
  uVar1 = XtWindow();
  FUN_00421dd0(uVar1);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void CreateSelectionMenus(undefined4 param_1,undefined4 param_2)

{
  undefined4 uVar1;
  undefined4 *puVar2;
  undefined4 uStack_6c;
  undefined4 uStack_68;
  undefined4 uStack_64;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 uStack_10;
  undefined4 uStack_8;
  undefined4 uStack_4;
  
  uStack_6c = 0;
  FUN_00432094(display,0,&uStack_68,&uStack_6c);
  uStack_4 = XmCreatePulldownMenu(param_1,"dirPane",&uStack_68,uStack_6c);
  XtAddCallback(uStack_4,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(uStack_4,0xe3f4c38,overlayMenuUnmappedCB,0);
  install_help_callback(uStack_4,&directoryHelp);
  uStack_6c = 0;
  menu_monitor_directory = XmCreateToggleButton(uStack_4,"menuMonitorDirectory",&uStack_68,0);
  XtAddCallback(menu_monitor_directory,0xe3f4ca5,menu_monitor_dir_callback,0);
  XtManageChild(menu_monitor_directory);
  uStack_6c = 0;
  uStack_10 = XmCreatePushButton(uStack_4,"menuMonitorTree",&uStack_68,0);
  XtAddCallback(uStack_10,0xe3f35b3,FUN_0041dff4,1);
  XtManageChild(uStack_10);
  uStack_6c = 0;
  uStack_10 = XmCreatePushButton(uStack_4,"menuStopMonitorTree",&uStack_68,0);
  XtAddCallback(uStack_10,0xe3f35b3,FUN_0041dff4,0);
  XtManageChild(uStack_10);
  uStack_6c = 0;
  uStack_10 = XmCreatePushButton(uStack_4,"menuRescanSubtree",&uStack_68,0);
  XtAddCallback(uStack_10,0xe3f35b3,FUN_0041e0a8,0);
  XtManageChild(uStack_10);
  uStack_6c = 0;
  current_picked_item = XmCreateToggleButton(uStack_4,"menuPruneDirectory",&uStack_68,0);
  XtAddCallback(current_picked_item,0xe3f4ca5,menu_prune_dir_callback,0);
  XtManageChild(current_picked_item);
  uStack_6c = 2;
  uStack_68 = 0xe3f4a31;
  uStack_60 = 0xf6617e7;
  uStack_5c = 0;
  uStack_64 = uStack_4;
  menu_directory_cascade = XmCreateCascadeButton(param_1,"menuDirectory",&uStack_68,2);
  XtManageChild(menu_directory_cascade);
  install_help_callback(menu_directory_cascade,&directoryHelp);
  XtAddEventHandler(param_2,4,0,postMenu,0);
  uStack_6c = 0;
  FUN_00432094(display,0,&uStack_68,&uStack_6c);
  XtSetSensitive(menu_directory_cascade,0);
  popup_menu_widget = XmCreatePopupMenu(param_2,"popupMenu",&uStack_68,uStack_6c);
  XtAddCallback(popup_menu_widget,0xe3f4c38,overlayMenuUnmappedCB,0);
  install_help_callback(popup_menu_widget,&fileHelp);
  uStack_6c = 0;
  FUN_00432094(display,0,&uStack_68,&uStack_6c);
  uStack_8 = XmCreatePulldownMenu(param_1,"filePane",&uStack_68,uStack_6c);
  XtAddCallback(uStack_8,0xe3f41fe,overlayMenuMappedCB,0);
  XtAddCallback(uStack_8,0xe3f4c38,overlayMenuUnmappedCB,0);
  install_help_callback(uStack_8,&fileHelp);
  uStack_6c = 0;
  uVar1 = XmCreateLabel(popup_menu_widget,"menuFile",&uStack_68,0);
  XtManageChild(uVar1);
  uStack_6c = 0;
  uVar1 = XmCreateSeparator(popup_menu_widget,"popupSep",&uStack_68,0);
  XtManageChild(uVar1);
  uStack_6c = 0;
  menu_open_file_1 = XmCreatePushButton(popup_menu_widget,"menuOpenFile",&uStack_68,0);
  XtAddCallback(menu_open_file_1,0xe3f35b3,menu_open_file_callback,0);
  XtManageChild(menu_open_file_1);
  (&menu_items_array)[array_index] = menu_open_file_1;
  array_index = array_index + 1;
  menu_open_file_2 = XmCreatePushButton(uStack_8,"menuOpenFile",&uStack_68,uStack_6c);
  XtAddCallback(menu_open_file_2,0xe3f35b3,menu_open_file_callback,0);
  XtManageChild(menu_open_file_2);
  puVar2 = &menu_items_array + array_index;
  array_index = array_index + 1;
  *puVar2 = menu_open_file_2;
  uStack_6c = 0;
  menu_print_file_1 = XmCreatePushButton(popup_menu_widget,"menuPrintFile",&uStack_68,0);
  XtAddCallback(menu_print_file_1,0xe3f35b3,menu_print_file_callback,0);
  XtManageChild(menu_print_file_1);
  (&menu_items_array)[array_index] = menu_print_file_1;
  array_index = array_index + 1;
  menu_print_file_2 = XmCreatePushButton(uStack_8,"menuPrintFile",&uStack_68,uStack_6c);
  XtAddCallback(menu_print_file_2,0xe3f35b3,menu_print_file_callback,0);
  XtManageChild(menu_print_file_2);
  puVar2 = &menu_items_array + array_index;
  array_index = array_index + 1;
  *puVar2 = menu_print_file_2;
  uStack_6c = 0;
  menu_delete_file_1 = XmCreateToggleButton(popup_menu_widget,"menuDeleteFile",&uStack_68,0);
  XtAddCallback(menu_delete_file_1,0xe3f4ca5,menu_delete_file_callback,0);
  XtManageChild(menu_delete_file_1);
  (&menu_items_array)[array_index] = menu_delete_file_1;
  array_index = array_index + 1;
  menu_delete_file_2 = XmCreateToggleButton(uStack_8,"menuDeleteFile",&uStack_68,uStack_6c);
  XtAddCallback(menu_delete_file_2,0xe3f4ca5,menu_delete_file_callback,0);
  XtManageChild(menu_delete_file_2);
  (&menu_items_array)[array_index] = menu_delete_file_2;
  array_index = array_index + 1;
  uStack_64 = move_file_xmstring;
  uStack_68 = 0xe3f40b5;
  uStack_60 = 0xf6617e7;
  uStack_6c = 2;
  uStack_5c = 0;
  menu_move_file_1 = XmCreatePushButton(popup_menu_widget,"menuMoveFile",&uStack_68,2);
  XtAddCallback(menu_move_file_1,0xe3f35b3,file_operation_callback,1);
  XtManageChild(menu_move_file_1);
  menu_move_file_2 = XmCreatePushButton(uStack_8,"menuMoveFile",&uStack_68,uStack_6c);
  XtAddCallback(menu_move_file_2,0xe3f35b3,file_operation_callback,1);
  XtManageChild(menu_move_file_2);
  uStack_64 = copy_file_xmstring;
  uStack_68 = 0xe3f40b5;
  uStack_60 = 0xf6617e7;
  uStack_6c = 2;
  uStack_5c = 0;
  menu_copy_file_1 = XmCreatePushButton(popup_menu_widget,"menuCopyFile",&uStack_68,2);
  XtAddCallback(menu_copy_file_1,0xe3f35b3,file_operation_callback,2);
  XtManageChild(menu_copy_file_1);
  menu_copy_file_2 = XmCreatePushButton(uStack_8,"menuCopyFile",&uStack_68,uStack_6c);
  XtAddCallback(menu_copy_file_2,0xe3f35b3,file_operation_callback,2);
  XtManageChild(menu_copy_file_2);
  uStack_64 = link_file_xmstring;
  uStack_68 = 0xe3f40b5;
  uStack_60 = 0xf6617e7;
  uStack_6c = 2;
  uStack_5c = 0;
  menu_link_file_1 = XmCreatePushButton(popup_menu_widget,"menuLinkFile",&uStack_68,2);
  XtAddCallback(menu_link_file_1,0xe3f35b3,file_operation_callback,3);
  XtManageChild(menu_link_file_1);
  menu_link_file_2 = XmCreatePushButton(uStack_8,"menuLinkFile",&uStack_68,uStack_6c);
  XtAddCallback(menu_link_file_2,0xe3f35b3,file_operation_callback,3);
  XtManageChild(menu_link_file_2);
  uStack_68 = 0xe3f4a31;
  uStack_60 = 0xf6617e7;
  uStack_6c = 2;
  uStack_5c = 0;
  uStack_64 = uStack_8;
  menu_file_cascade = XmCreateCascadeButton(param_1,"menuFile",&uStack_68,2);
  XtManageChild(menu_file_cascade);
  install_help_callback(menu_file_cascade,&fileHelp);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void SG_getPopupArgs(undefined4 param_1,undefined4 param_2,int param_3,int *param_4)

{
  undefined4 uVar1;
  int iVar2;
  int iVar3;
  
  uVar1 = FUN_004314e0(param_1,param_2,&temp_data_buffer,4);
  iVar2 = FUN_00432370(param_1,param_2,uVar1,&temp_data_buffer,4);
  if (iVar2 < 0) {
    FUN_00431b34(param_1,param_2,param_3,param_4);
  }
  else {
    uVar1 = FUN_00431354(param_1,param_2);
    *(undefined4 *)(param_3 + *param_4 * 8) = 0xf6615ba;
    *(undefined4 *)(param_3 + *param_4 * 8 + 4) = uVar1;
    iVar3 = *param_4;
    *param_4 = iVar3 + 1;
    *(undefined4 *)(param_3 + (iVar3 + 1) * 8) = 0xf6615c3;
    *(undefined4 *)(param_3 + *param_4 * 8 + 4) = 2;
    iVar3 = *param_4;
    *param_4 = iVar3 + 1;
    *(undefined4 *)(param_3 + (iVar3 + 1) * 8) = 0xf661fe4;
    *(int *)(param_3 + *param_4 * 8 + 4) = iVar2;
    *param_4 = *param_4 + 1;
  }
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}

void destroyCopyright(void)

{
  XtDestroyWidget(active_file_list);
                    // WARNING: Bad instruction - Truncating control flow here
  halt_baddata();
}
